### ISSUE TITLE
NullReference exception in SKTextBlobBuilder

### ISSUE THREAD

**Issue by MuziburRahman** [mono/SkiaSharp#1094]
What is the proper way to use SKTextBlobBuilder? 
I wrote this method and it throws `NullReferenceException`:
```
public static SKTextBlob GetTextBlob(string text)
{
	using SKTextBlobBuilder text_builder = new SKTextBlobBuilder();
	text_builder.AddRun(LabelTextFormat, 0, 0, text.Select(c => (ushort)c).ToArray());
	return text_builder.Build();
}
```
where `LabelTextFormat` is a SKPaint object; Note that I ensured neither the `text` nor the `LabelTextFormat` is null when the method is executed. 

I then discovered that if I set the `TextEncoding` property of the paint to `SKTextEncoding.GlyphId`, the method works fine, no exception.

Another problem is that, if I keep the encoding to `SKTextEncoding.GlyphId`, the text isn't rendered correctly. Strange characters appears instead of the text provided.

**Comment by Gillibald** [comment]
https://github.com/mono/SkiaSharp/blob/master/binding/Binding/SKPaint.cs#L486 is your friend. SKTextBlob is the low level component to store a run of glyphs and only works with SKTextEncoding.GlyphId

**Comment by Gillibald** [comment]
I think https://github.com/mono/SkiaSharp/blob/master/binding/Binding/SKTextBlob.cs#L53 throws underneath when something goes wrong.

**Comment by mattleibow** [comment]
As @Gillibald says, the text blobs are lower level that works with individual glyphs rather than characters as we know it.

**Comment by Ziriax** [comment]
I'm also having a `NullReferenceException`, but I'm using glyph-ids as returned from `SKPaint`.

I'm using preview 27.

The stack trace is:
```
  at System.Buffer.Memmove(Byte& dest, Byte& src, UInt64 len)
   at System.Buffer.Memmove[T](T& destination, T& source, UInt64 elementCount)
   at System.ReadOnlySpan`1.CopyTo(Span`1 destination)
   at SkiaSharp.SKRunBuffer.SetGlyphs(ReadOnlySpan`1 glyphs)
   at SkiaSharp.SKTextBlobBuilder.AddHorizontalRun(SKPaint font, Single y, ReadOnlySpan`1 glyphs, ReadOnlySpan`1 positions, ReadOnlySpan`1 text, ReadOnlySpan`1 clusters, Nullable`1 bounds)
   at SkiaSharp.SKTextBlobBuilder.AddHorizontalRun(SKPaint font, Single y, UInt16[] glyphs, Single[] positions)
   at SkiaRenderTests.Program.PositionedGlyphRun(RenderTestContext context) in C:\repos\ExpressDev\Source\Research\SkiaRenderTests\SkiaRenderTests\TestText.cs:line 191
```

My code is just:

```
var glyphIds = textPaint.GetGlyphs("X");
var glyphXs = new float[]{0};
using var builder = new SKTextBlobBuilder();
builder.AddHorizontalRun(textPaint, 0, glyphIds, glyphXs);
```

Should I make a new issue for this? I need to manually position glyphs, I don't find another API for this.

**Comment by mattleibow** [comment]
Thanks for opening the issue, I got a fix building that make life much esier.
