### ISSUE TITLE
[BUG] Tizen application crashes

### ISSUE THREAD

**Issue by VladislavAntonyuk** [mono/SkiaSharp#1273]
**Description**

```

Exception
System.EntryPointNotFoundException: Unable to find an entry point named 'sk_refcnt_safe_unref' in shared library 'libSkiaSharp'.
at SkiaSharp.SkiaApi.sk_refcnt_safe_unref(IntPtr refcnt)
at SkiaSharp.SKObject.DisposeNative()
at SkiaSharp.SKNativeObject.Dispose(Boolean disposing)
at SkiaSharp.SKObject.Dispose(Boolean disposing)
at SkiaSharp.SKSurface.Dispose(Boolean disposing)
at SkiaSharp.SKNativeObject.DisposeInternal()
at SkiaSharp.SKNativeObject.Dispose()
at SkiaSharp.Views.Tizen.SKCanvasView.OnDrawFrame()
at SkiaSharp.Views.Tizen.CustomRenderingView.<.ctor>b__4_1(IntPtr d, IntPtr o)
at Tizen.Applications.CoreBackend.UICoreBackend.Run(String[] args)
at Tizen.Applications.CoreApplication.Run(String[] args)
at Tizen.Applications.CoreUIApplication.Run(String[] args)
```

**Code**

**Expected Behavior**

**Actual Behavior**

Crash

**Basic Information**

- Version with issue: 2.80.0-alpha.4
- Last known good version:  1.68.2-preview.43 
- IDE:  Visual Studio
- Platform Target Frameworks: 
  - Tizen:  5.5 Simulator 

**Screenshots**

**Reproduction Link**

**Comment by mattleibow** [comment]
What nuget versions are you using?

**Comment by VladislavAntonyuk** [comment]
the issue appeared after updating from 1.68.2-preview.43 to 2.80.0-alpha.4

**Comment by mattleibow** [comment]
Unfortunately the v2 packages do not yet have a build for Tizen. This is due to the Tizen SDK not including a new enough version of the clang compiler. We are working with that team to get an updated SDK as soon as we can. As of today, the plan is to ship Tizen with the stable v2 or sooner if the compiler is ready.

**Comment by mattleibow** [comment]
Moving this to v2.80.1 as I don't think that we will get the SDKs in time for the initial release. Very sad, but I'll do my best to get it in.

**Comment by mattleibow** [comment]
We got the SDKs! All ready again!
