### ISSUE TITLE
Building release version for android failed

### ISSUE THREAD

**Issue by xDaijobu** [mono/SkiaSharp#1371]
**Description**
I have an error when compiling in Release and generating the APK, in Debug mode if it compiles and it works, in Release I have the following error: The "LinkAssemblies" task failed unexpectedly.

> Severity	Code	Description	Project	File	Line	Suppression State
Error		The "LinkAssemblies" task failed unexpectedly.
Mono.Linker.MarkException: Error processing method: 'SkiaSharp.SKImageInfo SkiaSharp.SKBitmap::DecodeBounds(System.ReadOnlySpan`1<System.Byte>)' in assembly: 'SkiaSharp.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve !0& modreq(System.Runtime.InteropServices.InAttribute) System.ReadOnlySpan`1<System.Byte>::GetPinnableReference()
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	Duren.Android			

Linker configured for Sdk Assemblies Only in Android build options

**Information**
Target framework - Android 9 ( Pie )
Visual Studio 2017 - v15.9.24
Skiasharp.Views.Forms - 1.68.3
Skiasharp 1.68.3
Xamarin.Forms - v4.5.0.725
Xamarin.Android SDK   9.1.7.0 

Link
[App5.zip](https://github.com/mono/SkiaSharp/files/4856763/App5.zip)

Thanks,
Cristover

**Comment by MarieR64** [comment]
Hi,
I had the same mistake. My version of Skiasharp was 1.68.3. I went back to version 1.68.1.1. The error appears from version of Skiasharp 1.68.2.0.
Marie

**Comment by mattleibow** [comment]
Linking https://github.com/xamarin/Xamarin.Forms/issues/11295
