### ISSUE TITLE
[BUG] In UWP, navigating between two pages containing an SKSwapChainPanel raises exception: Failed to create GL surface

### ISSUE THREAD

**Issue by gmurray81** [mono/SkiaSharp#1573]
**Description**

 In UWP, navigating between two pages containing an SKSwapChainPanel raises exception: Failed to create GL surface.
This could have a timing component, since sometimes it does not occur.

**Code**

Given two pages that contain an SKSwapChainPanel, performaing a simple navigation:
```cs
Frame.Navigate(typeof(Page2));
```
can cause this exception (not 100% of the time):
```
System.Exception: Failed to create EGL surface
   at SkiaSharp.Views.GlesInterop.GlesContext.CreateSurface(SwapChainPanel panel, Nullable`1 renderSurfaceSize, Nullable`1 resolutionScale)
   at SkiaSharp.Views.UWP.AngleSwapChainPanel.EnsureRenderSurface()
   at SkiaSharp.Views.UWP.AngleSwapChainPanel.OnCompositionChanged(SwapChainPanel sender, Object args)
```

**Expected Behavior**

No exception should be raised.

**Actual Behavior**

The aforementioned exception is raised.

**Basic Information**

- Version with issue:  2.80.3-preview.18 (but also in latest stable)
- Last known good version:  unknown
- IDE:  Visual Studio 2019
- Platform Target Frameworks: 
  - UWP:  
- Target Devices:   
  - Windows 10 PC
  
<details>
  <summary>Detailed IDE/OS information (click to expand)</summary>
  
```

PASTE ANY DETAILED VERSION INFO HERE

```
</details>

**Screenshots**

**Reproduction Link**

**Comment by gmurray81** [comment]
For ease of reproduction:

MainPage.xaml:
```xml
<Page
    x:Class="SkiaBug.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:SkiaBug"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    xmlns:sk="using:SkiaSharp.Views.UWP"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto"></RowDefinition>
            <RowDefinition></RowDefinition>
        </Grid.RowDefinitions>
        <Button Content="Click" Click="Button_Click"></Button>
        <sk:SKSwapChainPanel Grid.Row="1"></sk:SKSwapChainPanel>        
    </Grid>
</Page>
```

MainPage.xaml.cs:
```cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices.WindowsRuntime;
using Windows.Foundation;
using Windows.Foundation.Collections;
using Windows.UI.Xaml;
using Windows.UI.Xaml.Controls;
using Windows.UI.Xaml.Controls.Primitives;
using Windows.UI.Xaml.Data;
using Windows.UI.Xaml.Input;
using Windows.UI.Xaml.Media;
using Windows.UI.Xaml.Navigation;

// The Blank Page item template is documented at https://go.microsoft.com/fwlink/?LinkId=402352&clcid=0x409

namespace SkiaBug
{
    /// <summary>
    /// An empty page that can be used on its own or navigated to within a Frame.
    /// </summary>
    public sealed partial class MainPage : Page
    {
        public MainPage()
        {
            this.InitializeComponent();
        }

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            Frame.Navigate(typeof(Page2));
        }
    }
}
```

Page2.xaml:
```xml
<Page
    x:Class="SkiaBug.Page2"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:SkiaBug"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    xmlns:sk="using:SkiaSharp.Views.UWP"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}"
    >

    
    <Grid>
        <sk:SKSwapChainPanel></sk:SKSwapChainPanel>
    </Grid>
</Page>
```

**Comment by gmurray81** [comment]
I suspect that this issue is occurring due to how the setup/teardown of the SKSwapChainPanel's are interleaving.

This is the sequence that causes trouble:

- page1 panel is loaded
- page1 panel received CompositionScaleChanged
- navigation occurs
- page2 panel is loaded
- page1 panel is unloaded
- page2 panel received CompositionScaleChanged

I think its the page1 panel being destroyed between the page 2 panel being loaded and the composition scale changing that is causing the problem. If I inject a delay such that the panel on page1 is fully unloaded before I start to load page2's panel, the issue does not ocurr.

**Comment by gmurray81** [comment]
@mattleibow poking around a bit, may it be that both contexts are winding up with the same display handle? And something bad happens when one of the contexts terminates the handle? Maybe it needs to do some ref counting? Or maybe there's a way to check the display handle is still valid before trying to create a surface?

**Comment by gmurray81** [comment]
from poking round, it seems like while eglTerminate might do some internal ref counting specifically for Android, this may not be the case elsewhere. So that interleaved eglTerminate is probably freeing the display resources before the last CompositionScaleChanged tries to recreate the surface.

**Comment by gmurray81** [comment]
Debugging it a bit locally. If I ref count the display, it gets around this error, but something bad happens when it destroys the GRContext for the old panel after the new panel has initialized but before it gets a composition scale change.

**Comment by gmurray81** [comment]
Remaining issue is caused when it releases the resources associated with the GrContext:

```cs
context?.AbandonContext(true);
```

If I change that to false, so that it only abandons the context then all is ok, but I'm not familiar enough with that Skia resources are being managed here to know if that would be leaking stuff. I assume so :)

**Comment by gmurray81** [comment]
BTW, I assume the reason this doesn't come up in the UWP samples is that they just reuse an `SKSwapChainPanel`.

**Comment by gmurray81** [comment]
I created a PR with my current investigation. It is not complete as I can't imagine its valid to omit the cleanup of the GRContext in the panel, but I'm doing it by way of demonstration as to which portion of the cleanup appears to be invalidating shared resources that the other panels can't recover from.

**Comment by gmurray81** [comment]
Note, it seemed like there was some unnecessary churn to the surface since it wasn't checking to see if the composition scale had actually mutated before re-creating, and this was exacerbating things, is the rationale behind the mutation tracking of the composition scale.

**Comment by gmurray81** [comment]
Also note, the cleanup issue is definitely timing dependent. I keep spamming a button that swaps in a new panel, with the panels rendering a background. Sometimes the new panel will come up blank. It thinks it has a valid context/rendertarget/surface, but something internal to the chain is rejecting the painting.

MainPage.xaml:

```xml
<Page
    x:Class="SkiaBug.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:SkiaBug"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    xmlns:sk="using:SkiaSharp.Views.UWP"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <Grid x:Name="grid">
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto"></RowDefinition>
            <RowDefinition></RowDefinition>
        </Grid.RowDefinitions>
        <StackPanel Orientation="Horizontal">
        <Button Content="Click" Click="Button_Click"></Button>
            <Button Content="DPI" Click="Button_Click_1"></Button>
        </StackPanel>
        <!--<sk:SKSwapChainPanel Grid.Row="1" Tag="TEST1" PaintSurface="SKSwapChainPanel_PaintSurface"></sk:SKSwapChainPanel>-->
        
        <ContentControl x:Name="PageContent" HorizontalContentAlignment="Stretch" VerticalContentAlignment="Stretch" Grid.Row="1">
            <ContentControl.Content>
                <sk:SKSwapChainPanel Grid.Row="1" Tag="TEST1" PaintSurface="SKSwapChainPanel_PaintSurface"
                                     Loaded="SKSwapChainPanel_Loaded"
                                     Unloaded="SKSwapChainPanel_Unloaded"
                                     CompositionScaleChanged="SKSwapChainPanel_CompositionScaleChanged"
                                     ></sk:SKSwapChainPanel>
                <!--<SwapChainPanel x:Name="swap1"
                        Loaded="swap1_Loaded"
                        Unloaded="swap1_Unloaded"
                        CompositionScaleChanged="SwapChainPanel_CompositionScaleChanged"></SwapChainPanel>-->
            </ContentControl.Content>
        </ContentControl>
    </Grid>
</Page>
```

MainPage.xaml.cs:

```cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices.WindowsRuntime;
using System.Threading.Tasks;
using Windows.Foundation;
using Windows.Foundation.Collections;
using Windows.UI.Core;
using Windows.UI.Xaml;
using Windows.UI.Xaml.Controls;
using Windows.UI.Xaml.Controls.Primitives;
using Windows.UI.Xaml.Data;
using Windows.UI.Xaml.Input;
using Windows.UI.Xaml.Media;
using Windows.UI.Xaml.Navigation;

// The Blank Page item template is documented at https://go.microsoft.com/fwlink/?LinkId=402352&clcid=0x409

namespace SkiaBug
{
    /// <summary>
    /// An empty page that can be used on its own or navigated to within a Frame.
    /// </summary>
    public sealed partial class MainPage : Page
    {
        public MainPage()
        {
            this.InitializeComponent();
            //System.Diagnostics.Debug.WriteLine("swap1: " + swap1.CompositionScaleX);
        }

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            //PageContent.Children.Clear();
            PageContent.Content = null;
            PageContent.Content = new Page2();
            //Task.Delay(0).ContinueWith((t) =>
            //{
            //    Dispatcher.RunAsync(
            //        Windows.UI.Core.CoreDispatcherPriority.Normal,
            //        (DispatchedHandler)(() =>
            //    {
            //        PageContent.Content = (new Page2());
            //    }));
            //});
            //PageContent.ContentTransitions.Add(new Vector3Transition())
            //Frame.ContentTransitions = null;
            //Frame.Content = new Page2(); //Navigate(typeof(Page2), null, new Windows.UI.Xaml.Media.Animation.SuppressNavigationTransitionInfo() );
        }

        private void SKSwapChainPanel_PaintSurface(object sender, SkiaSharp.Views.UWP.SKPaintGLSurfaceEventArgs e)
        {
            e.Surface.Canvas.Clear(new SkiaSharp.SKColor(255, 0, 0));
        }

        private void SwapChainPanel_CompositionScaleChanged(SwapChainPanel sender, object args)
        {
            System.Diagnostics.Debug.WriteLine("main composition changed: " + sender.CompositionScaleX);
        }

        private void swap1_Loaded(object sender, RoutedEventArgs e)
        {
            System.Diagnostics.Debug.WriteLine("main loaded: " + ((SwapChainPanel)sender).CompositionScaleX);
        }

        private void swap1_Unloaded(object sender, RoutedEventArgs e)
        {
            System.Diagnostics.Debug.WriteLine("main unloaded: " + ((SwapChainPanel)sender).CompositionScaleX);
            
        }

        private void SKSwapChainPanel_Loaded(object sender, RoutedEventArgs e)
        {
            System.Diagnostics.Debug.WriteLine("main loaded: " + ((SwapChainPanel)sender).CompositionScaleX);
            System.Diagnostics.Debug.WriteLine("thread: " + System.Threading.Thread.CurrentThread.ManagedThreadId);
        }

        private void SKSwapChainPanel_Unloaded(object sender, RoutedEventArgs e)
        {
            System.Diagnostics.Debug.WriteLine("main unloaded: " + ((SwapChainPanel)sender).CompositionScaleX);
            System.Diagnostics.Debug.WriteLine("thread: " + System.Threading.Thread.CurrentThread.ManagedThreadId);
            //PageContent.Content = (new Page2());
            //Task.Delay(0).ContinueWith((t) =>
            //{
            //    Dispatcher.RunAsync(
            //        Windows.UI.Core.CoreDispatcherPriority.Normal,
            //        (DispatchedHandler)(() =>
            //        {
            //            System.Diagnostics.Debug.WriteLine("here: ");


            //        }));
            //});
        }

        private void SKSwapChainPanel_CompositionScaleChanged(SwapChainPanel sender, object args)
        {
            System.Diagnostics.Debug.WriteLine("main composition changed: " + sender.CompositionScaleX);
            System.Diagnostics.Debug.WriteLine("thread: " + System.Threading.Thread.CurrentThread.ManagedThreadId);
        }

        private bool normal = true;
        private void Button_Click_1(object sender, RoutedEventArgs e)
        {
            if (normal)
            {
                normal = !normal;
                grid.RenderTransform = new ScaleTransform() { ScaleX = 2, ScaleY = 2, CenterX = 0, CenterY = 0 } ;
            }
            else
            {
                normal = !normal;
                grid.RenderTransform = null;
            }
        }
    }
}
```

Page2.xaml:

```xml
<Page
    x:Class="SkiaBug.Page2"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:SkiaBug"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    xmlns:sk="using:SkiaSharp.Views.UWP"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}"
    >

    
    <Grid>
        <sk:SKSwapChainPanel Tag="TEST2" PaintSurface="SKSwapChainPanel_PaintSurface"
                             CompositionScaleChanged="SKSwapChainPanel_CompositionScaleChanged"
                             Loaded="SKSwapChainPanel_Loaded"
                             Unloaded="SKSwapChainPanel_Unloaded"
                             ></sk:SKSwapChainPanel>
        <!--<SwapChainPanel CompositionScaleChanged="SwapChainPanel_CompositionScaleChanged"
                        Loaded="SwapChainPanel_Loaded"
                        Unloaded="SwapChainPanel_Unloaded"></SwapChainPanel>-->
    </Grid>
</Page>
```

Page2.xaml.cs:

```cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices.WindowsRuntime;
using Windows.Foundation;
using Windows.Foundation.Collections;
using Windows.UI.Xaml;
using Windows.UI.Xaml.Controls;
using Windows.UI.Xaml.Controls.Primitives;
using Windows.UI.Xaml.Data;
using Windows.UI.Xaml.Input;
using Windows.UI.Xaml.Media;
using Windows.UI.Xaml.Navigation;

// The Blank Page item template is documented at https://go.microsoft.com/fwlink/?LinkId=234238

namespace SkiaBug
{
    /// <summary>
    /// An empty page that can be used on its own or navigated to within a Frame.
    /// </summary>
    public sealed partial class Page2 : Page
    {
        public Page2()
        {
            this.InitializeComponent();
        }

        private void SKSwapChainPanel_PaintSurface(object sender, SkiaSharp.Views.UWP.SKPaintGLSurfaceEventArgs e)
        {
            e.Surface.Canvas.Clear(new SkiaSharp.SKColor(0, 255, 0));
        }

        private void SwapChainPanel_CompositionScaleChanged(SwapChainPanel sender, object args)
        {
            System.Diagnostics.Debug.WriteLine("page2 composition changed: " + sender.CompositionScaleX);
        }

        private void SwapChainPanel_Loaded(object sender, RoutedEventArgs e)
        {
            System.Diagnostics.Debug.WriteLine("page2 loaded: " + ((SwapChainPanel)sender).CompositionScaleX);
        }

        private void SwapChainPanel_Unloaded(object sender, RoutedEventArgs e)
        {
            System.Diagnostics.Debug.WriteLine("page2 unloaded: " + ((SwapChainPanel)sender).CompositionScaleX);
        }

        private void SKSwapChainPanel_CompositionScaleChanged(SwapChainPanel sender, object args)
        {
            System.Diagnostics.Debug.WriteLine("page2 composition changed: " + sender.CompositionScaleX);
            System.Diagnostics.Debug.WriteLine("thread: " + System.Threading.Thread.CurrentThread.ManagedThreadId);
        }

        private void SKSwapChainPanel_Loaded(object sender, RoutedEventArgs e)
        {
            System.Diagnostics.Debug.WriteLine("page2 loaded: " + ((SwapChainPanel)sender).CompositionScaleX);
            System.Diagnostics.Debug.WriteLine("thread: " + System.Threading.Thread.CurrentThread.ManagedThreadId);
        }

        private void SKSwapChainPanel_Unloaded(object sender, RoutedEventArgs e)
        {
            System.Diagnostics.Debug.WriteLine("page2 unloaded: " + ((SwapChainPanel)sender).CompositionScaleX);
            System.Diagnostics.Debug.WriteLine("thread: " + System.Threading.Thread.CurrentThread.ManagedThreadId);
        }
    }
}
```

You'll note that Frame.Navigate doesn't even seem necessary, I think it just exacerbated the timing elements, or perhaps resulted in more composition scale changes, or different timing of said.

**Comment by gmurray81** [comment]
to elaborate, if only applying the refcounting fix, you can still get an issue if you spam the button in the above sample, where sometimes it will stop being able to paint the surface. The AbandonContext(true => false)  appears to resolve that aspect of it.

**Comment by mgierlasinski** [comment]
@gmurray81 @mattleibow It also crashes in Xamarin.Forms 5.0.0.1931/SkiaSharp.Views.Forms 2.80.2, making impossible to use `SKGLView` on UWP :(

**Comment by gmurray81** [comment]
@mgierlasinski if you have the time and means, you could try building my PR branch #1642 and see if it resolves the issue for you.
I'm not certain if its doing the right cleanup as I haven't poked around much in the Skia internals yet, so may need some feedback from @mattleibow
