### ISSUE TITLE
[BUG] Unable to load DLL 'libSkiaSharp': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

### ISSUE THREAD

**Issue by K232** [mono/SkiaSharp#1869]
**Description**

I've added SkiaSharp to my vb asp.net (.net 4.6) project. As I ran into the "Strong Name Signature Problem" in 2.80.3, I've tried both 2.80.2 and 2.88.0 preview 155. Project compiles, but as soon as I do anything with SkiaSharp (in my case SKBitmap.Decode with local filename) I get this error message:

Unable to load DLL 'libSkiaSharp': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

In other reports i've seen that installing 2015 runtime fixed it. In my case it was already installed. I've additionally installed the 2015-2021 runtimes and restarted my machine, but problem still exists. In Bin-Folder I see SkiaSharp.dll but how could I get libSkiaSharp?

**Basic Information**

- Version with issue:  2.80.2 and 2.88.0 preview 155
- Last known good version:  ---
- IDE:  Visual Studio 2019
- Platform Target Frameworks: 
  - Windows Classic: Windows 10

<details>
  <summary>Detailed IDE/OS information (click to expand)</summary>
  
```

at SkiaSharp.SkiaApi.sk_filestream_new(Void* path)
   at SkiaSharp.SKFileStream.CreateNew(String path)
   at SkiaSharp.SKFileStream..ctor(String path)
   at SkiaSharp.SKFileStream.OpenStream(String path)
   at SkiaSharp.SKBitmap.Decode(String filename)

```
</details>

**Comment by K232** [comment]
I've fixed it now by manually copying libSkiaSharp.dll from \packages\SkiaSharp.2.80.2\runtimes\win-x64\native\ (or \packages\SkiaSharp.2.80.2\runtimes\win-x86\native\ of course) to the bin folder.
