### ISSUE TITLE
[BUG] .net interactive does not work out of the box on macOS

### ISSUE THREAD

**Issue by spouliot** [mono/SkiaSharp#1976]
**Description**

.net interactive does not work out of the box - at least on macOS

**Code**

```csharp
#r "nuget: SkiaSharp"
using SkiaSharp;

SKImageInfo info = new SKImageInfo(256, 256);
SKSurface surface = SKSurface.Create(info);
SKCanvas canvas = surface.Canvas;

canvas.Clear(SKColors.White);

// configure our brush
SKPaint redBrush = new SKPaint {
    Color = new SKColor(0xff, 0, 0),
    IsStroke = true
};
SKPaint blueBrush = new SKPaint {
    Color = new SKColor(0, 0, 0xff),
    IsStroke = true
};

for (int i = 0; i < 64; i += 8) {
    SKRect rect = new SKRect(i, i, 256 - i - 1, 256 - i - 1);
    canvas.DrawRect(rect, (i % 16 == 0) ? redBrush : blueBrush);
}

surface.Snapshot().Display();
```

**Expected Behavior**

An image

**Actual Behavior**

```
System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.

 ---> System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibSkiaSharp, 0x0001): tried: 'liblibSkiaSharp' (no such file), '/usr/local/lib/liblibSkiaSharp' (no such file), '/usr/lib/liblibSkiaSharp' (no such file), '/Users/poupou/git/aos/liblibSkiaSharp' (no such file), '/usr/local/lib/liblibSkiaSharp' (no such file), '/usr/lib/liblibSkiaSharp' (no such file)

   at SkiaSharp.SkiaApi.sk_colortype_get_default_8888()

   at SkiaSharp.SKImageInfo..cctor()

   --- End of inner exception stack trace ---

   at SkiaSharp.SKImageInfo..ctor(Int32 width, Int32 height)

   at Submission#3.<<Initialize>>d__0.MoveNext()

--- End of stack trace from previous location ---

   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
```

**Basic Information**

- Version with issue:  SkiaSharp, 2.80.3
- Last known good version:  unknown, never tried before
- IDE:  vscode
- Platform Target Frameworks: .net interactive on macOS 12.2.1
  
<details>
  <summary>Detailed IDE/OS information (click to expand)</summary>
  
```

VScode 
Version: 1.65.2 (Universal)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:49.188Z (6 days ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.3.0

.NET Interactive Notebooks v1.0.3103010

```
</details>

**Screenshots**

**Reproduction Link**

**Comment by spouliot** [comment]
I downloaded the latest nuget and copied the dylib to the local directory.

The exception is gone but it does not run (it hangs).

OTOH it seems that the native library is for `x86_64` only and I'm running this on an `arm64` Mac.

```
file /Users/poupou/Downloads/skiasharp.2.80.3.nupkg/runtimes/osx/native/libSkiaSharp.dylib
/Users/poupou/Downloads/skiasharp.2.80.3.nupkg/runtimes/osx/native/libSkiaSharp.dylib: Mach-O universal binary with 1 architecture: [x86_64:Mach-O 64-bit dynamically linked shared library x86_64]
/Users/poupou/Downloads/skiasharp.2.80.3.nupkg/runtimes/osx/native/libSkiaSharp.dylib (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
```

The build script in the repo seems to handle both architectures so I'm not sure if this is a packaging issue ?!?

**Comment by spouliot** [comment]
For some reasons I thought SkiaSharp for macOS and net5/6 was already out (and not still a prerelease). IOW works fine when using the prerelease nuget :)
