### ISSUE TITLE
Unable to load assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' through COM

### ISSUE THREAD

**Issue by vinodd30** [mono/SkiaSharp#1990]
**Description**
I am trying to use SkiaSharp through Codecrete.SwissQRBill.Generator package.
But when I am accessing this dll through COM compoenent I am getting errors as below:

System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'PerTypeValues`1' threw an exception.
  Source=System.Memory
  StackTrace:
   at System.SpanHelpers.IsReferenceOrContainsReferences[T]()
   at SkiaSharp.SKString.ToString()
   at SkiaSharp.SKTypeface.get_FamilyName()
   at Codecrete.SwissQRBill.PixelCanvas.PNGCanvas.FindInstalledFontFamily(String fontFamilyList) in /_/PixelCanvas/Canvas/PNGCanvas.cs:line 110
   at Codecrete.SwissQRBill.PixelCanvas.PNGCanvas..ctor(Double width, Double height, Int32 resolution, String fontFamilyList) in /_/PixelCanvas/Canvas/PNGCanvas.cs:line 57
   at Codecrete.SwissQRBill.PixelCanvas.PNGCanvasFactory.Codecrete.SwissQRBill.Generator.Canvas.ICanvasFactory.Create(BillFormat format, Double width, Double height) in /_/PixelCanvas/Canvas/PNGCanvasFactory.cs:line 25
   at Codecrete.SwissQRBill.Generator.Canvas.CanvasCreator.Create(BillFormat format, Double width, Double height) in /_/Core/Canvas/CanvasCreator.cs:line 50
   at Codecrete.SwissQRBill.Generator.QRBill.CreateCanvas(BillFormat format) in /_/Core/QRBill.cs:line 309
   at Codecrete.SwissQRBill.Generator.QRBill.Generate(Bill bill) in /_/Core/QRBill.cs:line 132
   at Util.QRCodeGenerator.QRCodeGen.GenerateQRCode(String input) in C:\Nova\NovaProd\Source\DEV\4_Kailash_Scrum\Jd\Src\Util\QRCodeGen.cs:line 96

Inner Exception 1:
FileLoadException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.6.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Inner Exception 2:
FileLoadException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

So can you please help me to resolve this issue?

Regards,
Vinod

**Comment by Magenta94** [comment]
Same problem here

**Comment by veprim** [comment]
Have you fixed that anynone ?

**Comment by OlliC** [comment]
A few years later i came across the same problem. 
When running through COM it appears Skiasharp looks for a specific version of System.Runtime.CompilerServices.Unsafe.dll, 
namely AssemblyVersion 4.0.4.1 (Which is Package Version 4.5.3). Although we are at Package Version 6.0.0 every else. 

So i downloaded the package with that version from: https://www.nuget.org/packages/System.Runtime.CompilerServices.Unsafe/4.5.3
renamed it to zip and extracted the dll to a different folder.
On the particular machine where the issue occured i installed Windows SDK to get the GacUtil.
Then simply register the dll with "gacutil.exe /i" and the issue disappeard.

Maybe this helps someone until the issue is fixed.
