### ISSUE TITLE
[BUG] Tizen build fails

### ISSUE THREAD

**Issue by mgood7123** [mono/SkiaSharp#2023]
```
========================================
externals-tizen
========================================
The assembly 'Cake.FileHelpers, Version=3.2.1.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.33.0).
For best compatibility it should target Cake.Core version 2.0.0.
Arguments:
    target                         Default

========================================
git-sync-deps
========================================
Skipping "../src".
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\buildtools              @ 505de88083136eefd056e5ee4ca0f01fe9b33de8
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\common                  @ 9737551d7a52c3db3262db5856e6bcd62c462b92
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ 169895d529dfce00390a20e69c2f516066fe7a3b
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ c8d0c9b1d16bfda56f15165d39e0ffa360a11123
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ 47b3db22be33213eea4ad58f2453ee1088324ceb
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ e61745a6b7add50d380cfd7d3883dd6c62fc2c71
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ 40c5681ab92e7db1298273ccf3c816e6a1498260
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ a0bca08de07c7d7651047bedc0b653cfaaa4f2ae
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ f3c829047220ec1305c6a3202ee3e067e10512c9
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ e976867fb57a0cd87e3b0fe05d59e0ed63c6febb
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ 9418dcb69355558f70de260483424412c5ca2fce
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ 63e15eac4f443fa53565d1e4fb9611cdd7814f28
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ d06d2a6d42baf6c0c91cacc28df2542a911d05fe
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ 4dcc12d1a441b29d5901bc708bb1343d29d6459f
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ a82a4944a7f2496639f34a89c9923be5908b80aa
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ dbd3825b31041d782c5b504c59dcfb5ac7dda08c
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ 64fc43d52351ed52143208ce6a656c03db56462b
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ e354c6355e7f48e087678ec49e340ca0696725b1
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ 55a080e50af655d1fbe0a5c22954835cdd59ff92
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ 386707c6d19b974ca2e3db7f5c61873813c6fe44
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ 748945ec6f1c67b7efc934ab0808e1d32f2fb98d
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ 0944e71f4b2cb9a871bcbe353f95e889b64a611a
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ 4e6d30e406d2e5a65e1d65e404fe6df5f772a32b
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ 14b80ebeab022b2c78f84a573f01028c96075553
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ 932ed55c85f887041291cef8019e54280c033c35
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ b02a12d1dd821118763debec6b83d00a8a0ee419
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ bb217acdca1cc0c16b704669dd6f91a1b509c406
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ c0df742ec0b8178ad58c68cff3437ad4b6a06e26
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ b55ff303ea2f9e26702b514cf6a3196a2e3e2974
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ 011139094ec790ff7f32ea2d80286255fc9ed18b
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ bdbef7b1f3982fe99a62d076043036abe6dd6d80
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ 5d7cfcca344034aff9327f77fc181ae3754e7a90
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ 00cc8a50aa0c86b6bcb37e9ece8fb100047cc17b
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ e95fbfb1f509ad7a7fdfb72ac35fe412d72fc4a4
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ 019feda602ec90e99c448256e1ce11f6fdb622e8
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ eaf99a4e2009b0e5759e6070ad1760ac1dd75461

========================================
libSkiaSharp
========================================
Done. Made 89 targets from 43 files in 2775ms
ninja: Entering directory `out/tizen/armel'
[3/1091] compile ../../../src/ports/SkFontConfigInterface.cpp
FAILED: obj/src/ports/fontmgr_FontConfigInterface.SkFontConfigInterface.o
C:/Users/small/tizen-studio/tools/llvm-10/bin/clang++.exe -MD -MF obj/src/ports/fontmgr_FontConfigInterface.SkFontConfigInterface.o.d -DSK_BUILD_FOR_TIZEN -DNDEBUG -DSK_R32_SHIFT=16 -DSK_GAMMA_APPLY_TO_A8 -DGR_OP_ALLOCATE_USE_NEW -DSKIA_IMPLEMENTATION=1 -I../../.. -Wno-attributes -fPIC -fstrict-aliasing -fvisibility=hidden -march=armv7-a -mfpu=neon -mthumb --sysroot=C:/Users/small/tizen-studio/platforms/tizen-4.0/mobile/rootstraps/mobile-4.0-device.core --target=arm-tizen-linux-gnueabi -BC:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/bin -O3 -fdata-sections -ffunction-sections -Wno-sign-conversion -Wno-unused-parameter -DSKIA_C_DLL -DXML_DEV_URANDOM -DSK_NO_MAKE_SHARED_PTR -std=c++17 -fvisibility-inlines-hidden -isystemC:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/include/c++/9.2.0 -isystemC:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/include/c++/9.2.0/arm-tizen-linux-gnueabi -fno-exceptions -fno-rtti -c ../../../src/ports/SkFontConfigInterface.cpp -o obj/src/ports/fontmgr_FontConfigInterface.SkFontConfigInterface.o
In file included from ../../../src/ports/SkFontConfigInterface.cpp:8:
In file included from ../../..\include/core/SkFontMgr.h:11:
In file included from ../../..\include/core/SkFontArguments.h:11:
In file included from ../../..\include/core/SkScalar.h:11:
In file included from ../../..\include/private/SkFloatingPoint.h:11:
In file included from ../../..\include/core/SkTypes.h:618:
In file included from C:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/include/c++/9.2.0\memory:62:
In file included from C:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/include/c++/9.2.0\bits/stl_algobase.h:59:
In file included from C:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/include/c++/9.2.0/arm-tizen-linux-gnueabi\bits/c++config.h:524:
C:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/include/c++/9.2.0/arm-tizen-linux-gnueabi\bits/os_defines.h:39:10: fatal error: 'features.h' file not found
#include <features.h>
         ^~~~~~~~~~~~
1 error generated.
[4/1091] compile ../../../src/ports/SkFontConfigInterface_direct.cpp
FAILED: obj/src/ports/fontmgr_FontConfigInterface.SkFontConfigInterface_direct.o
C:/Users/small/tizen-studio/tools/llvm-10/bin/clang++.exe -MD -MF obj/src/ports/fontmgr_FontConfigInterface.SkFontConfigInterface_direct.o.d -DSK_BUILD_FOR_TIZEN -DNDEBUG -DSK_R32_SHIFT=16 -DSK_GAMMA_APPLY_TO_A8 -DGR_OP_ALLOCATE_USE_NEW -DSKIA_IMPLEMENTATION=1 -I../../.. -Wno-attributes -fPIC -fstrict-aliasing -fvisibility=hidden -march=armv7-a -mfpu=neon -mthumb --sysroot=C:/Users/small/tizen-studio/platforms/tizen-4.0/mobile/rootstraps/mobile-4.0-device.core --target=arm-tizen-linux-gnueabi -BC:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/bin -O3 -fdata-sections -ffunction-sections -Wno-sign-conversion -Wno-unused-parameter -DSKIA_C_DLL -DXML_DEV_URANDOM -DSK_NO_MAKE_SHARED_PTR -std=c++17 -fvisibility-inlines-hidden -isystemC:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/include/c++/9.2.0 -isystemC:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/include/c++/9.2.0/arm-tizen-linux-gnueabi -fno-exceptions -fno-rtti -c ../../../src/ports/SkFontConfigInterface_direct.cpp -o obj/src/ports/fontmgr_FontConfigInterface.SkFontConfigInterface_direct.o
In file included from ../../../src/ports/SkFontConfigInterface_direct.cpp:10:
In file included from ../../..\include/core/SkFontStyle.h:11:
In file included from ../../..\include/core/SkTypes.h:618:
In file included from C:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/include/c++/9.2.0\memory:62:
In file included from C:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/include/c++/9.2.0\bits/stl_algobase.h:59:
In file included from C:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/include/c++/9.2.0/arm-tizen-linux-gnueabi\bits/c++config.h:524:
C:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/include/c++/9.2.0/arm-tizen-linux-gnueabi\bits/os_defines.h:39:10: fatal error: 'features.h' file not found
#include <features.h>
         ^~~~~~~~~~~~
1 error generated.
[5/1091] compile ../../../src/gpu/glsl/GrGLSL.cpp
FAILED: obj/src/gpu/glsl/gpu.GrGLSL.o
C:/Users/small/tizen-studio/tools/llvm-10/bin/clang++.exe -MD -MF obj/src/gpu/glsl/gpu.GrGLSL.o.d -DSK_BUILD_FOR_TIZEN -DNDEBUG -DSK_R32_SHIFT=16 -DSK_GAMMA_APPLY_TO_A8 -DGR_OP_ALLOCATE_USE_NEW -DSKIA_IMPLEMENTATION=1 -DSK_GL -I../../.. -Wno-attributes -fPIC -fstrict-aliasing -fvisibility=hidden -march=armv7-a -mfpu=neon -mthumb --sysroot=C:/Users/small/tizen-studio/platforms/tizen-4.0/mobile/rootstraps/mobile-4.0-device.core --target=arm-tizen-linux-gnueabi -BC:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/bin -O3 -fdata-sections -ffunction-sections -Wno-sign-conversion -Wno-unused-parameter -DSKIA_C_DLL -DXML_DEV_URANDOM -DSK_NO_MAKE_SHARED_PTR -std=c++17 -fvisibility-inlines-hidden -isystemC:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/include/c++/9.2.0 -isystemC:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/include/c++/9.2.0/arm-tizen-linux-gnueabi -fno-exceptions -fno-rtti -c ../../../src/gpu/glsl/GrGLSL.cpp -o obj/src/gpu/glsl/gpu.GrGLSL.o
In file included from ../../../src/gpu/glsl/GrGLSL.cpp:8:
In file included from ../../..\src/gpu/GrShaderCaps.h:11:
In file included from ../../..\include/core/SkRefCnt.h:11:
In file included from ../../..\include/core/SkTypes.h:618:
In file included from C:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/include/c++/9.2.0\memory:62:
In file included from C:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/include/c++/9.2.0\bits/stl_algobase.h:59:
In file included from C:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/include/c++/9.2.0/arm-tizen-linux-gnueabi\bits/c++config.h:524:
C:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/include/c++/9.2.0/arm-tizen-linux-gnueabi\bits/os_defines.h:39:10: fatal error: 'features.h' file not found
#include <features.h>
         ^~~~~~~~~~~~
1 error generated.
[6/1091] compile ../../../src/gpu/glsl/GrGLSLFragmentProcessor.cpp
FAILED: obj/src/gpu/glsl/gpu.GrGLSLFragmentProcessor.o
C:/Users/small/tizen-studio/tools/llvm-10/bin/clang++.exe -MD -MF obj/src/gpu/glsl/gpu.GrGLSLFragmentProcessor.o.d -DSK_BUILD_FOR_TIZEN -DNDEBUG -DSK_R32_SHIFT=16 -DSK_GAMMA_APPLY_TO_A8 -DGR_OP_ALLOCATE_USE_NEW -DSKIA_IMPLEMENTATION=1 -DSK_GL -I../../.. -Wno-attributes -fPIC -fstrict-aliasing -fvisibility=hidden -march=armv7-a -mfpu=neon -mthumb --sysroot=C:/Users/small/tizen-studio/platforms/tizen-4.0/mobile/rootstraps/mobile-4.0-device.core --target=arm-tizen-linux-gnueabi -BC:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/bin -O3 -fdata-sections -ffunction-sections -Wno-sign-conversion -Wno-unused-parameter -DSKIA_C_DLL -DXML_DEV_URANDOM -DSK_NO_MAKE_SHARED_PTR -std=c++17 -fvisibility-inlines-hidden -isystemC:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/include/c++/9.2.0 -isystemC:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/include/c++/9.2.0/arm-tizen-linux-gnueabi -fno-exceptions -fno-rtti -c ../../../src/gpu/glsl/GrGLSLFragmentProcessor.cpp -o obj/src/gpu/glsl/gpu.GrGLSLFragmentProcessor.o
In file included from ../../../src/gpu/glsl/GrGLSLFragmentProcessor.cpp:8:
In file included from ../../..\src/gpu/GrFragmentProcessor.h:11:
In file included from C:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/include/c++/9.2.0\tuple:38:
In file included from C:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/include/c++/9.2.0\utility:68:
In file included from C:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/include/c++/9.2.0/arm-tizen-linux-gnueabi\bits/c++config.h:524:
C:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/include/c++/9.2.0/arm-tizen-linux-gnueabi\bits/os_defines.h:39:10: fatal error: 'features.h' file not found
#include <features.h>
         ^~~~~~~~~~~~
1 error generated.
[7/1091] compile ../../../src/gpu/glsl/GrGLSLBlend.cpp
FAILED: obj/src/gpu/glsl/gpu.GrGLSLBlend.o
C:/Users/small/tizen-studio/tools/llvm-10/bin/clang++.exe -MD -MF obj/src/gpu/glsl/gpu.GrGLSLBlend.o.d -DSK_BUILD_FOR_TIZEN -DNDEBUG -DSK_R32_SHIFT=16 -DSK_GAMMA_APPLY_TO_A8 -DGR_OP_ALLOCATE_USE_NEW -DSKIA_IMPLEMENTATION=1 -DSK_GL -I../../.. -Wno-attributes -fPIC -fstrict-aliasing -fvisibility=hidden -march=armv7-a -mfpu=neon -mthumb --sysroot=C:/Users/small/tizen-studio/platforms/tizen-4.0/mobile/rootstraps/mobile-4.0-device.core --target=arm-tizen-linux-gnueabi -BC:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/bin -O3 -fdata-sections -ffunction-sections -Wno-sign-conversion -Wno-unused-parameter -DSKIA_C_DLL -DXML_DEV_URANDOM -DSK_NO_MAKE_SHARED_PTR -std=c++17 -fvisibility-inlines-hidden -isystemC:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/include/c++/9.2.0 -isystemC:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/include/c++/9.2.0/arm-tizen-linux-gnueabi -fno-exceptions -fno-rtti -c ../../../src/gpu/glsl/GrGLSLBlend.cpp -o obj/src/gpu/glsl/gpu.GrGLSLBlend.o
In file included from ../../../src/gpu/glsl/GrGLSLBlend.cpp:8:
In file included from ../../..\src/gpu/glsl/GrGLSLBlend.h:11:
In file included from ../../..\include/core/SkBlendMode.h:11:
In file included from ../../..\include/core/SkTypes.h:618:
In file included from C:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/include/c++/9.2.0\memory:62:
In file included from C:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/include/c++/9.2.0\bits/stl_algobase.h:59:
In file included from C:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/include/c++/9.2.0/arm-tizen-linux-gnueabi\bits/c++config.h:524:
C:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/include/c++/9.2.0/arm-tizen-linux-gnueabi\bits/os_defines.h:39:10: fatal error: 'features.h' file not found
#include <features.h>
         ^~~~~~~~~~~~
1 error generated.
[8/1091] compile ../../../src/gpu/text/GrTextBlob.cpp
FAILED: obj/src/gpu/text/gpu.GrTextBlob.o
C:/Users/small/tizen-studio/tools/llvm-10/bin/clang++.exe -MD -MF obj/src/gpu/text/gpu.GrTextBlob.o.d -DSK_BUILD_FOR_TIZEN -DNDEBUG -DSK_R32_SHIFT=16 -DSK_GAMMA_APPLY_TO_A8 -DGR_OP_ALLOCATE_USE_NEW -DSKIA_IMPLEMENTATION=1 -DSK_GL -I../../.. -Wno-attributes -fPIC -fstrict-aliasing -fvisibility=hidden -march=armv7-a -mfpu=neon -mthumb --sysroot=C:/Users/small/tizen-studio/platforms/tizen-4.0/mobile/rootstraps/mobile-4.0-device.core --target=arm-tizen-linux-gnueabi -BC:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/bin -O3 -fdata-sections -ffunction-sections -Wno-sign-conversion -Wno-unused-parameter -DSKIA_C_DLL -DXML_DEV_URANDOM -DSK_NO_MAKE_SHARED_PTR -std=c++17 -fvisibility-inlines-hidden -isystemC:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/include/c++/9.2.0 -isystemC:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/include/c++/9.2.0/arm-tizen-linux-gnueabi -fno-exceptions -fno-rtti -c ../../../src/gpu/text/GrTextBlob.cpp -o obj/src/gpu/text/gpu.GrTextBlob.o
In file included from ../../../src/gpu/text/GrTextBlob.cpp:8:
In file included from ../../..\include/core/SkColorFilter.h:11:
In file included from ../../..\include/core/SkBlendMode.h:11:
In file included from ../../..\include/core/SkTypes.h:618:
In file included from C:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/include/c++/9.2.0\memory:62:
In file included from C:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/include/c++/9.2.0\bits/stl_algobase.h:59:
In file included from C:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/include/c++/9.2.0/arm-tizen-linux-gnueabi\bits/c++config.h:524:
C:/Users/small/tizen-studio/tools/arm-linux-gnueabi-gcc-9.2/arm-tizen-linux-gnueabi/include/c++/9.2.0/arm-tizen-linux-gnueabi\bits/os_defines.h:39:10: fatal error: 'features.h' file not found
#include <features.h>
         ^~~~~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.
An error occurred when executing task 'libSkiaSharp'.
Error: One or more errors occurred. (Process 'C:/Users/small/source/repos/AndroidUI-SkiaSharp/externals/depot_tools/ninja.exe' failed with error: 1)
        Process 'C:/Users/small/source/repos/AndroidUI-SkiaSharp/externals/depot_tools/ninja.exe' failed with error: 1
An error occurred when executing task 'externals-tizen'.
Error: One or more errors occurred. (.NET CLI: Process returned an error (exit code 1).)
        .NET CLI: Process returned an error (exit code 1).
PS C:\Users\small\source\repos\AndroidUI-SkiaSharp>
```

Tizen Studio is installed to `C:\Users\small\tizen-studio`

Tizen Studio data is installed to `C:\Users\small\tizen-studio-data`

for mobile i have these packages installed

![image](https://user-images.githubusercontent.com/26642847/167282390-109d95f9-0356-43fa-a884-97657c87fbd0.png)

for wearable i have these packages installed

![image](https://user-images.githubusercontent.com/26642847/167282395-31a1289c-5f68-44a3-8e32-dadba65c9bbc.png)

for Tizen SDK Tools i have these packages installed

![image](https://user-images.githubusercontent.com/26642847/167282414-98eb31d4-38f4-46b7-a82f-212ed805544d.png)

![image](https://user-images.githubusercontent.com/26642847/167282418-5bbc74b8-cf83-4c16-8c99-ebe54e412b7a.png)

**Comment by mgood7123** [comment]
ok, so i had to install these

![image](https://user-images.githubusercontent.com/26642847/167285242-550ef3f6-007e-4a74-963f-f99ec6106977.png)

**Comment by mgood7123** [comment]
tho i now i get this

```
========================================
libSkiaSharp
========================================
Done. Made 89 targets from 43 files in 2014ms
ninja: Entering directory `out/tizen/armel'
[1089/1089] link libskia.a
Exception in thread "main" java.lang.NoClassDefFoundError: org/tizen/sbilib/for_cli/sbiplugin/SBIPluginManager
        at org.tizen.ncli.subcommands.build.buildnative.BuildNativeCLICommand.call(BuildNativeCLICommand.java:168)
        at org.tizen.ncli.subcommands.build.buildnative.BuildNativeCLICommand.call(BuildNativeCLICommand.java:44)
        at org.tizen.ncli.subcommands.AbstractSubCommand.runCommand(AbstractSubCommand.java:76)
        at org.tizen.ncli.ide.shell.BuildNativeCLI.execute(BuildNativeCLI.java:107)
        at org.tizen.ncli.ide.shell.AbstractCLI.execute(AbstractCLI.java:91)
        at org.tizen.ncli.ide.shell.Main.run(Main.java:189)
        at org.tizen.ncli.ide.shell.Main.main(Main.java:122)
Caused by: java.lang.ClassNotFoundException: org.tizen.sbilib.for_cli.sbiplugin.SBIPluginManager
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
        ... 7 more
An error occurred when executing task 'libSkiaSharp'.
Error: One or more errors occurred. (Process 'C:/Users/small/tizen-studio/tools/ide/bin/tizen.bat' failed with error: 1)
        Process 'C:/Users/small/tizen-studio/tools/ide/bin/tizen.bat' failed with error: 1
An error occurred when executing task 'externals-tizen'.
Error: One or more errors occurred. (.NET CLI: Process returned an error (exit code 1).)
        .NET CLI: Process returned an error (exit code 1).
        ```
