### ISSUE TITLE
[BUG] Tizen build fails - java.lang.ClassNotFoundException: org.tizen.sbilib.for_cli.sbiplugin.SBIPluginManager

### ISSUE THREAD

**Issue by mgood7123** [mono/SkiaSharp#2024]
```
========================================
externals-tizen
========================================
The assembly 'Cake.FileHelpers, Version=3.2.1.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.33.0).
For best compatibility it should target Cake.Core version 2.0.0.
Arguments:
    target                         Default

========================================
git-sync-deps
========================================
Skipping "../src".
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ 169895d529dfce00390a20e69c2f516066fe7a3b
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\common                  @ 9737551d7a52c3db3262db5856e6bcd62c462b92
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ e61745a6b7add50d380cfd7d3883dd6c62fc2c71
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ f3c829047220ec1305c6a3202ee3e067e10512c9
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\buildtools              @ 505de88083136eefd056e5ee4ca0f01fe9b33de8
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ 47b3db22be33213eea4ad58f2453ee1088324ceb
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ c8d0c9b1d16bfda56f15165d39e0ffa360a11123
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ 9418dcb69355558f70de260483424412c5ca2fce
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ a0bca08de07c7d7651047bedc0b653cfaaa4f2ae
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ 40c5681ab92e7db1298273ccf3c816e6a1498260
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ e976867fb57a0cd87e3b0fe05d59e0ed63c6febb
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ 4dcc12d1a441b29d5901bc708bb1343d29d6459f
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ 63e15eac4f443fa53565d1e4fb9611cdd7814f28
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ a82a4944a7f2496639f34a89c9923be5908b80aa
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ 55a080e50af655d1fbe0a5c22954835cdd59ff92
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ 0944e71f4b2cb9a871bcbe353f95e889b64a611a
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ 386707c6d19b974ca2e3db7f5c61873813c6fe44
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ e354c6355e7f48e087678ec49e340ca0696725b1
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ dbd3825b31041d782c5b504c59dcfb5ac7dda08c
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ 64fc43d52351ed52143208ce6a656c03db56462b
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ 748945ec6f1c67b7efc934ab0808e1d32f2fb98d
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ d06d2a6d42baf6c0c91cacc28df2542a911d05fe
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ 4e6d30e406d2e5a65e1d65e404fe6df5f772a32b
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ 932ed55c85f887041291cef8019e54280c033c35
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ b02a12d1dd821118763debec6b83d00a8a0ee419
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ bb217acdca1cc0c16b704669dd6f91a1b509c406
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ b55ff303ea2f9e26702b514cf6a3196a2e3e2974
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ 011139094ec790ff7f32ea2d80286255fc9ed18b
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ 5d7cfcca344034aff9327f77fc181ae3754e7a90
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ c0df742ec0b8178ad58c68cff3437ad4b6a06e26
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ bdbef7b1f3982fe99a62d076043036abe6dd6d80
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ 14b80ebeab022b2c78f84a573f01028c96075553
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ 00cc8a50aa0c86b6bcb37e9ece8fb100047cc17b
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ e95fbfb1f509ad7a7fdfb72ac35fe412d72fc4a4
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ eaf99a4e2009b0e5759e6070ad1760ac1dd75461
C:\Users\small\source\repos\AndroidUI-SkiaSharp\externals\skia\third_party/external... @ 019feda602ec90e99c448256e1ce11f6fdb622e8

========================================
libSkiaSharp
========================================
Done. Made 89 targets from 43 files in 1934ms
ninja: Entering directory `out/tizen/armel'
ninja: no work to do.
Exception in thread "main" java.lang.NoClassDefFoundError: org/tizen/sbilib/for_cli/sbiplugin/SBIPluginManager
        at org.tizen.ncli.subcommands.build.buildnative.BuildNativeCLICommand.call(BuildNativeCLICommand.java:168)
        at org.tizen.ncli.subcommands.build.buildnative.BuildNativeCLICommand.call(BuildNativeCLICommand.java:44)
        at org.tizen.ncli.subcommands.AbstractSubCommand.runCommand(AbstractSubCommand.java:76)
        at org.tizen.ncli.ide.shell.BuildNativeCLI.execute(BuildNativeCLI.java:107)
        at org.tizen.ncli.ide.shell.AbstractCLI.execute(AbstractCLI.java:91)
        at org.tizen.ncli.ide.shell.Main.run(Main.java:189)
        at org.tizen.ncli.ide.shell.Main.main(Main.java:122)
Caused by: java.lang.ClassNotFoundException: org.tizen.sbilib.for_cli.sbiplugin.SBIPluginManager
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
        ... 7 more
An error occurred when executing task 'libSkiaSharp'.
Error: One or more errors occurred. (Process 'C:/Users/small/tizen-studio/tools/ide/bin/tizen.bat' failed with error: 1)
        Process 'C:/Users/small/tizen-studio/tools/ide/bin/tizen.bat' failed with error: 1
An error occurred when executing task 'externals-tizen'.
Error: One or more errors occurred. (.NET CLI: Process returned an error (exit code 1).)
        .NET CLI: Process returned an error (exit code 1).
```

**Comment by mgood7123** [comment]
welp i managed to get around it somehow by installing these

![image](https://user-images.githubusercontent.com/26642847/167289657-cd2a01a1-a266-427b-82ae-7e2ff7c3f3a9.png)

but now i get

```
========================================
libSkiaSharp
========================================
Done. Made 89 targets from 43 files in 2205ms
ninja: Entering directory `out/tizen/armel'
ninja: no work to do.
[PLATFORM] Mobile-4.0
[ARCHITECTURE] armel
[COMPILER] LLVM-4.0
[CONFIGURATION] Release
[SBI] prdefine options =
[SBI] command : cmd /c make.exe -f "C:\Users\small\tizen-studio\tools\ide\resources\native\Build\makefile" -r
make -f C:\Users\small\tizen-studio\tools\ide\resources\native\Build/makefile.mk
C:\Users\small\tizen-studio\tools\smart-build-interface\..\msys2\usr\bin\make[1]: Entering directory '/c/Users/small/source/repos/AndroidUI-SkiaSharp/native/tizen/libSkiaSharp'
preparing to build /c/Users/small/source/repos/AndroidUI-SkiaSharp/externals/skia/src/xamarin/SkiaKeeper.c
preparing to build /c/Users/small/source/repos/AndroidUI-SkiaSharp/externals/skia/src/xamarin/sk_xamarin.cpp
preparing to build /c/Users/small/source/repos/AndroidUI-SkiaSharp/externals/skia/src/xamarin/sk_compatpaint.cpp
preparing to build /c/Users/small/source/repos/AndroidUI-SkiaSharp/externals/skia/src/xamarin/SkCompatPaint.cpp
preparing to build /c/Users/small/source/repos/AndroidUI-SkiaSharp/externals/skia/src/xamarin/sk_managedstream.cpp
preparing to build /c/Users/small/source/repos/AndroidUI-SkiaSharp/externals/skia/src/xamarin/SkManagedStream.cpp
preparing to build /c/Users/small/source/repos/AndroidUI-SkiaSharp/externals/skia/src/xamarin/sk_manageddrawable.cpp
preparing to build /c/Users/small/source/repos/AndroidUI-SkiaSharp/externals/skia/src/xamarin/SkManagedDrawable.cpp
preparing to build /c/Users/small/source/repos/AndroidUI-SkiaSharp/externals/skia/src/xamarin/sk_managedtracememorydump.cpp
preparing to build /c/Users/small/source/repos/AndroidUI-SkiaSharp/externals/skia/src/xamarin/SkManagedTraceMemoryDump.cpp
C:\Users\small\tizen-studio\tools\ide\resources\native\Build/makefile.mk:160: warning: overriding recipe for target 'Release'
C:\Users\small\tizen-studio\tools\ide\resources\native\Build/makefile.mk:157: warning: ignoring old recipe for target 'Release'
  Building file: /c/Users/small/source/repos/AndroidUI-SkiaSharp/externals/skia/src/xamarin/SkiaKeeper.c
  Output Path ./Release
  Invoking: C Compiler
"C:\Users\small\tizen-studio\tools\smart-build-interface/../llvm-4.0.0/bin/clang.exe" -c "/c/Users/small/source/repos/AndroidUI-SkiaSharp/externals/skia/src/xamarin/SkiaKeeper.c" -o "Release//c/Users/small/source/repos/AndroidUI-SkiaSharp/externals/skia/src/xamarin/SkiaKeeper.o" -DTIZEN_DEPRECATION -DDEPRECATION_WARNING  -DNDEBUG -DGR_OP_ALLOCATE_USE_NEW -DSK_BUILD_FOR_TIZEN -DSK_CODEC_DECODES_JPEG -DSK_CODEC_DECODES_PNG -DSK_CODEC_DECODES_RAW -DSK_CODEC_DECODES_WEBP -DSK_ENCODE_JPEG -DSK_ENCODE_PNG -DSK_ENCODE_WEBP -DSK_GAMMA_APPLY_TO_A8 -DSK_GL -DSK_NO_MAKE_SHARED_PTR -DSK_R32_SHIFT=16 -DSK_SUPPORT_PDF -DSK_USE_LIBGIFCODEC -DSK_XML -DSKIA_C_DLL -DSKIA_IMPLEMENTATION=1 -DXML_DEV_URANDOM  -I/c/Users/small/source/repos/AndroidUI-SkiaSharp/externals/skia  -I"pch" -O3 -Wall -c -fmessage-length=0 -target arm-tizen-linux-gnueabi -gcc-toolchain "C:\Users\small\tizen-studio\tools\smart-build-interface/../arm-linux-gnueabi-gcc-6.2/" -ccc-gcc-name arm-linux-gnueabi-g++ -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -mtune=cortex-a8 -Wno-gnu  -fPIC --sysroot="C:/Users/small/tizen-studio/tools/smart-build-interface/../../platforms/tizen-4.0/mobile/rootstraps/mobile-4.0-device.core" -Werror-implicit-function-declaration  -fPIC -g -fno-exceptions -fstrict-aliasing -Wall -Wextra -Winit-self -Wpointer-arith -Wsign-compare -Wno-unused-parameter -Werror -Os -ffunction-sections -fdata-sections -fno-rtti -Wp,@./Release/objs/platform_incs_file.inc
  Finished building: /c/Users/small/source/repos/AndroidUI-SkiaSharp/externals/skia/src/xamarin/SkiaKeeper.c
  Building file: /c/Users/small/source/repos/AndroidUI-SkiaSharp/externals/skia/src/xamarin/sk_xamarin.cpp
  Output Path ./Release
  Invoking: C++ Compiler
"C:\Users\small\tizen-studio\tools\smart-build-interface/../llvm-4.0.0/bin/clang++.exe" -c "/c/Users/small/source/repos/AndroidUI-SkiaSharp/externals/skia/src/xamarin/sk_xamarin.cpp" -o "Release//c/Users/small/source/repos/AndroidUI-SkiaSharp/externals/skia/src/xamarin/sk_xamarin.o" -DTIZEN_DEPRECATION -DDEPRECATION_WARNING  -DNDEBUG -DGR_OP_ALLOCATE_USE_NEW -DSK_BUILD_FOR_TIZEN -DSK_CODEC_DECODES_JPEG -DSK_CODEC_DECODES_PNG -DSK_CODEC_DECODES_RAW -DSK_CODEC_DECODES_WEBP -DSK_ENCODE_JPEG -DSK_ENCODE_PNG -DSK_ENCODE_WEBP -DSK_GAMMA_APPLY_TO_A8 -DSK_GL -DSK_NO_MAKE_SHARED_PTR -DSK_R32_SHIFT=16 -DSK_SUPPORT_PDF -DSK_USE_LIBGIFCODEC -DSK_XML -DSKIA_C_DLL -DSKIA_IMPLEMENTATION=1 -DXML_DEV_URANDOM  -I/c/Users/small/source/repos/AndroidUI-SkiaSharp/externals/skia  -I"pch" -O3 -Wall -c -fmessage-length=0 -std=c++14 -target arm-tizen-linux-gnueabi -gcc-toolchain "C:\Users\small\tizen-studio\tools\smart-build-interface/../arm-linux-gnueabi-gcc-6.2/" -ccc-gcc-name arm-linux-gnueabi-g++ -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -mtune=cortex-a8 -Wno-gnu  -fPIC --sysroot="C:/Users/small/tizen-studio/tools/smart-build-interface/../../platforms/tizen-4.0/mobile/rootstraps/mobile-4.0-device.core" -Werror-implicit-function-declaration  -fPIC -g -fno-exceptions -fstrict-aliasing -Wall -Wextra -Winit-self -Wpointer-arith -Wsign-compare -Wno-unused-parameter -Werror -Os -ffunction-sections -fdata-sections -fno-rtti -std=c++17 -fno-threadsafe-statics -Wnon-virtual-dtor -Wp,@./Release/objs/platform_incs_file.inc
error: invalid value 'c++17' in '-std=c++17'
C:\Users\small\tizen-studio\tools\smart-build-interface\..\msys2\usr\bin\make[1]: *** [C:\Users\small\tizen-studio\tools\ide\resources\native\Build/makefile.mk:97: Release//c/Users/small/source/repos/AndroidUI-SkiaSharp/externals/skia/src/xamarin/sk_xamarin.o] Error 1
C:\Users\small\tizen-studio\tools\smart-build-interface\..\msys2\usr\bin\make[1]: Leaving directory '/c/Users/small/source/repos/AndroidUI-SkiaSharp/native/tizen/libSkiaSharp'
make: *** [C:\Users\small\tizen-studio\tools\ide\resources\native\Build\makefile:27: app_build] Error 2
Total time: 00:00:08.289
An error occurred when executing task 'libSkiaSharp'.
Error: One or more errors occurred. (Process 'C:/Users/small/tizen-studio/tools/ide/bin/tizen.bat' failed with error: 1)
        Process 'C:/Users/small/tizen-studio/tools/ide/bin/tizen.bat' failed with error: 1
An error occurred when executing task 'externals-tizen'.
Error: One or more errors occurred. (.NET CLI: Process returned an error (exit code 1).)
        .NET CLI: Process returned an error (exit code 1).
```
```
