### ISSUE TITLE
Thread Safety in SKBitmap.Decode?

### ISSUE THREAD

**Issue by abezydar** [mono/SkiaSharp#209]
Hi! I'm using SkiaSharp for server side image generation and have run into an issue when Decoding many bitmaps at once on IIS. 

Here's the error: 
```
Application: w3wp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at SkiaSharp.SkiaApi.sk_codec_get_info(IntPtr, SkiaSharp.SKImageInfo ByRef)
   at SkiaSharp.SKBitmap.Decode(SkiaSharp.SKCodec)
   at SkiaSharp.SKBitmap.Decode(SkiaSharp.SKStream)
```

I'm not sure if this is because of memory constraints, because of thread safety or another reason I'm unaware of. 

The code I have is this:

```c#
public static async Task LoadBitmap(RenderContext context, ILayoutElementHasUri element, Action<SKBitmap> handleBitmapAction) {
    
    var uri = element.GetUriWithReplacements();

    var bytes = await new LoadImage(uri, context).Execute();

    // Limit the number of bitmaps decoding concurrently
    await decodeBitmapThrottler.WaitAsync();

    try
    {
        var bitmap = SKBitmap.Decode(bytes);
        handleBitmapAction(bitmap);
        if (bitmap != null)
        {
            bitmap.Dispose();
        }
        
    }
    finally
    {
        decodeBitmapThrottler.Release();
    }
}
```     

My workaround has been to add a SemaphoreSlim, `decodeBitmapThrottler`, with a max count of 1, which increases the stability but sacrifices speed. As soon as I increase the count, I start getting System.AccessViolationException errors. 

Any help or insight is appreciated! I also understand if this case is outside the goals of the project.

**Comment by mattleibow** [comment]
Hi @abezydar, thanks for giving SkiaSharp a go.

I am having a look at your code and I can't really see why threads would come into this. There is just the single `SKBitmap.Decode` operation. the `bytes` variable - is that a byte array or is it a stream (as appears by the stack trace). If it is a stream, is there a way to test and see if you load the stream into a byte array and see if the issue goes away? (this is not a fix, but just checking to see where the error is)

SkiaSharp is "thread safe" in the sense that you can have two threads loading a bitmap, but two threads shouldn't access the same object.

**Comment by abezydar** [comment]
Hey @mattleibow, no problem and thanks for the feedback. The `bytes` variable is a byte array. It's multithreaded since an API in IIS is used to call this method. In the load test, 20 clients are decoding images at the same time. So, my expectation is that IIS is using multiple threads in the same worker process to decode the images. 

Since the error is happening on the `SKBitmap.Decode` method, my thought was it couldn't handle decoding more than one byte array at a time reliably. If it should, then perhaps I'm running into a memory error? If that's the case, I can look into limiting access to `SKBitmap.Decode` by memory availability rather than concurrent processes.

**Comment by mattleibow** [comment]
I am going to re-investigate this. Here is another example of this issue: https://forums.xamarin.com/discussion/87687/usage-in-visual-studio-2015-unit-test-project

**Comment by mattleibow** [comment]
This is the code that fails:

```csharp

public class ImagingUnitTest
{
	public static void ImageScalingMultipleThreads()
	{
		const int numThreads = 100;
		const int mumIterationsPerThread = 1000;

		var referenceFile = @"/Users/matthew/Documents/baboon.jpg";

		var tasks = new List<Task>();

		for (int i = 0; i < numThreads; i++)
		{
			var task = Task.Run(() => ScaleAndSaveImagesToByteArray(mumIterationsPerThread, referenceFile));
			tasks.Add(task);
		}

		Task.WaitAll(tasks.ToArray());

		Console.WriteLine($"Test completed for {numThreads} tasks, {mumIterationsPerThread} each.");
	}

	private static void ScaleAndSaveImagesToByteArray(int iterationsPerThread, string referenceFile)
	{
		byte[] comparisonImage;

		comparisonImage = ComputeThumbnail(referenceFile);

		for (int i = 0; i < iterationsPerThread; i++)
		{
			var imageData = ComputeThumbnail(referenceFile);

			for (int idx = 0; idx < imageData.Length; idx++)
			{
				if (imageData[idx] != comparisonImage[idx])
					throw new Exception($"Unexpected scaled image content for {referenceFile}");
			}
		}
	}

	public static byte[] ComputeThumbnail(string fileName)
	{
		using (var ms = new MemoryStream())
		using (var bitmap = SKBitmap.Decode(fileName))
		using (var scaledBitmap = new SKBitmap(60, 40, bitmap.ColorType, bitmap.AlphaType))
		{
			SKBitmap.Resize(scaledBitmap, bitmap, SKBitmapResizeMethod.Hamming);

			using (var image = SKImage.FromBitmap(scaledBitmap))
			using (var data = image.Encode(SKImageEncodeFormat.Png, 80))
			{
				data.SaveTo(ms);

				return ms.ToArray();
			}
		}
	}
}
```

**Comment by mattleibow** [comment]
This is the code that fails:

```csharp

public class ImagingUnitTest
{
	public static void ImageScalingMultipleThreads()
	{
		const int numThreads = 100;
		const int mumIterationsPerThread = 1000;

		var referenceFile = @"/Users/matthew/Documents/baboon.jpg";

		var tasks = new List<Task>();

		for (int i = 0; i < numThreads; i++)
		{
			var task = Task.Run(() => ScaleAndSaveImagesToByteArray(mumIterationsPerThread, referenceFile));
			tasks.Add(task);
		}

		Task.WaitAll(tasks.ToArray());

		Console.WriteLine($"Test completed for {numThreads} tasks, {mumIterationsPerThread} each.");
	}

	private static void ScaleAndSaveImagesToByteArray(int iterationsPerThread, string referenceFile)
	{
		byte[] comparisonImage;

		comparisonImage = ComputeThumbnail(referenceFile);

		for (int i = 0; i < iterationsPerThread; i++)
		{
			var imageData = ComputeThumbnail(referenceFile);

			for (int idx = 0; idx < imageData.Length; idx++)
			{
				if (imageData[idx] != comparisonImage[idx])
					throw new Exception($"Unexpected scaled image content for {referenceFile}");
			}
		}
	}

	public static byte[] ComputeThumbnail(string fileName)
	{
		using (var ms = new MemoryStream())
		using (var bitmap = SKBitmap.Decode(fileName))
		using (var scaledBitmap = new SKBitmap(60, 40, bitmap.ColorType, bitmap.AlphaType))
		{
			SKBitmap.Resize(scaledBitmap, bitmap, SKBitmapResizeMethod.Hamming);

			using (var image = SKImage.FromBitmap(scaledBitmap))
			using (var data = image.Encode(SKImageEncodeFormat.Png, 80))
			{
				data.SaveTo(ms);

				return ms.ToArray();
			}
		}
	}
}
```

**Comment by groege** [comment]
Is there any workarount?

**Comment by mattleibow** [comment]
I am not sure what I did to fix this :) It may have been an issue with skia returning the same instance of the decoders, and me not handling those cases. I think the fix is that I now track each time skia gives me an instance, and make sure it is not in use before disposing.

**Comment by abezydar** [comment]
Cool, I'll check it out as soon as the release comes out! Thanks!

**Comment by ncthbrt** [comment]
@mattleibow any updates on this? I'm running into a similar problem in netcore in version 1.56.2
Code is in this repo: https://github.com/ncthbrt/skia-fsharp`

This is where the drawing call is made:
https://github.com/ncthbrt/skia-fsharp/blob/master/Drawing/Test.fs#L94

**Comment by mattleibow** [comment]
Moving to the next release so we can get the new skia out.

**Comment by tdoneal** [comment]
Hi, I'm having similar issues with 1.56.2.  I'm getting nondeterministic AccessViolationExceptions using Windows Forms.  Strangely, the problem occurs only in Release mode (maybe due to tighter memory packing?).  Anyway, I'm pretty sure I'm allocating my surface correctly:

using (var bitmap = new Bitmap(iw, ih, PixelFormat.Format32bppPArgb))
            {
                var data = bitmap.LockBits(new Rectangle(0, 0, iw, ih), ImageLockMode.WriteOnly, bitmap.PixelFormat);

                var surface = SKSurface.Create(iw, ih, SKColorType.Bgra8888, SKAlphaType.Premul, data.Scan0, iw * 4);
                var skcanvas = surface.Canvas;
                .... // canvas.draw(), etc

This was working very reliably for months while in Debug mode, but switching to Release mode caused it to start failing.  Is there a bug in Skia in handling the allocation, or am I missing something silly?  There's no other place in my code where I'm doing "low level" memory management so I don't really know how to go about fixing this.  I commented out the actual canvas.draw() calls but I'm still getting the AccessViolationExceptions. I can try to get a minimal reproducing test case if the above code is indeed correct.

**Comment by tdoneal** [comment]
Small correction: commenting out the actual canvas.draw() calls causes the exceptions to disappear.  Let me know if you have any debugging tips to try.

**Comment by tdoneal** [comment]
Update: apparently I wasn't disposing of the SKSurface properly.  I wasn't calling surface.Dispose() after calling bitmap.UnlockBits().  Adding the call to surface.Dispose() fixed the issue.  I'll leave the above comments here in case anyone else runs into the same thing.

**Comment by mattleibow** [comment]
Glad to hear that you got it to work.

I would say that the "best practice" is to wrap SkiaSharp types in a `using` statement. This will make sure that there are no memory leaks as well as all the memory is freed ASAP. One thing where this helps is with the bitmap types, the managed type has only a size of `IntPtr`, but the underlying data could be several megabytes.

**Comment by ncthbrt** [comment]
@mattleibow This is still an issue.
@tdoneal has a different problem

**Comment by ncthbrt** [comment]
@mattleibow this appears to be still an issue. I've managed to work around it for now by using thread locks however.

**Comment by samirchakour-crossover** [comment]
I am having the same issue on Android, on iOS its working fine.

`_blobBitmap = SKBitmap.Decode(filePath);`

After the call to SKBitmap.Decode the app crash with a memory violation issue.

Here is my project.json file on Android :

`
<package id="SkiaSharp" version="1.57.0" targetFramework="monoandroid71" />
<package id="SkiaSharp.Views" version="1.57.0" targetFramework="monoandroid71" />
<package id="SkiaSharp.Views.Forms" version="1.57.0" targetFramework="monoandroid71" />
`

**Comment by samirchakour-crossover** [comment]
I have done a couple of changes to my android configuration and the bug seems to be resolved for me :
1. Changed the targetFramework to 'monoandroid60' instead of 'monoandroid71'
2. Changed the link behaviour to "Don't Link"
3. Disabled the arm64 and x86_64 ABIs 

And SKBitmap.Decode is working now, I haven't investigated yet which of those changes have resolved the issue but will do that on the next few days.

Hope this will help others.

**Comment by ncthbrt** [comment]
I was thinking... Would it be possible that aspnet core is interfering with GC?

**Comment by irv** [comment]
I'm also hitting this (in dotnet core, running on .net 4.6.1)

it appears to pop here: https://github.com/mono/SkiaSharp/blob/1cc9af5adb5a9966361ac5a4138952694a5345d3/binding/Binding/SKImage.cs#L59

from the stacktrace:

at SkiaSharp.SkiaApi.sk_image_unref(IntPtr image)
  at SkiaSharp.SKImage.Dispose(Boolean disposing)
  at SkiaSharp.SKNativeObject.Dispose()

It looks like maybe Dispose() is being called twice?

**Comment by mattleibow** [comment]
This is something that we will be looking at in the future.

**Comment by kostebudinoski** [comment]
loading the stream into a byte array and the issue is gone. @mattleibow what could be the reason for it? 
would prefer using the stream I have.

**Comment by kostebudinoski** [comment]
Reverting SkiaSharp to version 2.80.2 (what we used before the upgrade to 2.88.5) and the issue is gone.

I believe you now have ample investigative materials.

**Comment by gktval** [comment]
I am seeing this on an Asp.Net core application, but only in IIS. During debug on my computer it seems to work fine. 

here is the error from the log:
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at SkiaSharp.SkiaApi.sk_pixmap_encode_image(IntPtr, IntPtr, SkiaSharp.SKEncodedImageFormat, Int32)
--------------------------------
   at SkiaSharp.SKPixmap.Encode(SkiaSharp.SKWStream, SkiaSharp.SKEncodedImageFormat, Int32)
   at SkiaSharp.SKPixmap.Encode(SkiaSharp.SKEncodedImageFormat, Int32)
   at SkiaSharp.SKBitmap.Encode(SkiaSharp.SKEncodedImageFormat, Int32)
   at ManualCloudClassifier.Classes.SatelliteImage.GetBase64String()
   at ManualCloudClassifier.Pages.Pages_Index+<ExecuteAsync>d__47.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[ManualCloudClassifier.Pages.Pages_Index+<ExecuteAsync>d__47, ManualCloudClassifier, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](<ExecuteAsync>d__47 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[ManualCloudClassifier.Pages.Pages_Index+<ExecuteAsync>d__47, ManualCloudClassifier, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](<ExecuteAsync>d__47 ByRef)
   at ManualCloudClassifier.Pages.Pages_Index.ExecuteAsync()
   ...
```

seems to be crashing on this line of code:
```
var skData = bmp.Encode(SKEncodedImageFormat.Png, 10);
```

**Comment by Proektsoftbg** [comment]
@gktval . It is not enough just to remove `GC.Collect()`

If you need to use the bmp object further (e.g. to 'Encode'), you should not immediately call `handle.Free()`.
The GC Handle must be released after the memory is no longer needed. Then, you can safely call `handle.Free()`, and definitely after `bmp.Encode()`. Otherwise, GC can "decide" meanwhile to collect the array behind the handle and will destroy your bitmap data. If you try to use this bitmap after that, you will get again "Attempted to read or write protected memory". 

Removing `GC.Collect()` just makes it to not happen each time. Now, it can happen rarely, but will cause your app to crash. You can catch it if you simulate heavy load on your app. This will trigger GC more often and there will be a greater chance to hit the small time span between freeing the handle and trying to use the bitmap. This is some of those nasty hidden bugs that can squeeze through your tests and cause troubles to your clients.

**Comment by kostebudinoski** [comment]
Taking into consideration the current vulnerability highlighted at https://security.snyk.io/vuln/SNYK-DOTNET-SKIASHARP-5922114, updating to the latest version becomes even more challenging. With one memory issue on one side and another vulnerability on the other, the task is compounded. @mattleibow , any insights you can provide would be greatly appreciated.
