### ISSUE TITLE
libHarfBuzzSharp.so symbols

### ISSUE THREAD

**Issue by TruckDynasty** [mono/SkiaSharp#2117]
Trying to build a libHarfBuzzSharp using the ninja build system.  I've had good success building libSkiaSharp (I still need to report a few bugs with the build script).  The platform is a raspberry pi 3b+ running the latest 64 bit raspberry pi os.

The exact commands I ran from the mono/skia directory were:

# run the gn build script generator:
./bin/gn gen 'out/linux/arm64' --args='is_official_build=true
skia_enable_tools=false
target_os="linux"
target_cpu="arm64"
skia_use_icu=true
skia_use_system_icu=true
skia_use_harfbuzz=true
skia_use_system_harfbuzz=true
skia_pdf_subset_harfbuzz=false
skia_use_sfntly=false
skia_use_piex=true
skia_use_system_expat=false
skia_use_system_freetype2=true
skia_use_system_libjpeg_turbo=true
skia_use_system_libpng=true
skia_use_system_libwebp=true
skia_use_system_zlib=true
skia_enable_gpu=true
extra_cflags=[ "-DSKIA_C_DLL", "-DHAVE_PTHREAD", "-DHB_EXTERN=extern", "-I/usr/local/lib/aarch64-linux-gnu/harfbuzz/include/", "-I/usr/include/freetype2/" ]'
--cflags='[ "-DSKIA_C_DLL", "-DHAVE_PTHREAD", "-DHB_EXTERN=extern", "-I/usr/local/lib/aarch64-linux-gnu/harfbuzz/include/", "-I/usr/include/freetype2/" ]'

# build libSkiaSharp (no issues here, the build and generated library are a success)
ninja 'SkiaSharp' -C '/out/linux/arm64'

# build libHarfBuzzSharp (builds fine, issues occur later...)
ninja 'HarfBuzzSharp' -C '/out/linux/arm64'

# copy the built libSkiaSharp.so and libHarfBuzzSharp.so files to the project that needs them (UVTools), then run
LD_DEBUG=libs dotnet UVTools.dll

# get a bunch of output text, then the issue occurs as:
..... libHarfBuzzSharp.so: error: symbol lookup error: undefined symbol: hb_face_create_for_tables (fatal)

# running 'readelf -Ws --dyn-syms libHarfBuzzSharp.so' gives a *very* short list of symbols, none of which seem to have anything to do with harfbuzz
  _ITM_deregisterTMCloneTable
 __cxa_finalize@GLIBC_2.17 (2)
 __gmon_start__
 __getauxval@GLIBC_2.17 (2)
  _ITM_registerTMCloneTable

# I've also built SkiaSharp and HarfBuzzSharp using almost all of the third_party options (non skia_use_system_... build), and get the same result.  (I've probably built the pair 10 times in the last couple of weeks, each time trying something slightly different).

At this point one thing is obvious: I'm doing something wrong.  Any chance anyone can help me out?

**Comment by TruckDynasty** [comment]
got it compiled today, had to edit more build scripts: removed -fvisibility=hidden from cflags and -fvisibility-inlines-hidden from cflags_cc, then added -shared and -rdynamic to ldflags

the symbols all show up, but the source built libHarfBuzzSharp gives me the same issues as the nuget libHarfBuzzSharp: it seg faults as soon as it loads

I think I'm going to throw in the bandana until arm64 platforms are better supported by dotnet and others, but I appreciate everyone's hard work!  new architectures are never fun for anyone

**Comment by TruckDynasty** [comment]
Revisiting:
run 'gdb dotnet' to start dotnet
then 'run /opt/UVtools-3.4.3/UVtools.WPF/bin/Debug/net6.0/UVtools.dll' to load up the compiled dotnet project
... bunch of output as threads spawn ...
Thread 1 "dotnet" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
/#0  0x0000000000000000 in ()
/#1  0x0000007f80b40c7c in ()
/#2  0x0000007ff7a29000 in vtable for InlinedCallFrame () at /opt/dotnet-sdk-6.0.103/shared/Microsoft.NETCore.App/6.0.3/libcoreclr.so

Also:
run LD_DEBUG=libs dotnet /opt/UVtools-3.4.3/UVtools.WPF/bin/Debug/net6.0/UVtools.dll
... bunch of library load output ...
calling init:  /opt/UVTools-3.4.3/UVtools.WPF/bin/Debug/net6.0/runtimes/linux-arm64/native/libHarfbuzzSharp.so
Segmentation Fault

(NOTE: I moved the libHarfbuzzSharp.so and libSkiaSharp.so from the source build dir to the directory listed above as well as to the system library)

does this help at all??  I really wish I could help more with this, UVtools is also an app built on Avalonia, which needs libHarfbuzzSharp (at least for this project)

I also just finished recompiling openssl 1.1.1, openssl 3, and dotnet from source (the prebuilt dotnet 6's have serious issues right now with the dated versions of ossl that ship with raspberry pi os).  I'll try harfbuzz, libSkiaSharp, libHarfbuzzSharp, then UVTools and see if anything changes
