### ISSUE TITLE
[BUG] Skottie failed to call native method in arm64

### ISSUE THREAD

**Issue by OmidID** [mono/SkiaSharp#2143]
**Description**

Library failed to call native methods. `skottie_animation_make_from_string`

**Code**

```
Animation.Parse(loadingAnimation)
```

**Expected Behavior**
```
Unhandled exception. System.EntryPointNotFoundException: Unable to find an entry point named 'skottie_animation_make_from_string' in shared library 'libSkiaSharp'.
   at SkiaSharp.SkottieApi.skottie_animation_make_from_string(String data, Int32 length)
   at SkiaSharp.Skottie.Animation.TryParse(String json, Animation& animation)
   at SkiaSharp.Skottie.Animation.Parse(String json)
```
**Actual Behavior**

**Basic Information**

- Version with issue:  2.88.1-preview.79
- Last known good version:  2.88.1-preview.79
- IDE:  Any
- Platform Target Frameworks: dotnet 6
  - Linux: raspberrypi 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux
- Target Devices:   RPi 3

**Comment by OmidID** [comment]
I did the test using Stream and result was the same thing
```
Unhandled exception. System.EntryPointNotFoundException: Unable to find an entry point named 'skottie_animation_make_from_stream' in shared library 'libSkiaSharp'.
   at SkiaSharp.Skottie.Animation.TryCreate(SKStream stream, Animation& animation)
```
