### ISSUE TITLE
[BUG] error during linking SkiaSharp.Views.Android

### ISSUE THREAD

**Issue by NPadrutt** [mono/SkiaSharp#2291]
**Description**

I have a .net MAUI app that uses SkiaSharp via LiveCharts2. On .net 6 and .net 7 RC1 that worked without issues. on .net 7 RC2 I get this error when I publish my app for Android:

```
ILLink : error IL1011: Failed to write 'obj\Release\net7.0-android\android-x86\linked\SkiaSharp.Views.Android.dll'. [D:\a\MoneyFox\MoneyFox\src\MoneyFox.Ui\MoneyFox.Ui.csproj::TargetFramework=net7.0-android]
  Fatal error in IL Linker
  Unhandled exception. Mono.Linker.LinkerFatalErrorException: ILLink: error IL1011: Failed to write 'obj\Release\net7.0-android\android-x86\linked\SkiaSharp.Views.Android.dll'.
   ---> System.ArgumentException: Member 'System.Int32 SKCanvasView_ignorePixelScaling' is declared in another module and needs to be imported
     at Mono.Cecil.MetadataBuilder.LookupToken(IMetadataTokenProvider provider)
     at Mono.Cecil.Cil.CodeWriter.WriteOperand(Instruction instruction)
     at Mono.Cecil.Cil.CodeWriter.WriteInstructions()
     at Mono.Cecil.Cil.CodeWriter.WriteResolvedMethodBody(MethodDefinition method)
     at Mono.Cecil.Cil.CodeWriter.WriteMethodBody(MethodDefinition method)
     at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
     at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
     at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
     at Mono.Cecil.MetadataBuilder.AddTypes()
     at Mono.Cecil.MetadataBuilder.BuildTypes()
     at Mono.Cecil.MetadataBuilder.BuildModule()
     at Mono.Cecil.MetadataBuilder.BuildMetadata()
     at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
     at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
     at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
     at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
     at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
     at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
     at Mono.Cecil.AssemblyDefinition.Write(String fileName, WriterParameters parameters)
     at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory, WriterParameters writerParameters)
     --- End of inner exception stack trace ---
     at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory, WriterParameters writerParameters)
     at Mono.Linker.Steps.OutputStep.OutputAssembly(AssemblyDefinition assembly)
     at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Main(String[] args)

```

I'm able to publish for iOS without issues though.

**Code**

**Expected Behavior**

**Actual Behavior**

**Basic Information**

- Version with issue:  
- Last known good version:  
- IDE:  
- Platform Target Frameworks: 
  - Android: .net7-android RC2
  - iOS: .net7-iosRC2
  - Linux:  
  - macOS:  
  - Tizen:   
  - tvOS:  
  - UWP:   
  - watchOS:  
  - Windows Classic:  
- Target Devices:   
  - 
  - 
  
<details>
  <summary>Detailed IDE/OS information (click to expand)</summary>
  
```

PASTE ANY DETAILED VERSION INFO HERE

```
</details>

**Screenshots**

**Reproduction Link**

**Comment by NPadrutt** [comment]
The issue persists on the stable release of .net 7.

**Comment by justlucky** [comment]
As an update, this issue persists on the stable release of .net 7.

**Comment by AswinPG** [comment]
As an update, this issue persists on the stable release of .net 7. :(

**Comment by clough360** [comment]
Yes, can confirm this issue with stable release of .Net 7. Only occurs on Android, compiles ok on IOS

**Comment by tipa** [comment]
Same problem has been posted here (incl. a workaround): https://github.com/dotnet/maui/issues/11901
