### ISSUE TITLE
[BUG] Segfault/Fatal CLR Error when copying from SKDataStream into FileStream

### ISSUE THREAD

**Issue by alexhorner** [mono/SkiaSharp#2306]
This is really difficult to reproduce, and is very inconsistent and hard to reproduce. I am really unskilled when it comes to issues occuring in unmanaged code, and I'm assuming this is a problem with Skia and not SkiaSharp, but I best open the issue here initially.

I am copying from an SKDataStream to a FileStream with CopyToAsync. Occasionally, for no apparent reason, this operation fails and hard crashes the entire .NET runtime with a segfault on Linux and a Fatal CLR Error on Windows.

**Code**

```csharp
SKImage sourceImage = SKImage.FromEncodedData(downloadedDataStream);
decimal widthRatio = (decimal)200 / sourceImage.Width;
decimal ratio = Math.Min(widthRatio, 1);
            
int newWidth = Convert.ToInt32(Math.Ceiling(sourceImage.Width * ratio));
int newHeight = Convert.ToInt32(Math.Ceiling(sourceImage.Height * ratio));

using SKSurface? surface = SKSurface.Create(new SKImageInfo
{
    Width = newWidth,
    Height = newHeight,
    ColorType = SKImageInfo.PlatformColorType,
    AlphaType = SKAlphaType.Premul
});

using SKPaint paint = new();

paint.IsAntialias = true;
paint.FilterQuality = SKFilterQuality.High;

surface.Canvas.DrawImage(sourceImage, new SKRectI(0, 0, newWidth, newHeight), paint);
surface.Canvas.Flush();

using SKImage ss = surface.Snapshot();
using SKData? thumbnailPng = ss.Encode();
Stream? thumbnailPngData = thumbnailPng.AsStream();

if (thumbnailPngData is not null)
{
    await using FileStream fileHandle = File.OpenWrite(filePath);
    thumbnailPngData.Position = 0;
    await thumbnailPngData.CopyToAsync(fileHandle);
    fileHandle.Close();
    
    await thumbnailPngData.DisposeAsync();
}
```

I have of course taken this code out of context a bit, but everything is essentially the same. That OpenWrite takes a path which is generated way above this code in the real thing, and downloadedDataStream is a stream of PNG or JPG bytes which is also generated way above.

**Expected Behavior**

Copy works consistently every time

**Actual Behavior**

Inconsistent behaviour where the copy just doesn't work. Doesn't appear to be invalid input image data at all, as it can crash and succeed on the same image.

**Basic Information**

- Version with issue:  2.88.3
- Last known good version:  N/A Just started using SkiaSharp
- IDE:  Rider on Windows whilst debugging
- Platform Target Frameworks:
  - Linux:  Debian 11
  - Windows Classic:   Windows 10 Pro 10.0.19044
- Target Devices:
  - Linux server
  - Windows PC

**Screenshots**

As you can see, my IDE breaks at the CopyToAsync:
![image](https://user-images.githubusercontent.com/33007665/200140248-9e31e43f-0f70-40f5-811e-81b105b0a52f.png)

**Crash Output**
Linux Production Release, captured using GDB debug:

```
Thread 53 ".NET ThreadPool" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffa6a7fc700 (LWP 151468)]
__longjmp () at ../sysdeps/x86_64/__longjmp.S:111
111     ../sysdeps/x86_64/__longjmp.S: No such file or directory.

Thread 53 ".NET ThreadPool" received signal SIGSEGV, Segmentation fault.
0x00007ffff779a0af in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/6.0.10/libcoreclr.so
```

Windows Debugging:

```
Fatal error. Internal CLR error. (0x80131506)
   at System.Buffer._Memmove(Byte ByRef, Byte ByRef, UIntPtr)
   at System.Buffer.Memmove(Byte ByRef, Byte ByRef, UIntPtr)
   at System.IO.UnmanagedMemoryStream.ReadCore(System.Span`1<Byte>)
   at System.IO.UnmanagedMemoryStream.Read(Byte[], Int32, Int32)
   at System.IO.UnmanagedMemoryStream.ReadAsync(System.Memory`1<Byte>, System.Threading.CancellationToken)
   at System.IO.Stream+<<CopyToAsync>g__Core|29_0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.IO.Stream+<<CopyToAsync>g__Core|29_0>d, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](<<CopyToAsync>g__Core|29_0>d ByRef)
   at System.IO.Stream.<CopyToAsync>g__Core|29_0(System.IO.Stream, System.IO.Stream, Int32, System.Threading.CancellationToken)
   at System.IO.Stream.CopyToAsync(System.IO.Stream, Int32, System.Threading.CancellationToken)
   at System.IO.Stream.CopyToAsync(System.IO.Stream)
   at MyPrivateApplicationRedacted+<MyPrivateMethodRedacted>d__29.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Boolean, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKey
Token=7cec85d7bea7798e]](System.__Canon ByRef)
   at MyPrivateApplicationRedacted.MyPrivateMethodRedacted (System.IO.Stream, System.String, System.String, System.String)
   at MyPrivateApplicationRedacted+<MyOtherPrivateMethodRedacted >d__22.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Vers
ion=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Vers
ion=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Vers
ion=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TrySetResult(System.__Canon)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SetExistingTaskResult(System.Threading.Tasks.Task`1<System.__Canon>, System.__Canon)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SetResult(System.__Canon)
   at MyPrivateApplicationRedacted+<MyYetAnotherPrivateMethodRedacted>d__28.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=ne
utral, PublicKeyToken=7cec85d7bea7798e]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=ne
utral, PublicKeyToken=7cec85d7bea7798e]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=ne
utral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.TrySetResult()
   at System.Threading.Tasks.ValueTask+ValueTaskSourceAsTask+<>c.<.cctor>b__4_0(System.Object)
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1[[System.Int64, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SignalCompletion()
   at Microsoft.Win32.SafeHandles.SafeFileHandle+ThreadPoolValueTaskSource.ExecuteInternal()
   at Microsoft.Win32.SafeHandles.SafeFileHandle+ThreadPoolValueTaskSource+<>c.<System.Threading.IThreadPoolWorkItem.Execute>b__18_0(ThreadPoolValueTaskSource)
   at Microsoft.Win32.SafeHandles.SafeFileHandle+ThreadPoolValueTaskSource.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

**Comment by alexhorner** [comment]
I should note I have been unable to reproduce this in a separate console app using essentially that sample code I provided

**Comment by alexhorner** [comment]
Replacing
```csharp
Stream? thumbnailPngData = thumbnailPng.AsStream();
```

and

```csharp
thumbnailPngData.Position = 0;
await thumbnailPngData.CopyToAsync(fileHandle);
```

with a direct

```
thumbnailPng.SaveTo(fileHandle);
```

Does not resolve the issue.
