### ISSUE TITLE
[BUG] Unable to load shared library 'libSkiaSharp' or one of its dependencies on Linux

### ISSUE THREAD

**Issue by Rudazzle** [mono/SkiaSharp#2377]
**Description**

I've built a .NET Core 6 application that runs without issue on my local Windows 11 machine.  I've deployed it to an Ubuntu 20.04 server and I receive an error that it cannot load the libSkiaSharp shared library.  I've seen other people report this issue but none of the suggestions are working for me.  I will preface this with this is my first foray into Linux servers so this has been a huge learning curve.  However, I've spent days trying to resolve this now and I can't figure out what is wrong.

I use SkiaSharp with text via SKTypeFace so I believe I need the SkiaSharp.NativeAssets.Linux package.  However, after trying other suggestions and those not working, I removed the package and installed SkiaSharp.NativeAssets.Linux.NoDependencies.  I'm still receiving the error though.  My application takes user input to determine how SkiaSharp is used so I'm not hitting any code that is using SKTypeFace and I'm still receiving the same error while using the NoDependencies package.

My project has references to the following packages:
![image](https://user-images.githubusercontent.com/19159582/217980370-fa9173f0-f0e5-4141-b962-b62d9d5d0893.png)

I initially published the application with Target-Runtime = Portable but that didn't work.  I tried moving the LibSkiaSharp.so file from the Runtimes directory to my web applications directory and that didn't work.  I've also tried updating my publish settings to Target-Runtime=linux-x64 as this puts all of the project files in the root directory, redeployed, restarted the apache server and still receive the error.  

Here are the file permissions for the deployed libSkiaSharp.so:
![image](https://user-images.githubusercontent.com/19159582/217980936-45ce88b6-d5ce-4e87-9269-b1683a6cf938.png)

I've run the ldd command and it appears to have all of the necessary dependencies for libSkiaSharp.so.
![image](https://user-images.githubusercontent.com/19159582/217979149-46a7e579-07a0-40f9-a579-722b4e71dc02.png)

I've also run the command to install libfontconfig1 as well

**Code**
`byte[] imageBytes = Convert.FromBase64String(details.ImageBase64);

SKBitmap skBitmapOriginal = SKBitmap.Decode(imageBytes);`

**Expected Behavior**

Application is able to find the libSkiaSharp library when run in a Linux environment

**Actual Behavior**

Error is received whenever SkiaSharp is used via code in a Linux environment
![image](https://user-images.githubusercontent.com/19159582/217982016-5056f3e8-9a84-493c-bd5b-cd2a5e19add1.png)
Feb  9 19:40:10 vmi1190349 dotnet-MyTest[9456]:       System.TypeInitializationException: The type initializer for 'SkiaSharp.SKData' threw an exception.
<e LD_DEBUG environment variable: liblibSkiaSharp: cannot open shared object file: No such file or directory
Feb  9 19:40:10 vmi1190349 dotnet-MyTest[9456]: fail: MyTest.Controllers.MyController[0]
Feb  9 19:40:10 vmi1190349 dotnet-MyTest[9456]:       The type initializer for 'SkiaSharp.SKData' threw an exception.
Feb  9 19:40:10 vmi1190349 dotnet-MyTest[9456]:       System.TypeInitializationException: The type initializer for 'SkiaSharp.SKData' threw an exception.
Feb  9 19:40:10 vmi1190349 dotnet-MyTest[9456]:        ---> System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibSkiaSharp: cannot open shared object file: No such file or directory
Feb  9 19:40:10 vmi1190349 dotnet-MyTest[9456]:          at SkiaSharp.SkiaApi.sk_data_new_empty()
Feb  9 19:40:10 vmi1190349 dotnet-MyTest[9456]:          at SkiaSharp.SKData..cctor()
Feb  9 19:40:10 vmi1190349 dotnet-MyTest[9456]:          --- End of inner exception stack trace ---
Feb  9 19:40:10 vmi1190349 dotnet-MyTest[9456]:          at SkiaSharp.SKData.Create(IntPtr address, Int32 length)
Feb  9 19:40:10 vmi1190349 dotnet-MyTest[9456]:          at SkiaSharp.SKBitmap.Decode(ReadOnlySpan`1 buffer)
Feb  9 19:40:10 vmi1190349 dotnet-MyTest[9456]:          at SkiaSharp.SKBitmap.Decode(Byte[] buffer)
Feb  9 19:40:10 vmi1190349 dotnet-MyTest[9456]:          at Test.Common.Image.ImageManager.GenerateImage(ImageOptions MyPost, Details details) in C:\Users\TestUser\source\repos\Test.Web.Main\Test.Common.Image\ImageManager.cs:line 109
Feb  9 19:40:10 vmi1190349 dotnet-MyTest[9456]:          at MyTest.Controllers.MyController.Get(ImageOptions MyPost) in C:\Users\TestUser\source\repos\Test.Web.Main\MyTest\Controllers\MyController.cs:line 84

### Here's the output from LD_DEBUG, which does have a reference where it says libSkiaSharp.so: command not found:

root@vmi1190349:/var/www/mytest.com/public_html# LD_DEBUG=libs libSkiaSharp.so
     16710:     find library=libc.so.6 [0]; searching
     16710:      search cache=/etc/ld.so.cache
     16710:       trying file=/lib/x86_64-linux-gnu/libc.so.6
     16710:
     16710:     find library=libpthread.so.0 [0]; searching
     16710:      search cache=/etc/ld.so.cache
     16710:       trying file=/lib/x86_64-linux-gnu/libpthread.so.0
     16710:
     16710:     find library=libdl.so.2 [0]; searching
     16710:      search cache=/etc/ld.so.cache
     16710:       trying file=/lib/x86_64-linux-gnu/libdl.so.2
     16710:
     16710:     find library=libutil.so.1 [0]; searching
     16710:      search cache=/etc/ld.so.cache
     16710:       trying file=/lib/x86_64-linux-gnu/libutil.so.1
     16710:
     16710:     find library=libm.so.6 [0]; searching
     16710:      search cache=/etc/ld.so.cache
     16710:       trying file=/lib/x86_64-linux-gnu/libm.so.6
     16710:
     16710:     find library=libexpat.so.1 [0]; searching
     16710:      search cache=/etc/ld.so.cache
     16710:       trying file=/lib/x86_64-linux-gnu/libexpat.so.1
     16710:
     16710:     find library=libz.so.1 [0]; searching
     16710:      search cache=/etc/ld.so.cache
     16710:       trying file=/lib/x86_64-linux-gnu/libz.so.1
     16710:
     16710:
     16710:     calling init: /lib/x86_64-linux-gnu/libpthread.so.0
     16710:
     16710:
     16710:     calling init: /lib/x86_64-linux-gnu/libc.so.6
     16710:
     16710:
     16710:     calling init: /lib/x86_64-linux-gnu/libz.so.1
     16710:
     16710:
     16710:     calling init: /lib/x86_64-linux-gnu/libexpat.so.1
     16710:
     16710:
     16710:     calling init: /lib/x86_64-linux-gnu/libm.so.6
     16710:
     16710:
     16710:     calling init: /lib/x86_64-linux-gnu/libutil.so.1
     16710:
     16710:
     16710:     calling init: /lib/x86_64-linux-gnu/libdl.so.2
     16710:
     16710:
     16710:     initialize program: /usr/bin/python3
     16710:
     16710:
     16710:     transferring control: /usr/bin/python3
     16710:
     16710:
     16710:     calling init: /usr/lib/python3.8/lib-dynload/_json.cpython-38-x86_64-linux-gnu.so
     16710:
     16710:     find library=libsqlite3.so.0 [0]; searching
     16710:      search cache=/etc/ld.so.cache
     16710:       trying file=/lib/x86_64-linux-gnu/libsqlite3.so.0
     16710:
     16710:
     16710:     calling init: /lib/x86_64-linux-gnu/libsqlite3.so.0
     16710:
     16710:
     16710:     calling init: /usr/lib/python3.8/lib-dynload/_sqlite3.cpython-38-x86_64-linux-gnu.so
     16710:
     16710:     find library=libapt-pkg.so.6.0 [0]; searching
     16710:      search cache=/etc/ld.so.cache
     16710:       trying file=/lib/x86_64-linux-gnu/libapt-pkg.so.6.0
     16710:
     16710:     find library=libstdc++.so.6 [0]; searching
     16710:      search cache=/etc/ld.so.cache
     16710:       trying file=/lib/x86_64-linux-gnu/libstdc++.so.6
     16710:
     16710:     find library=libgcc_s.so.1 [0]; searching
     16710:      search cache=/etc/ld.so.cache
     16710:       trying file=/lib/x86_64-linux-gnu/libgcc_s.so.1
     16710:
     16710:     find library=libresolv.so.2 [0]; searching
     16710:      search cache=/etc/ld.so.cache
     16710:       trying file=/lib/x86_64-linux-gnu/libresolv.so.2
     16710:
     16710:     find library=libbz2.so.1.0 [0]; searching
     16710:      search cache=/etc/ld.so.cache
     16710:       trying file=/lib/x86_64-linux-gnu/libbz2.so.1.0
     16710:
     16710:     find library=liblzma.so.5 [0]; searching
     16710:      search cache=/etc/ld.so.cache
     16710:       trying file=/lib/x86_64-linux-gnu/liblzma.so.5
     16710:
     16710:     find library=liblz4.so.1 [0]; searching
     16710:      search cache=/etc/ld.so.cache
     16710:       trying file=/lib/x86_64-linux-gnu/liblz4.so.1
     16710:
     16710:     find library=libzstd.so.1 [0]; searching
     16710:      search cache=/etc/ld.so.cache
     16710:       trying file=/lib/x86_64-linux-gnu/libzstd.so.1
     16710:
     16710:     find library=libudev.so.1 [0]; searching
     16710:      search cache=/etc/ld.so.cache
     16710:       trying file=/lib/x86_64-linux-gnu/libudev.so.1
     16710:
     16710:     find library=libsystemd.so.0 [0]; searching
     16710:      search cache=/etc/ld.so.cache
     16710:       trying file=/lib/x86_64-linux-gnu/libsystemd.so.0
     16710:
     16710:     find library=libgcrypt.so.20 [0]; searching
     16710:      search cache=/etc/ld.so.cache
     16710:       trying file=/lib/x86_64-linux-gnu/libgcrypt.so.20
     16710:
     16710:     find library=librt.so.1 [0]; searching
     16710:      search cache=/etc/ld.so.cache
     16710:       trying file=/lib/x86_64-linux-gnu/librt.so.1
     16710:
     16710:     find library=libgpg-error.so.0 [0]; searching
     16710:      search cache=/etc/ld.so.cache
     16710:       trying file=/lib/x86_64-linux-gnu/libgpg-error.so.0
     16710:
     16710:
     16710:     calling init: /lib/x86_64-linux-gnu/libgpg-error.so.0
     16710:
     16710:
     16710:     calling init: /lib/x86_64-linux-gnu/librt.so.1
     16710:
     16710:
     16710:     calling init: /lib/x86_64-linux-gnu/libgcrypt.so.20
     16710:
     16710:
     16710:     calling init: /lib/x86_64-linux-gnu/liblzma.so.5
     16710:
     16710:
     16710:     calling init: /lib/x86_64-linux-gnu/liblz4.so.1
     16710:
     16710:
     16710:     calling init: /lib/x86_64-linux-gnu/libsystemd.so.0
     16710:
     16710:
     16710:     calling init: /lib/x86_64-linux-gnu/libudev.so.1
     16710:
     16710:
     16710:     calling init: /lib/x86_64-linux-gnu/libzstd.so.1
     16710:
     16710:
     16710:     calling init: /lib/x86_64-linux-gnu/libbz2.so.1.0
     16710:
     16710:
     16710:     calling init: /lib/x86_64-linux-gnu/libresolv.so.2
     16710:
     16710:
     16710:     calling init: /lib/x86_64-linux-gnu/libgcc_s.so.1
     16710:
     16710:
     16710:     calling init: /lib/x86_64-linux-gnu/libstdc++.so.6
     16710:
     16710:
     16710:     calling init: /lib/x86_64-linux-gnu/libapt-pkg.so.6.0
     16710:
     16710:
     16710:     calling init: /usr/lib/python3/dist-packages/apt_pkg.cpython-38-x86_64-linux-gnu.so
     16710:
     16710:
     16710:     calling init: /usr/lib/python3.8/lib-dynload/_bz2.cpython-38-x86_64-linux-gnu.so
     16710:
     16710:
     16710:     calling init: /usr/lib/python3.8/lib-dynload/_lzma.cpython-38-x86_64-linux-gnu.so
     16710:
     16710:     find library=libnss_files.so.2 [0]; searching
     16710:      search cache=/etc/ld.so.cache
     16710:       trying file=/lib/x86_64-linux-gnu/libnss_files.so.2
     16710:
     16710:
     16710:     calling init: /lib/x86_64-linux-gnu/libnss_files.so.2
     16710:
     16710:     find library=libnss_systemd.so.2 [0]; searching
     16710:      search cache=/etc/ld.so.cache
     16710:       trying file=/lib/x86_64-linux-gnu/libnss_systemd.so.2
     16710:
     16710:
     16710:     calling init: /lib/x86_64-linux-gnu/libnss_systemd.so.2
     16710:
**libSkiaSharp.so: command not found**
     16710:
     16710:     calling fini: /usr/bin/python3 [0]
     16710:
     16710:
     16710:     calling fini: /lib/x86_64-linux-gnu/libutil.so.1 [0]
     16710:
     16710:
     16710:     calling fini: /lib/x86_64-linux-gnu/libexpat.so.1 [0]
     16710:
     16710:
     16710:     calling fini: /usr/lib/python3.8/lib-dynload/_json.cpython-38-x86_64-linux-gnu.so [0]
     16710:
     16710:
     16710:     calling fini: /usr/lib/python3.8/lib-dynload/_sqlite3.cpython-38-x86_64-linux-gnu.so [0]
     16710:
     16710:
     16710:     calling fini: /lib/x86_64-linux-gnu/libsqlite3.so.0 [0]
     16710:
     16710:
     16710:     calling fini: /lib/x86_64-linux-gnu/libdl.so.2 [0]
     16710:
     16710:
     16710:     calling fini: /usr/lib/python3/dist-packages/apt_pkg.cpython-38-x86_64-linux-gnu.so [0]
     16710:
     16710:
     16710:     calling fini: /lib/x86_64-linux-gnu/libapt-pkg.so.6.0 [0]
     16710:
     16710:
     16710:     calling fini: /lib/x86_64-linux-gnu/libz.so.1 [0]
     16710:
     16710:
     16710:     calling fini: /lib/x86_64-linux-gnu/libstdc++.so.6 [0]
     16710:
     16710:
     16710:     calling fini: /lib/x86_64-linux-gnu/libm.so.6 [0]
     16710:
     16710:
     16710:     calling fini: /lib/x86_64-linux-gnu/libgcc_s.so.1 [0]
     16710:
     16710:
     16710:     calling fini: /lib/x86_64-linux-gnu/libresolv.so.2 [0]
     16710:
     16710:
     16710:     calling fini: /lib/x86_64-linux-gnu/libzstd.so.1 [0]
     16710:
     16710:
     16710:     calling fini: /lib/x86_64-linux-gnu/libudev.so.1 [0]
     16710:
     16710:
     16710:     calling fini: /lib/x86_64-linux-gnu/libsystemd.so.0 [0]
     16710:
     16710:
     16710:     calling fini: /lib/x86_64-linux-gnu/liblz4.so.1 [0]
     16710:
     16710:
     16710:     calling fini: /lib/x86_64-linux-gnu/libgcrypt.so.20 [0]
     16710:
     16710:
     16710:     calling fini: /lib/x86_64-linux-gnu/librt.so.1 [0]
     16710:
     16710:
     16710:     calling fini: /lib/x86_64-linux-gnu/libgpg-error.so.0 [0]
     16710:
     16710:
     16710:     calling fini: /usr/lib/python3.8/lib-dynload/_bz2.cpython-38-x86_64-linux-gnu.so [0]
     16710:
     16710:
     16710:     calling fini: /lib/x86_64-linux-gnu/libbz2.so.1.0 [0]
     16710:
     16710:
     16710:     calling fini: /usr/lib/python3.8/lib-dynload/_lzma.cpython-38-x86_64-linux-gnu.so [0]
     16710:
     16710:
     16710:     calling fini: /lib/x86_64-linux-gnu/liblzma.so.5 [0]
     16710:
     16710:
     16710:     calling fini: /lib/x86_64-linux-gnu/libnss_files.so.2 [0]
     16710:
     16710:
     16710:     calling fini: /lib/x86_64-linux-gnu/libnss_systemd.so.2 [0]
     16710:
     16710:
     16710:     calling fini: /lib/x86_64-linux-gnu/libpthread.so.0 [0]
     16710:

**Basic Information**

- Version with issue:  2.88.3
- IDE:  Visual Studio Professional v17.4.4
- Platform Target Frameworks: 
- Linux:  Ubuntu 20.04 64Bit

**Comment by kYann** [comment]
Hello, same issue here. Did you find the solution ?
