### ISSUE TITLE
[BUG] MAUI App crashes on iOS while starting

### ISSUE THREAD

**Issue by erdogdum** [mono/SkiaSharp#2410]
**Description**

I am trying to use SkiaSharp in a .NET MAUI application (.NET 6.0). After the deployment to local device (iPad), when i try to start the app, it crashes with the following error code :

**Output Message**
```
[0:] An error occurred: '@rpath/libSkiaSharp.framework/libSkiaSharp'. Callstack: '   at SkiaSharp.SKPaint..ctor()
   at MauiApp1_60.MainPage..ctor() in D:\Projeler\TEMP\MauiApp1-60\MainPage.xaml.cs:line 13
   at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object obj, Object[] parameters, Boolean wrapExceptions)'
The app has been terminated.
```

App crashes only when i try to deploy to iPad. For Android and Windows, it works.

In the code I am just trying to call the ctor of SKPaint class with the following code :

```
public MainPage()
	{
		InitializeComponent();

		var a = new SKPaint();
	}

```
When i remove the construction of SKPaint(), the app deploys and runs on iPad. 

I also added the .UseSkiaSharp() command in MauiProgram class as :

```
public static MauiApp CreateMauiApp()
	{
		var builder = MauiApp.CreateBuilder();
		builder
			.UseMauiApp<App>()
			.UseSkiaSharp()
			.ConfigureFonts(fonts =>
			{
				fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
				fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
			});

		return builder.Build();
	}
```

**Expected Behavior**

Creating an instance of a SKPaint class.

**Actual Behavior**

App crashes

**Basic Information**

- Version with issue:  
   SkiaSharp.Views.Maui.Controls (2.88.3), 
   SkiaSharp.Views.Maui.Controls.Compatibility (2.88.3)
   SkiaSharp.Views.Maui.Core(2.88.3)

- IDE:  Microsoft Visual Studio Enterprise 2022 (64-bit) - Current Version 17.5.0 (Windows 11)
- Platform Target Frameworks:
- iOS:  13.6
- Target Devices:  
  iPad 9. Generation, iPadOs : 16.3.1

<details>
  <summary>Detailed IDE/OS information (click to expand)</summary>
  
```

Microsoft Visual Studio Enterprise 2022
Version 17.5.0
VisualStudio.17.Release/17.5.0+33414.496
Microsoft .NET Framework
Version 4.8.09032

Installed Version: Enterprise

ASP.NET and Web Tools   17.5.317.37931
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.5.317.37931
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.5.317.37931
Azure Functions and Web Jobs Tools

C# Tools   4.5.0-6.23109.5+6a5a63bbc9f4449d9bd1e95a8f9624939c3ccdc3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.4.3 (main@2a4517a)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.5.9 (11975e6)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.5.2.2307502+8b3141d86b738daf2ca3ed9c15b12513071fc676
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.2.40118.0
Microsoft SQL Server Data Tools

TypeScript Tools   17.0.20105.2003
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.5.0-6.23109.5+6a5a63bbc9f4449d9bd1e95a8f9624939c3ccdc3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.5.0-beta.23053.5+794b7c259d9646a7eb685dad865aa27da7940a21
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.5.0.173 (d17-5@33e727c)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.5.3.46 (remotes/origin/d17-5@e4dd80b2bb)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.5.41 (ba80d05)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.2.0.0 (d17-5/797e2e1)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 6dd9def
    Java.Interop: xamarin/java.interop/main@149d70fe
    SQLite: xamarin/sqlite/3.40.0@fdc1e34
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@9f02d77


Xamarin.iOS and Xamarin.Mac SDK   16.2.0.5 (7738c90c9)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

```
</details>

**Comment by UkeHa** [comment]
Can confirm, SKCodec.Create(inputStream); doesn't work either. I suspect this has to do with the native libraries not being copied into the right directory and therefore failing. @mattleibow, could you try to reproduce this issue?

**Comment by cwilde123** [comment]
I'm getting the same issue. I'm using a library that uses SKIA MAUI lib and I boiled down the bug to when it tries to create a new SKpaint object it crashes on iOS. It's weird though because it works on the iOS simulator running 16.2 but not a real device on any iOS version I tested running in either debug or release with Adhoc previsioning profile. @erdogdum  Does it work on a simulator for you? Will there be a fix for this?

**Comment by UkeHa** [comment]
My workaround for this is twofold.

First, i compress my pictures with iOS-specific code:

`#if IOS
		private static byte[] ResizeImageIos(byte[] imageData)
		{
			var originalImage = ImageFromByteArray(imageData);
			using var jpgImage = originalImage.AsJPEG(0.9f);
			return jpgImage.ToArray();
		}
		public static UIImage ImageFromByteArray(byte[] data)
		{
			if (data == null)
			{
				return null;
			}

			UIImage image;
			try
			{
				image = new UIImage(NSData.FromArray(data));
			}
			catch (Exception e)
			{
				return null;
			}
			return image;
		}
#endif`

Second, i'm using https://github.com/dimonovdd/Xamarin.MediaGallery to capture/select images, as the current implementation in MAUI is broken and doesn't return the image orientation.

**Comment by LRufenacht** [comment]
Same issue here.

**Comment by cwilde123** [comment]
@Inrego No it's really annoying, tried cloning the whole repo down and fixing the SKpaint object myself but there is so many dependencies for this so it's no point. This is a major bug that needs to be fixed

**Comment by Inrego** [comment]
I actually managed to get it working. What I did was to connect my iPad directly to the Mac, and deploy the app to iOS Remote Devices -> device rather than doing the Hot Reload thingy where the device is connected directly to the Windows machine.

Other things I also did, which may or may not be necessary: Changed Minimum Target iOS Framework to 13.6 (I noticed that the SkiaSharp NuGet targets net6.0-ios13.6)

**Comment by erdogdum** [comment]
@Inrego 's solution works and that's how we also tried to implement.
