### ISSUE TITLE
[BUG] .NET 7.0 MAUI requires BOTH Microsoft.Maui.Graphics.Skia AND SkiaSharp.Views.Maui.Core installed to run any simple SkiaSharp functions on iOS? Is this normal?

### ISSUE THREAD

**Issue by jonmdev** [mono/SkiaSharp#2636]
### Description

I am using .NET 7.0 MAUI and I presume the only SkiaSharp library we should need for basic functions is this one: https://www.nuget.org/packages/Microsoft.Maui.Graphics.Skia/7.0.92

With just this package installed, I can use normal basic SkiaSharp functions like the following in Windows and Android:

- `SKBitmap bitmap = new SKBitmap()`
- `SKBitmap bitmap = SKBitmap.Decode(stream);` 

However, when I try to build directly in Debug to iOS iPhone XR (no Mac device available), any reference to any SkiaSharp code like the above crashes it and prevents it from starting with the following error `An error occurred: '@rpath/libSkiaSharp.framework/libSkiaSharp'. Callstack: '   at SkiaSharp.SKBitmap..ctor()`.

Even just a single line saying `SKBitmap = new SKBitmap();` breaks the app.

I read about adding the line `[assembly: ObjCRuntime.LinkWith("libSkiaSharp.framework", SmartLink = true)]` to AssemblyInfo.cs and tried doing that in the iOS debug ones but no benefit as per this link: https://stackoverflow.com/questions/45275372/dllnotfoundexception-is-thrown-after-ilmerge-skiasharp-into-my-xamarin-ios-dll

I have no idea why this is happening. It says `Loaded assembly: /private/var/mobile/Containers/Data/Application/.../Documents/MauiBuild.content/SkiaSharp.dll` so why isn't it working?

I then tried adding the following package as well: https://www.nuget.org/packages/SkiaSharp.Views.Maui.Core/2.88.6

And with this the iOS error goes away. I can again use basic functions like `SKBitmap bitmap = new SKBitmap();` in iOS.

However, I would like to know if this is normal behavior. I do not need any special "Views" related functions which I believe SkiaSharp.Views.Maui.Core is for. Why is Microsoft.Maui.Graphics.Skia not enough to even create an empty SKBitmap in iOS?

Thanks for any clarification or guidance. It is appreciated.

### Code

`SKBitmap bitmap = new SKBitmap();` is all that it is taking to trigger this. When only Microsoft.Maui.Graphics.Skia is installed this fails with `An error occurred: '@rpath/libSkiaSharp.framework/libSkiaSharp'. Callstack: '   at SkiaSharp.SKBitmap..ctor()`.

Installing SkiaSharp.Views.Maui.Core  as well solves this in iOS, but this is not needed in any other operating system.

### Expected Behavior

Something simple like `SKBitmap bitmap = new SKBitmap();` should be possible in iOS just like Android and Windows with `Microsoft.Maui.Graphics.Skia` or otherwise what is the point of this package at all? 

### Actual Behavior

The SkiaSharp.Views.Maui.Core package is described as "a set of views that can be used to draw on the screen," which is great, but not what I need in any way. I presume I shouldn't have to install both packages just to make an `SKBitmap` object at least in principle. This works on Android/Windows but iOS somehow needs this extra package in addition to Microsoft.Maui.Graphics.Skia   to do it.

### Version of SkiaSharp

2.88.3 (Current)

### Last Known Good Version of SkiaSharp

2.88.2 (Previous)

### IDE / Editor

Visual Studio (Windows)

### Platform / Operating System

iOS

### Platform / Operating System Version

iOS 16.7

### Devices

Apple iPhone XR

### Relevant Log Output

```shell
LOG OF ATTEMPTED DEBUG BUILD WITH ONLY Microsoft.Maui.Graphics.Skia ADDED AS PACKAGE, BREAKING ON SIMPLE ATTEMPT TO MAKE NEW SKBITMAP OBJECT:


Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/Microsoft.iOS.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Runtime.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Collections.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Runtime.InteropServices.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Threading.Thread.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Threading.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Net.Http.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Net.Primitives.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Numerics.Vectors.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Net.Sockets.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Drawing.Primitives.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Private.Uri.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/Xamarin.PreBuilt.iOS.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/Xamarin.iOS.HotRestart.Application.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/netstandard.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.IO.MemoryMappedFiles.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.IO.Pipes.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Memory.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Diagnostics.Tracing.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Collections.NonGeneric.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/Microsoft.Win32.Primitives.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Net.NameResolution.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Threading.ThreadPool.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Collections.Concurrent.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Diagnostics.Process.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.ComponentModel.Primitives.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.ComponentModel.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.ObjectModel.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Diagnostics.FileVersionInfo.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Reflection.Metadata.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Collections.Immutable.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Linq.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.IO.Compression.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Text.Encoding.Extensions.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Collections.Specialized.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Security.Cryptography.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Formats.Asn1.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Runtime.Numerics.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.ComponentModel.TypeConverter.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Runtime.Loader.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Text.RegularExpressions.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Reflection.Emit.ILGeneration.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Reflection.Emit.Lightweight.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Reflection.Primitives.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Net.Security.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Security.Claims.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Runtime.Serialization.Formatters.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Resources.Writer.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Xml.XDocument.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Private.Xml.Linq.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Private.Xml.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Diagnostics.TraceSource.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Diagnostics.DiagnosticSource.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Net.Quic.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.IO.Compression.Brotli.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Threading.Channels.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Net.NetworkInformation.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Reflection.Emit.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Linq.Expressions.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.ComponentModel.EventBasedAsync.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Console.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Data.Common.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Xml.ReaderWriter.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Xml.XmlSerializer.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Transactions.Local.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Diagnostics.Contracts.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Diagnostics.TextWriterTraceListener.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Diagnostics.StackTrace.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.IO.Compression.ZipFile.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.IO.FileSystem.DriveInfo.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.IO.FileSystem.Watcher.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.IO.IsolatedStorage.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Linq.Queryable.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Linq.Parallel.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Net.Requests.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Net.WebHeaderCollection.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Net.ServicePoint.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Net.HttpListener.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Net.WebSockets.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Security.Principal.Windows.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Net.WebClient.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Net.WebProxy.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Net.Mail.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Net.Ping.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Net.WebSockets.Client.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Reflection.DispatchProxy.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Runtime.CompilerServices.VisualC.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Runtime.Serialization.Primitives.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Runtime.Serialization.Xml.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Private.DataContractSerialization.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Runtime.Serialization.Json.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Threading.Overlapped.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Threading.Tasks.Parallel.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Web.HttpUtility.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Xml.XPath.XDocument.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Xml.XPath.dll [External]
Thread started:  #2
Thread started: .NET Timer #3
Loaded assembly: /private/var/mobile/Containers/Data/Application/.../Documents/MauiBuild.content/MauiBuild.dll
2023-09-30 00:40:16.946 Xamarin.PreBuilt.iOS[493:19477] Content folder: /var/mobile/Containers/Data/Application/.../Documents/MauiBuild.content

2023-09-30 00:40:16.951 Xamarin.PreBuilt.iOS[493:19477] App path /var/mobile/Containers/Data/Application/.../Documents/MauiBuild.content/MauiBuild.dll

Loaded assembly: /private/var/mobile/Containers/Data/Application/.../Documents/MauiBuild.content/Microsoft.Maui.Controls.dll [External]
Loaded assembly: /private/var/mobile/Containers/Data/Application/.../Documents/MauiBuild.content/Microsoft.Maui.dll [External]
Thread started: <Thread Pool> #4
Thread started: .NET ThreadPool Gate #5
Thread started: <Thread Pool> #6
Loaded assembly: /private/var/mobile/Containers/Data/Application/.../Documents/MauiBuild.content/Microsoft.Maui.Graphics.dll [External]
Loaded assembly: /private/var/mobile/Containers/Data/Application/.../Documents/MauiBuild.content/Microsoft.Maui.Controls.Compatibility.dll [External]
Loaded assembly: /private/var/mobile/Containers/Data/Application/.../Documents/MauiBuild.content/SkiaSharp.dll [External]
Loaded assembly: /private/var/mobile/Containers/Data/Application/.../Documents/MauiBuild.content/SharpHook.dll [External]
Loaded assembly: /private/var/mobile/Containers/Data/Application/.../Documents/MauiBuild.content/Microsoft.Extensions.DependencyInjection.Abstractions.dll [External]
2023-09-30 00:40:17.012 Xamarin.PreBuilt.iOS[493:19477] AppDelegate name: AppDelegate

Loaded assembly: /private/var/mobile/Containers/Data/Application/.../Documents/MauiBuild.content/Microsoft.Extensions.Logging.dll [External]
Loaded assembly: /private/var/mobile/Containers/Data/Application/.../Documents/MauiBuild.content/Microsoft.Extensions.Logging.Abstractions.dll [External]
Loaded assembly: /private/var/mobile/Containers/Data/Application/.../Documents/MauiBuild.content/Microsoft.Extensions.Options.dll [External]
Thread started: <Thread Pool> #7
Loaded assembly: /private/var/mobile/Containers/Data/Application/.../Documents/MauiBuild.content/Microsoft.Maui.Controls.Xaml.dll [External]
Loaded assembly: /private/var/mobile/Containers/Data/Application/.../Documents/MauiBuild.content/Microsoft.Maui.Graphics.Skia.dll [External]
Loaded assembly: /private/var/mobile/Containers/Data/Application/.../Documents/MauiBuild.content/SkiaSharp.Views.iOS.dll [External]
Loaded assembly: /private/var/mobile/Containers/Data/Application/.../Documents/MauiBuild.content/CommunityToolkit.Maui.Core.dll [External]
Loaded assembly: /private/var/mobile/Containers/Data/Application/.../Documents/MauiBuild.content/Microsoft.Extensions.Configuration.dll [External]
Loaded assembly: /private/var/mobile/Containers/Data/Application/.../Documents/MauiBuild.content/Microsoft.Extensions.Configuration.Abstractions.dll [External]
Loaded assembly: /private/var/mobile/Containers/Data/Application/.../Documents/MauiBuild.content/Microsoft.Extensions.Primitives.dll [External]
Loaded assembly: /private/var/mobile/Containers/Data/Application/.../Documents/MauiBuild.content/Microsoft.Extensions.Logging.Debug.dll [External]
Loaded assembly: /private/var/mobile/Containers/Data/Application/.../Documents/MauiBuild.content/CommunityToolkit.Maui.dll [External]
Loaded assembly: /private/var/mobile/Containers/Data/Application/.../Documents/MauiBuild.content/Microsoft.Maui.Essentials.dll [External]
Loaded assembly: /private/var/mobile/Containers/Data/Application/.../Documents/MauiBuild.content/Microsoft.Extensions.DependencyInjection.dll [External]
Resolved pending breakpoint for 'MauiBuild.Program.Main(System.String[])' to H:\Users\...\maui\MauiBuild\MauiBuild\Platforms\iOS\Program.cs:7 [0x00000].
Loaded assembly: data-0x12d5dc000 [External]
Loaded assembly: data-0x12d7a4000 [External]
2023-09-30 00:40:17.542 Xamarin.PreBuilt.iOS[493:19477] Could not resolve assembly Xamarin.HotReload.Contracts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null. Details: Could not load file or assembly '/var/mobile/Containers/Data/Application/.../Documents/MauiBuild.content/Xamarin.HotReload.Contracts.dll' or one of its dependencies.

2023-09-30 00:40:17.531 Xamarin.PreBuilt.iOS[493:19477] Could not resolve assembly Microsoft.VisualStudio.DesignTools.TapContract, Version=17.0.0.0, Culture=neutral, PublicKeyToken=null. Details: Could not load file or assembly '/var/mobile/Containers/Data/Application/.../Documents/MauiBuild.content/Microsoft.VisualStudio.DesignTools.TapContract.dll' or one of its dependencies.

Resolved pending breakpoint for 'Xamarin.HotReload.HotReloadAgent.BreakpointSendToIde(System.String)' to D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Agent\HotReloadAgent.cs:423 [0x00000].
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Text.Json.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/.../MauiBuild.app/System.Text.Encodings.Web.dll [External]
Resolved pending breakpoint for 'Xamarin.HotReload.HotReloadAgent.BreakpointCheckpoint()' to D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Agent\HotReloadAgent.cs:418 [0x00000].
2023-09-30 00:40:17.693 Xamarin.PreBuilt.iOS[493:19477] Could not resolve assembly Microsoft.VisualStudio.DesignTools.TapContract, Version=17.0.0.0, Culture=neutral, PublicKeyToken=null. Details: Could not load file or assembly '/var/mobile/Containers/Data/Application/.../Documents/MauiBuild.content/Microsoft.VisualStudio.DesignTools.TapContract.dll' or one of its dependencies.

2023-09-30 00:40:17.690 Xamarin.PreBuilt.iOS[493:19477] Could not resolve assembly Xamarin.HotReload.Contracts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null. Details: Could not load file or assembly '/var/mobile/Containers/Data/Application/.../Documents/MauiBuild.content/Xamarin.HotReload.Contracts.dll' or one of its dependencies.

Thread started:  #8
Thread started:  #9
Thread started:  #10
2023-09-30 00:40:17.867 Xamarin.PreBuilt.iOS[493:19477] Could not resolve assembly System.Private.DataContractSerialization.resources, Version=7.0.0.0, Culture=en, PublicKeyToken=null. Details: Could not load file or assembly '/var/mobile/Containers/Data/Application/.../Documents/MauiBuild.content/System.Private.DataContractSerialization.resources.dll' or one of its dependencies.

2023-09-30 00:40:17.865 Xamarin.PreBuilt.iOS[493:19477] Could not resolve assembly System.Private.DataContractSerialization.resources, Version=7.0.0.0, Culture=en-CA, PublicKeyToken=null. Details: Could not load file or assembly '/var/mobile/Containers/Data/Application/.../Documents/MauiBuild.content/System.Private.DataContractSerialization.resources.dll' or one of its dependencies.

[0:] An error occurred: '@rpath/libSkiaSharp.framework/libSkiaSharp'. Callstack: '   at SkiaSharp.SKBitmap..ctor()
   at MauiBuild.Scripts.ImageTintBehavior.setImage(String resourceName) in H:\Users\...\maui\MauiBuild\MauiBuild\Scripts\ImageTintBehavior.cs:line 69
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jonmdev** [comment]
Closing as I am no longer using SkiaSharp.
