### ISSUE TITLE
[BUG] SkiaSharp 3.0 Preview 3.1 crashes the release version of the .NET MAUI app at start, debug works fine

### ISSUE THREAD

**Issue by janne-hmp** [mono/SkiaSharp#2828]
### Description

When upgrading the .NET MAUI app (GnollHackM) from Preview 2.1 to 3.1 and building in Release configuration on Android, the app builds fine, but it crashes immediately upon start. Debug configuration, however, works fine, so difficult to know what the problem is. Preview 2.1 worked just fine.

### Code

https://github.com/hyvanmielenpelit/GnollHack

### Expected Behavior

App starts normally in both Release and Debug modes.

### Actual Behavior

App crashes at start in Release mode but works fine in Debug mode.

### Version of SkiaSharp

3.x (Alpha)

### Last Known Good Version of SkiaSharp

Other (Please indicate in the description)

### IDE / Editor

Visual Studio (Windows)

### Platform / Operating System

Android

### Platform / Operating System Version

Android 14

### Devices

Samsung SM-S901B

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by janne-hmp** [comment]
Here's the log:

```
04-15 12:42:53.555  1266  1266 D Zygote  : Forked child process 14629
04-15 12:42:53.555  1656  2068 I ActivityManager: Start proc 14629:com.soundmindgames.gnollhackm/u0a593 for top-activity {com.soundmindgames.gnollhackm/crc6481ebf3e09068bf87.MainActivity}
04-15 12:42:53.567 14629 14629 I ames.gnollhackm: Using CollectorTypeCC GC.
04-15 12:42:53.569 14629 14629 E ames.gnollhackm: Not starting debugger since process cannot load the jdwp agent.
04-15 12:42:53.573 14629 14629 D ActivityThread: setConscryptValidator
04-15 12:42:53.573 14629 14629 D ActivityThread: setConscryptValidator - put
04-15 12:42:53.581 14629 14629 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10593; state: ENABLED
04-15 12:42:53.581 14629 14629 D CompatibilityChangeReporter: Compat change id reported: 242716250; UID 10593; state: ENABLED
04-15 12:42:53.586 14629 14629 W ziparchive: Unable to open '/data/app/~~Qx-ZqsTMknh7WSkBNzt8nw==/com.soundmindgames.gnollhackm-zy7V-_oFhQz3D1Bb2oDbEQ==/split_config.arm64_v8a.dm': No such file or directory
04-15 12:42:53.586 14629 14629 W ziparchive: Unable to open '/data/app/~~Qx-ZqsTMknh7WSkBNzt8nw==/com.soundmindgames.gnollhackm-zy7V-_oFhQz3D1Bb2oDbEQ==/split_config.arm64_v8a.dm': No such file or directory
04-15 12:42:53.587 14629 14629 W ames.gnollhackm: Entry not found
04-15 12:42:53.587 14629 14629 W ziparchive: Unable to open '/data/app/~~Qx-ZqsTMknh7WSkBNzt8nw==/com.soundmindgames.gnollhackm-zy7V-_oFhQz3D1Bb2oDbEQ==/split_config.en.dm': No such file or directory
04-15 12:42:53.587 14629 14629 W ziparchive: Unable to open '/data/app/~~Qx-ZqsTMknh7WSkBNzt8nw==/com.soundmindgames.gnollhackm-zy7V-_oFhQz3D1Bb2oDbEQ==/split_config.en.dm': No such file or directory
04-15 12:42:53.588 14629 14629 W ames.gnollhackm: Entry not found
04-15 12:42:53.588 14629 14629 W ziparchive: Unable to open '/data/app/~~Qx-ZqsTMknh7WSkBNzt8nw==/com.soundmindgames.gnollhackm-zy7V-_oFhQz3D1Bb2oDbEQ==/split_config.fi.dm': No such file or directory
04-15 12:42:53.588 14629 14629 W ziparchive: Unable to open '/data/app/~~Qx-ZqsTMknh7WSkBNzt8nw==/com.soundmindgames.gnollhackm-zy7V-_oFhQz3D1Bb2oDbEQ==/split_config.fi.dm': No such file or directory
04-15 12:42:53.588 14629 14629 W ames.gnollhackm: Entry not found
04-15 12:42:53.588 14629 14629 W ziparchive: Unable to open '/data/app/~~Qx-ZqsTMknh7WSkBNzt8nw==/com.soundmindgames.gnollhackm-zy7V-_oFhQz3D1Bb2oDbEQ==/split_config.xxhdpi.dm': No such file or directory
04-15 12:42:53.588 14629 14629 W ziparchive: Unable to open '/data/app/~~Qx-ZqsTMknh7WSkBNzt8nw==/com.soundmindgames.gnollhackm-zy7V-_oFhQz3D1Bb2oDbEQ==/split_config.xxhdpi.dm': No such file or directory
04-15 12:42:53.588  1656  2042 D PkgPredictorService-SecIpmManagerServiceImpl: onForegroundActivitiesChanged pid:14629 uid:10593
04-15 12:42:53.589 14629 14629 W ames.gnollhackm: Entry not found
04-15 12:42:53.589 14629 14629 W ziparchive: Unable to open '/data/app/~~Qx-ZqsTMknh7WSkBNzt8nw==/com.soundmindgames.gnollhackm-zy7V-_oFhQz3D1Bb2oDbEQ==/split_installtimepack.dm': No such file or directory
04-15 12:42:53.589 14629 14629 W ziparchive: Unable to open '/data/app/~~Qx-ZqsTMknh7WSkBNzt8nw==/com.soundmindgames.gnollhackm-zy7V-_oFhQz3D1Bb2oDbEQ==/split_installtimepack.dm': No such file or directory
04-15 12:42:53.589 14629 14629 W ames.gnollhackm: Entry not found
04-15 12:42:53.591 14629 14629 D nativeloader: Configuring clns-4 for other apk /data/app/~~Qx-ZqsTMknh7WSkBNzt8nw==/com.soundmindgames.gnollhackm-zy7V-_oFhQz3D1Bb2oDbEQ==/base.apk:/data/app/~~Qx-ZqsTMknh7WSkBNzt8nw==/com.soundmindgames.gnollhackm-zy7V-_oFhQz3D1Bb2oDbEQ==/split_config.arm64_v8a.apk:/data/app/~~Qx-ZqsTMknh7WSkBNzt8nw==/com.soundmindgames.gnollhackm-zy7V-_oFhQz3D1Bb2oDbEQ==/split_config.en.apk:/data/app/~~Qx-ZqsTMknh7WSkBNzt8nw==/com.soundmindgames.gnollhackm-zy7V-_oFhQz3D1Bb2oDbEQ==/split_config.fi.apk:/data/app/~~Qx-ZqsTMknh7WSkBNzt8nw==/com.soundmindgames.gnollhackm-zy7V-_oFhQz3D1Bb2oDbEQ==/split_config.xxhdpi.apk:/data/app/~~Qx-ZqsTMknh7WSkBNzt8nw==/com.soundmindgames.gnollhackm-zy7V-_oFhQz3D1Bb2oDbEQ==/split_installtimepack.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~Qx-ZqsTMknh7WSkBNzt8nw==/com.soundmindgames.gnollhackm-zy7V-_oFhQz3D1Bb2oDbEQ==/lib/arm64:/data/app/~~Qx-ZqsTMknh7WSkBNzt8nw==/com.soundmindgames.gnollhackm-zy7V-_oFhQz3D1Bb2oDbEQ==/base.apk!/lib/arm64-v8a:/data/app/~~Qx-ZqsTMknh7WSkBNzt8nw==/com
04-15 12:42:53.599 14629 14629 V GraphicsEnvironment: Currently set values for:
04-15 12:42:53.600 14629 14629 V GraphicsEnvironment:   angle_gl_driver_selection_pkgs=[]
04-15 12:42:53.600 14629 14629 V GraphicsEnvironment:   angle_gl_driver_selection_values=[]
04-15 12:42:53.600 14629 14629 V GraphicsEnvironment: ANGLE GameManagerService for com.soundmindgames.gnollhackm: false
04-15 12:42:53.600 14629 14629 V GraphicsEnvironment: com.soundmindgames.gnollhackm is not listed in per-application setting
04-15 12:42:53.600 14629 14629 V GraphicsEnvironment: Updatable production driver is not supported on the device.
04-15 12:42:53.608 14629 14629 I DOTNET  : JNI_OnLoad: JNI_OnLoad in pal_jni.c
04-15 12:42:53.608 14629 14629 D DOTNET  : GetOptionalClassGRef: optional class com/android/org/conscrypt/OpenSSLEngineImpl was not found
04-15 12:42:53.610 14629 14629 W monodroid: Failed to create directory '/data/user/0/com.soundmindgames.gnollhackm/files/.__override__/arm64-v8a'. No such file or directory
04-15 12:42:53.610 14629 14629 W monodroid: Creating public update directory: `/data/user/0/com.soundmindgames.gnollhackm/files/.__override__/arm64-v8a`
04-15 12:42:53.712 14629 14629 W monodroid-assembly: Shared library 'libSystem.Globalization.Native' not loaded, p/invoke 'GlobalizationNative_LoadICU' may fail
04-15 12:42:53.720 14629 14629 W monodroid-assembly: Shared library 'libSystem.Globalization.Native' not loaded, p/invoke 'GlobalizationNative_LoadICU' may fail
04-15 12:42:53.727 14629 14629 W monodroid-assembly: Shared library 'libSystem.Globalization.Native' not loaded, p/invoke 'GlobalizationNative_LoadICU' may fail
04-15 12:42:53.745 14629 14629 F mono-rt : [ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: TypeInitialization_Type, System.Globalization.CompareInfo
04-15 12:42:53.745 14629 14629 F mono-rt :  ---> System.TypeInitializationException: TypeInitialization_Type, System.Globalization.CultureInfo
04-15 12:42:53.745 14629 14629 F mono-rt :  ---> System.TypeInitializationException: TypeInitialization_Type, Settings
04-15 12:42:53.745 14629 14629 F mono-rt :  ---> System.DllNotFoundException: libSystem.Globalization.Native
04-15 12:42:53.745 14629 14629 F mono-rt :    at System.Globalization.GlobalizationMode.LoadICU()
04-15 12:42:53.745 14629 14629 F mono-rt :    at System.Globalization.GlobalizationMode.Settings..cctor()
04-15 12:42:53.745 14629 14629 F mono-rt :    Exception_EndOfInnerExceptionStack
04-15 12:42:53.745 14629 14629 F mono-rt :    at System.Globalization.GlobalizationMode.get_Invariant()
04-15 12:42:53.745 14629 14629 F mono-rt :    at System.Globalization.CultureData.CreateCultureWithInvariantData()
04-15 12:42:53.745 14629 14629 F mono-rt :    at System.Globalization.CultureData.get_Invariant()
04-15 12:42:53.745 14629 14629 F mono-rt :    at System.Globalization.CultureInfo..cctor()
04-15 12:42:53.745 14629 14629 F mono-rt :    Exception_EndOfInnerExceptionStack
04-15 12:42:53.745 14629 14629 F mono-rt :    Exception_EndOfInnerExceptionStack
04-15 12:42:53.745 14629 14629 F mono-rt :    at Java.Interop.TypeManager.RegisterType(String , Type )
04-15 12:42:53.745 14629 14629 F mono-rt :    at Android.Runtime.JNIEnvInit.RegisterJniNatives(IntPtr , Int32 , IntPtr , IntPtr , Int32 )
04-15 12:42:53.777  1656  4724 I ActivityManager: Process com.soundmindgames.gnollhackm (pid 14629) has died: fg  TOP (218,1595)
04-15 12:42:53.777  1266  1266 I Zygote  : Process 14629 exited cleanly (1)
04-15 12:42:53.777  1656  2076 I libprocessgroup: Successfully killed process cgroup uid 10593 pid 14629 in 0ms
04-15 12:42:55.580  1371  1470 E ANDR-PERF-UTIL: Failed to update node /proc/14629/sched_boost with value 0
04-15 12:42:55.580  1371  1470 E ANDR-PERF-OPTSHANDLER: can't reset task 14629
```

**Comment by janne-hmp** [comment]
This seems to be connected with .NET 9.0 Preview 3. Combination of .NET 9.0 Preview 2 and SkiaSharp 3.0 Preview 3.1 does work.

**Comment by janne-hmp** [comment]
We found that deleting obj and bin directories will make .NET 9.0 Preview 2 and SkiaSharp 3.0 Preview 3.1 work together in Release. However, .NET 9.0 Preview 3 seems to always crash in Release both with SkiaSharp 3.0 Preview 2.1 and 3.1

**Comment by janne-hmp** [comment]
Here's the latest log:

```
04-15 16:47:14.779 13737 13737 D nativeloader: Configuring clns-4 for other apk /data/app/~~O5RWJhgS6Zk8k0MBH8yrpA==/com.soundmindgames.gnollhackm-RXV8I9Pt69CLmHl5ap2PBg==/base.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~O5RWJhgS6Zk8k0MBH8yrpA==/com.soundmindgames.gnollhackm-RXV8I9Pt69CLmHl5ap2PBg==/lib/arm64:/data/app/~~O5RWJhgS6Zk8k0MBH8yrpA==/com.soundmindgames.gnollhackm-RXV8I9Pt69CLmHl5ap2PBg==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/com.soundmindgames.gnollhackm
04-15 16:47:14.795 13737 13737 V GraphicsEnvironment: Currently set values for:
04-15 16:47:14.795 13737 13737 V GraphicsEnvironment:   angle_gl_driver_selection_pkgs=[]
04-15 16:47:14.795 13737 13737 V GraphicsEnvironment:   angle_gl_driver_selection_values=[]
04-15 16:47:14.795 13737 13737 V GraphicsEnvironment: ANGLE GameManagerService for com.soundmindgames.gnollhackm: false
04-15 16:47:14.795 13737 13737 V GraphicsEnvironment: com.soundmindgames.gnollhackm is not listed in per-application setting
04-15 16:47:14.796 13737 13737 V GraphicsEnvironment: Updatable production driver is not supported on the device.
04-15 16:47:14.865 13737 13737 I DOTNET  : JNI_OnLoad: JNI_OnLoad in pal_jni.c
04-15 16:47:14.866 13737 13737 D DOTNET  : GetOptionalClassGRef: optional class com/android/org/conscrypt/OpenSSLEngineImpl was not found
04-15 16:47:14.879 13737 13737 W monodroid: Failed to create directory '/data/user/0/com.soundmindgames.gnollhackm/files/.__override__/arm64-v8a'. No such file or directory
04-15 16:47:14.879 13737 13737 W monodroid: Creating public update directory: `/data/user/0/com.soundmindgames.gnollhackm/files/.__override__/arm64-v8a`
04-15 16:47:14.881 13737 13737 W ames.gnollhackm: Attempt to remove non-JNI local reference
04-15 16:47:15.247 13737 13737 W monodroid-debug: Trying to initialize the debugger with options: --debugger-agent=transport=socket-fd,address=85,embedding=1
04-15 16:47:16.884 13737 13737 W monodroid: runtime args empty
04-15 16:47:16.888 13737 13737 W monodroid-assembly: Unable to open app library directory '/data/user/0/com.soundmindgames.gnollhackm/files/.__override__/arm64-v8a': No such file or directory
04-15 16:47:19.657  1656  3110 I Pageboost: IoRecord pid : 13737
04-15 16:47:19.725  1656  3110 I Pageboost: IoRecord pid : 13737, result_size : 19133
04-15 16:47:19.794  1656  3110 I Pageboost: memUsage collected : 128565 0 0 for com.soundmindgames.gnollhackm 13737
04-15 16:47:20.149   692   692 D io_stats: !@ Read_top(KB): ames.gnollhackm(13737) 131160 .android.chrome(15263) 752 system_server(1656) 680
04-15 16:47:20.831 13737 13737 W ames.gnollhackm: Attempt to remove non-JNI local reference
04-15 16:47:20.916 13737 13737 W monodroid-assembly: Shared library 'libSystem.Globalization.Native' not loaded, p/invoke 'GlobalizationNative_LoadICU' may fail
04-15 16:47:20.926 13737 13737 W monodroid-assembly: Shared library 'libSystem.Globalization.Native' not loaded, p/invoke 'GlobalizationNative_LoadICU' may fail
04-15 16:47:20.930 13737 13737 W monodroid-assembly: Shared library 'libSystem.Globalization.Native' not loaded, p/invoke 'GlobalizationNative_LoadICU' may fail
04-15 16:47:20.954 13737 13737 W monodroid-assembly: Shared library 'libSystem.Globalization.Native' not loaded, p/invoke 'GlobalizationNative_GetLocaleName' may fail
04-15 16:47:20.957 13737 13737 W monodroid-assembly: Shared library 'libSystem.Globalization.Native' not loaded, p/invoke 'GlobalizationNative_GetLocaleName' may fail
04-15 16:47:20.960 13737 13737 W monodroid-assembly: Shared library 'libSystem.Globalization.Native' not loaded, p/invoke 'GlobalizationNative_GetLocaleName' may fail
04-15 16:47:20.973 13737 13737 W ames.gnollhackm: Process terminated.
04-15 16:47:20.973 13737 13737 W ames.gnollhackm: Encountered infinite recursion while looking up resource 'Arg_DllNotFoundException' in System.Private.CoreLib. Verify the installation of .NET is complete and does not need repairing, and that the state of the process has not become corrupted.
04-15 16:47:20.973 13737 13737 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 13737 (ames.gnollhackm), pid 13737 (ames.gnollhackm)
04-15 16:47:21.032   747   747 I tombstoned: received crash request for pid 13737
04-15 16:47:21.033 13778 13778 I crash_dump64: performing dump of process 13737 (target tid = 13737)
04-15 16:47:21.382 13778 13778 F DEBUG   : pid: 13737, tid: 13737, name: ames.gnollhackm  >>> com.soundmindgames.gnollhackm <<<
04-15 16:47:21.436  1266  1266 I Zygote  : Process 13737 exited due to signal 6 (Aborted)
04-15 16:47:21.459  1656  3778 I ActivityManager: Process com.soundmindgames.gnollhackm (pid 13737) has died: fg  TOP (225,1750)
04-15 16:47:21.461  1656  2076 I libprocessgroup: Successfully killed process cgroup uid 10602 pid 13737 in 2ms
04-15 16:47:24.152   692   692 D io_stats: !@ Read_top(KB): crash_dump64(13778) 6308 loop31(824) 2588 ames.gnollhackm(13737) 2216
```

**Comment by janne-hmp** [comment]
And here's the log for .NET 9.0 Preview 3 crash (seems to be the same as the others):

```
04-15 20:38:07.568  4173  4324 D CompatibilityChangeReporter: Compat change id reported: 210923482; UID 10297; state: ENABLED
04-15 21:00:00.340  8000  8000 D CompatibilityChangeReporter: Compat change id reported: 210923482; UID 10306; state: ENABLED
04-15 21:38:18.385 32112 32112 D CompatibilityChangeReporter: Compat change id reported: 210923482; UID 10239; state: ENABLED
04-15 21:43:27.770   924   924 D Zygote  : Forked child process 10923
04-15 21:43:27.770  1412  1484 I ActivityManager: Start proc 10923:com.soundmindgames.gnollhackm/u0a307 for top-activity {com.soundmindgames.gnollhackm/crc6481ebf3e09068bf87.MainActivity}
04-15 21:43:27.778 10923 10923 I ames.gnollhackm: Using CollectorTypeCMC GC.
04-15 21:43:27.780 10923 10923 E ames.gnollhackm: Not starting debugger since process cannot load the jdwp agent.
04-15 21:43:27.783 10923 10923 D ActivityThread: setConscryptValidator
04-15 21:43:27.783 10923 10923 D ActivityThread: setConscryptValidator - put
04-15 21:43:27.788 10923 10923 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10307; state: ENABLED
04-15 21:43:27.788 10923 10923 D CompatibilityChangeReporter: Compat change id reported: 242716250; UID 10307; state: ENABLED
04-15 21:43:27.791 10923 10923 D nativeloader: Configuring clns-4 for other apk /data/app/~~0TIYkF9E1cLppmhZJ8PC2A==/com.soundmindgames.gnollhackm-8jKvxzZZD9yN9K2b_DDCfw==/base.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~0TIYkF9E1cLppmhZJ8PC2A==/com.soundmindgames.gnollhackm-8jKvxzZZD9yN9K2b_DDCfw==/lib/arm64:/data/app/~~0TIYkF9E1cLppmhZJ8PC2A==/com.soundmindgames.gnollhackm-8jKvxzZZD9yN9K2b_DDCfw==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/com.soundmindgames.gnollhackm
04-15 21:43:27.794  1412  1467 D PkgPredictorService-SecIpmManagerServiceImpl: onForegroundActivitiesChanged pid:10923 uid:10307
04-15 21:43:27.797 10923 10923 V GraphicsEnvironment: Currently set values for:
04-15 21:43:27.797 10923 10923 V GraphicsEnvironment:   angle_gl_driver_selection_pkgs=[]
04-15 21:43:27.797 10923 10923 V GraphicsEnvironment:   angle_gl_driver_selection_values=[]
04-15 21:43:27.797 10923 10923 V GraphicsEnvironment: ANGLE GameManagerService for com.soundmindgames.gnollhackm: false
04-15 21:43:27.797 10923 10923 V GraphicsEnvironment: com.soundmindgames.gnollhackm is not listed in per-application setting
04-15 21:43:27.797 10923 10923 V GraphicsEnvironment: App is not on the allowlist for updatable production driver.
04-15 21:43:27.803 10923 10923 I DOTNET  : JNI_OnLoad: JNI_OnLoad in pal_jni.c
04-15 21:43:27.803 10923 10923 D DOTNET  : GetOptionalClassGRef: optional class com/android/org/conscrypt/OpenSSLEngineImpl was not found
04-15 21:43:27.872 10923 10923 W monodroid-assembly: Shared library 'libSystem.Globalization.Native' not loaded, p/invoke 'GlobalizationNative_LoadICU' may fail
04-15 21:43:27.873 10923 10923 W monodroid-assembly: Shared library 'libSystem.Globalization.Native' not loaded, p/invoke 'GlobalizationNative_LoadICU' may fail
04-15 21:43:27.873 10923 10923 W monodroid-assembly: Shared library 'libSystem.Globalization.Native' not loaded, p/invoke 'GlobalizationNative_LoadICU' may fail
04-15 21:43:27.882 10923 10923 F mono-rt : [ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: TypeInitialization_Type, System.Globalization.CompareInfo
04-15 21:43:27.882 10923 10923 F mono-rt :  ---> System.TypeInitializationException: TypeInitialization_Type, System.Globalization.CultureInfo
04-15 21:43:27.882 10923 10923 F mono-rt :  ---> System.TypeInitializationException: TypeInitialization_Type, Settings
04-15 21:43:27.882 10923 10923 F mono-rt :  ---> System.DllNotFoundException: libSystem.Globalization.Native
04-15 21:43:27.882 10923 10923 F mono-rt :    at System.Globalization.GlobalizationMode.LoadICU()
04-15 21:43:27.882 10923 10923 F mono-rt :    at System.Globalization.GlobalizationMode.Settings..cctor()
04-15 21:43:27.882 10923 10923 F mono-rt :    Exception_EndOfInnerExceptionStack
04-15 21:43:27.882 10923 10923 F mono-rt :    at System.Globalization.GlobalizationMode.get_Invariant()
04-15 21:43:27.882 10923 10923 F mono-rt :    at System.Globalization.CultureData.CreateCultureWithInvariantData()
04-15 21:43:27.882 10923 10923 F mono-rt :    at System.Globalization.CultureData.get_Invariant()
04-15 21:43:27.882 10923 10923 F mono-rt :    at System.Globalization.CultureInfo..cctor()
04-15 21:43:27.882 10923 10923 F mono-rt :    Exception_EndOfInnerExceptionStack
04-15 21:43:27.882 10923 10923 F mono-rt :    Exception_EndOfInnerExceptionStack
04-15 21:43:27.882 10923 10923 F mono-rt :    at Java.Interop.TypeManager.RegisterType(String , Type )
04-15 21:43:27.882 10923 10923 F mono-rt :    at Android.Runtime.JNIEnvInit.RegisterJniNatives(IntPtr , Int32 , IntPtr , IntPtr , Int32 )
04-15 21:43:27.918  1412  1993 I ActivityManager: Process com.soundmindgames.gnollhackm (pid 10923) has died: fg  TOP (671,3230)
04-15 21:43:27.918  1412  1486 I libprocessgroup: Successfully killed process cgroup uid 10307 pid 10923 in 0ms
04-15 21:43:27.918   924   924 I Zygote  : Process 10923 exited cleanly (1)

```

**Comment by mattleibow** [comment]
This stack trace looks to be the new things in the Android for .NET SDK, so could you open this issue in the dotnet/runtime repo?

This stack is some sort of globalization (probably ICU related) in the .NET 9 SDK.

**Comment by janne-hmp** [comment]
Sure, just reported this as https://github.com/dotnet/runtime/issues/101107

**Comment by ivanpovazan** [comment]
Feel free to close this, as we are tracking it on the dotnet/runtime side.

**Comment by janne-hmp** [comment]
Followed on dotnet/runtime side.
