### ISSUE TITLE
ZipArchive is not functioning in Blazor WebAssembly when using System.IO.Compression.ZipArchive and SkiaSharp v3.118.0-preview.1.2 in .NET 9.0.

### ISSUE THREAD

**Issue by pandi123** [mono/SkiaSharp#3067]
### Description

We are experiencing an issue with the System.IO.Compression.ZipArchive and SkiaSharp package v3.118.0-preview.1.2 in our Blazor WebAssembly .NET 9.0 project. The problem began after we added the following line in our .csproj file:
![image](https://github.com/user-attachments/assets/8b552511-2211-4205-ac2f-dfd2404af650)

This issue does not occur when using the SkiaSharp package v2.88.8 or checking .NET 8.0 working fine. I have attached a sample project and a screenshot of the issue for your reference.

Platform: Blazor wasm
Visual Studio version: 2022
.NET version : .NET9
SkiaSharp version : v3.118.0-preview.1.2

### Code
```razor
@page "/"
@using System.IO.Compression;
@using System.Xml.Linq;
@inject IJSRuntime JS;


<button @onclick="ZipArchive">Download ZIP</button>


@code {
    public async void ZipArchive()
    {
        using (MemoryStream zipStream = new MemoryStream())
        {
            using (ZipArchive archive = new ZipArchive(zipStream, ZipArchiveMode.Create, true))
            {
                ZipArchiveEntry entry = archive.CreateEntry("Sample.xml");
                using (Stream entryStream = entry.Open())
                {
                    XDocument xmlDocument = new XDocument(
                        new XElement("Root",
                            new XElement("Child", "Content")
                        )
                    );
                    xmlDocument.Save(entryStream);
                }
            }
            zipStream.Position = 0;
            await JS.InvokeVoidAsync("downloadFileFromByteArray", "SampleArchive.zip", zipStream.ToArray());
        }
    }
}
```
### Expected Behavior

The program should run without any exceptions in blazor wasm while using System.IO.Compression.ZipArchive and SkiaSharp package v3.118.0-preview.1.2

### Actual Behavior

 
Aborted(Assertion failed: native function `stackRestore` called after runtime exit (use NO_EXIT_RUNTIME to keep it alive after main() exits))
The thread '.NET TP Worker' (33996) has exited with code 0 (0x0).
The thread '.NET TP Worker' (42984) has exited with code 0 (0x0).
Uncaught RuntimeError RuntimeError: unreachable
    at $__trap (wasm/022f640e.wat:3678318:1)
    at ___trap (localhost꞉7023/_framework/dotnet.native.krq9w4nbeb.js:11275:54)
    at abort (localhost꞉7023/_framework/dotnet.native.krq9w4nbeb.js:775:5)
    at assert (localhost꞉7023/_framework/dotnet.native.krq9w4nbeb.js:468:5)
    at <anonymous> (localhost꞉7023/_framework/dotnet.native.krq9w4nbeb.js:808:5)
    at <anonymous> (d:\Net9\ZipArchive3.118.0-preview.1.2\ZipArchive3.118.0-preview.1.2\wwwroot\_framework\https:\raw.githubusercontent.com\dotnet\runtime\9d5a6a9aa463d6d10b0b0ba6d5982cc82f363dc3\src\mono\browser\runtime\invoke-cs.ts:328:20)
    at beginInvokeDotNetFromJS (localhost꞉7023/_framework/blazor.webassembly.js:1:43656)
    at invokeDotNetMethodAsync (localhost꞉7023/_framework/blazor.webassembly.js:1:3978)
    at invokeMethodAsync (localhost꞉7023/_framework/blazor.webassembly.js:1:5486)
    at <anonymous> (localhost꞉7023/_framework/blazor.webassembly.js:1:13036)
    at R (localhost꞉7023/_framework/blazor.webassembly.js:1:13214)
    at <anonymous> (localhost꞉7023/_framework/blazor.webassembly.js:1:52854)
    at invokeWhenHeapUnlocked (localhost꞉7023/_framework/blazor.webassembly.js:1:44875)
    at <anonymous> (localhost꞉7023/_framework/blazor.webassembly.js:1:52817)
    at R (localhost꞉7023/_framework/blazor.webassembly.js:1:52844)
    at I (localhost꞉7023/_framework/blazor.webassembly.js:1:13005)
    at dispatchGlobalEventToAllElements (localhost꞉7023/_framework/blazor.webassembly.js:1:15626)
    at onGlobalEvent (localhost꞉7023/_framework/blazor.webassembly.js:1:14835)

### Version of SkiaSharp

3.118.0-preview.1 (Next Preview)

### Last Known Good Version of SkiaSharp

2.88.8 (Previous)

### IDE / Editor

Visual Studio (Windows)

### Platform / Operating System

Windows

### Platform / Operating System Version

Window11

### Devices

Visual studio v2022

### Issue reproducing sample
[ZipArchive3.118.0-preview.1.2.zip](https://github.com/user-attachments/files/17748587/ZipArchive3.118.0-preview.1.2.zip)

### Working sample
[ZipArchive 2.88.8.zip](https://github.com/user-attachments/files/17748588/ZipArchive.2.88.8.zip)

### Relevant Log Output

![image (5)](https://github.com/user-attachments/assets/469f018f-dcfa-4aad-a27a-1d3728c115d4)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mattleibow** [comment]
This may be fixed with https://github.com/mono/SkiaSharp/pull/3064

Can you try the nightly on the preview feed: `3.118.0-nightly.27`

```
https://aka.ms/skiasharp-eap/index.json
```

Let me know if this fixes it and I will push out the 3.x release.
