### ISSUE TITLE
[BUG] The version of the native libSkiaSharp library (116.0) is incompatible with this version of SkiaSharp.

### ISSUE THREAD

**Issue by bautistavirchar** [mono/SkiaSharp#3117]
### Description

The version of the native libSkiaSharp library (116.0) is incompatible with this version of SkiaSharp. Supported versions of the native libSkiaSharp library are in the range [88.1, 89.0)

### Code

```
Stream GenerateQr(string text)
{
    using var generator = new QRCodeGenerator();

    // Generate QrCode
    var qr = generator.CreateQrCode(text, ECCLevel.L);

    // Render to canvas
    var info = new SKImageInfo(512, 512);
    using var surface = SKSurface.Create(info);
    var canvas = surface.Canvas;
    canvas.Render(qr, info.Width, info.Height);

    // Output to Stream -> File
    using var image = surface.Snapshot();
    using var data = image.Encode(SKEncodedImageFormat.Png, 100);

    var img = SKImage.FromPixels(image.PeekPixels());
    // encode the image (defaults to PNG)
    var encoded = image.Encode();
    // get a stream over the encoded data
    return encoded.AsStream();

}
```

### Expected Behavior

**WORKING VERSION 2.88.9**

`<PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.88.9" />`

### Version of SkiaSharp

3.116.0 (Current)

### Last Known Good Version of SkiaSharp

2.88.9 (Previous)

### IDE / Editor

Visual Studio (Windows)

### Platform / Operating System

Linux

### Platform / Operating System Version

Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm

### Relevant Log Output

```shell
System.TypeInitializationException: The type initializer for 'SkiaSharp.SKObject' threw an exception.
       ---> System.InvalidOperationException: The version of the native libSkiaSharp library (116.0) is incompatible with this version of SkiaSharp. Supported versions of the native libSkiaSharp library are in the range [88.1, 89.0).
         at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Version minSupported, Version current, Boolean throwIfIncompatible)
         at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Boolean throwIfIncompatible)
         at SkiaSharp.SKObject..cctor()
         --- End of inner exception stack trace ---
         at SkiaSharp.SKObject..ctor(IntPtr handle, Boolean owns)
         at SkiaSharp.SKSurface..ctor(IntPtr h, Boolean owns)
         at SkiaSharp.SKSurface.GetObject(IntPtr handle)
         at SkiaSharp.SKSurface.Create(SKImageInfo info, Int32 rowBytes, SKSurfaceProperties props)
         at SkiaSharp.SKSurface.Create(SKImageInfo info)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mattleibow** [comment]
Did you update all the SkiaSharp nugets to the same version?

**Comment by bautistavirchar** [comment]
@mattleibow 

only this library SkiaSharp.NativeAssets.Linux.NoDependencies which the working version is 2.88.9

**Comment by elr0berto** [comment]
Got same problem. solved by downgrading to 2.88.9

**Comment by penihel** [comment]
i have the same problem

**Comment by gktval** [comment]
Same issue. I have SkiaSharp and SkiaSharp.View.Blazor. The nugets in the solution were all updated to 3.116.1. The solution was to clean the solution and rebuild.

**Comment by danilobreda** [comment]
116 is bugged. only 88 and 89 is working.
The check occurs on SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible

**Comment by vadimart92** [comment]
Seems like problem is only SkiaSharp.NativeAssets.Linux.NoDependencies:
```
/runtimes/linux-x64/native$ readelf -d libSkiaSharp.so

Dynamic section at offset 0x8c6a60 contains 33 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libfontconfig.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
 0x000000000000000e (SONAME)             Library soname: [libSkiaSharp.so.88.1.0] <----
```
SkiaSharp.NativeAssets.Linux works
```
/runtimes/linux-x64/native$ readelf -d libSkiaSharp.so

Dynamic section at offset 0x891a30 contains 33 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libfontconfig.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
 0x000000000000000e (SONAME)             Library soname: [libSkiaSharp.so.118.0.0] <----
```

**Comment by TheFerrango** [comment]
The same problem happens under a Windows OS when the application is being served via IIS

**Comment by vikher** [comment]
@mattleibow  I’m working on a .NET MAUI app with `<MauiVersion>9.0.50</MauiVersion>`. The app targets both Android and iOS. When using the following SkiaSharp packages, everything works fine on both platforms:

```
<PackageReference Include="SkiaSharp" Version="2.88.9" />
<PackageReference Include="SkiaSharp.Views" Version="2.88.9" />
<PackageReference Include="SkiaSharp.Views.Maui.Controls" Version="2.88.9" />
```

However, when I update these packages to the latest versions:

```
<PackageReference Include="SkiaSharp" Version="3.116.1" />
<PackageReference Include="SkiaSharp.Views" Version="3.116.1" />
<PackageReference Include="SkiaSharp.Views.Maui.Controls" Version="3.116.1" />
```

The app continues to work on Android but fails on iOS with the following exception:

```
System.TypeInitializationException: The type initializer for 'SkiaSharp.SKObject' threw an exception.
 ---> System.InvalidOperationException: The version of the native libSkiaSharp library (88.1) is incompatible with this version of SkiaSharp. Supported versions of the native libSkiaSharp library are in the range [116.0, 117.0).
   at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Version minSupported, Version current, Boolean throwIfIncompatible)
   at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Boolean throwIfIncompatible)
   at SkiaSharp.SKObject..cctor()
   --- End of inner exception stack trace ---
   at SkiaSharp.SKSurface..ctor(IntPtr h, Boolean owns)
   at SkiaSharp.SKSurface.GetObject(IntPtr handle)
   at SkiaSharp.SKSurface.Create(SKImageInfo info, IntPtr pixels, Int32 rowBytes, SKSurfaceReleaseDelegate releaseProc, Object context, SKSurfaceProperties props)
   at SkiaSharp.SKSurface.Create(SKImageInfo info, IntPtr pixels, Int32 rowBytes)
   at SkiaSharp.Views.iOS.SKCGSurfaceFactory.CreateSurface(CGRect contentsBounds, NFloat scale, SKImageInfo& info)
   at SkiaSharp.Views.iOS.SKCanvasView.Draw(CGRect rect)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at Mobile.Program.Main(String[] args) in /Users/victorsanchez/Mobile-Maui/Mobile/Platforms/iOS/Program.cs:line 12
```

It seems the native `libSkiaSharp` library on iOS remains at version 88.1, which is incompatible with SkiaSharp 3.116.1 (expecting 116.0–117.0). This issue doesn’t occur on Android. Has anyone encountered this with .NET MAUI 9.0.50 on iOS, or is there a known fix to ensure the correct native library version is used?

**Comment by mattleibow** [comment]
Could you attach a binlog?

If you clean and rebuild, does it go away? What about building on the CLI?

**Comment by ladeak** [comment]
@bautistavirchar could you confirm if this is going to be part of an upcoming release, or closed with a different reason?

**Comment by jacobilsoe** [comment]
> [@mattleibow](https://github.com/mattleibow) I’m working on a .NET MAUI app with `<MauiVersion>9.0.50</MauiVersion>`. The app targets both Android and iOS. When using the following SkiaSharp packages, everything works fine on both platforms:
> 
> ```
> <PackageReference Include="SkiaSharp" Version="2.88.9" />
> <PackageReference Include="SkiaSharp.Views" Version="2.88.9" />
> <PackageReference Include="SkiaSharp.Views.Maui.Controls" Version="2.88.9" />
> ```
> 
> However, when I update these packages to the latest versions:
> 
> ```
> <PackageReference Include="SkiaSharp" Version="3.116.1" />
> <PackageReference Include="SkiaSharp.Views" Version="3.116.1" />
> <PackageReference Include="SkiaSharp.Views.Maui.Controls" Version="3.116.1" />
> ```
> 
> The app continues to work on Android but fails on iOS with the following exception:
> 
> ```
> System.TypeInitializationException: The type initializer for 'SkiaSharp.SKObject' threw an exception.
>  ---> System.InvalidOperationException: The version of the native libSkiaSharp library (88.1) is incompatible with this version of SkiaSharp. Supported versions of the native libSkiaSharp library are in the range [116.0, 117.0).
>    at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Version minSupported, Version current, Boolean throwIfIncompatible)
>    at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Boolean throwIfIncompatible)
>    at SkiaSharp.SKObject..cctor()
>    --- End of inner exception stack trace ---
>    at SkiaSharp.SKSurface..ctor(IntPtr h, Boolean owns)
>    at SkiaSharp.SKSurface.GetObject(IntPtr handle)
>    at SkiaSharp.SKSurface.Create(SKImageInfo info, IntPtr pixels, Int32 rowBytes, SKSurfaceReleaseDelegate releaseProc, Object context, SKSurfaceProperties props)
>    at SkiaSharp.SKSurface.Create(SKImageInfo info, IntPtr pixels, Int32 rowBytes)
>    at SkiaSharp.Views.iOS.SKCGSurfaceFactory.CreateSurface(CGRect contentsBounds, NFloat scale, SKImageInfo& info)
>    at SkiaSharp.Views.iOS.SKCanvasView.Draw(CGRect rect)
>    at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
>    at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
>    at Mobile.Program.Main(String[] args) in /Users/victorsanchez/Mobile-Maui/Mobile/Platforms/iOS/Program.cs:line 12
> ```
> 
> It seems the native `libSkiaSharp` library on iOS remains at version 88.1, which is incompatible with SkiaSharp 3.116.1 (expecting 116.0–117.0). This issue doesn’t occur on Android. Has anyone encountered this with .NET MAUI 9.0.50 on iOS, or is there a known fix to ensure the correct native library version is used?

I have exactly the same issue. Works on Android but not iOS.

**Comment by gktval** [comment]
I mentioned above to clean and rebuild. But I rolled back yesterday after testing 3.118.2 to 2.88.9 and had a similar issue. It kept trying to reference 3.118. I had to delete the bin/obj folders to make finally get rid of all references in iOS.

**Comment by jacobilsoe** [comment]
Deleting those folders helped. Thanks.

**Comment by lilleyd** [comment]
I am also facing this issue, Is there a new release soon ?

**Comment by mattleibow** [comment]
Did you delete the bin and obj? If that is helping, this may be an issue in the iOS build so please open an issue with repro steps for the iOS team:  http://github.com/dotnet/macios

**Comment by penihel** [comment]
i still have the same problem yet, i have deleted the bin and obj, the problem continues

**Comment by lilleyd** [comment]
I also have tired that and the Problem Remained

**Comment by slackerbob** [comment]
I can confirm this is still happening with 3.116.1 and should not be closed.

Downgrading to 2.88.9 is the only fix I've found, but isn't sustainable long-term.

**Comment by mattleibow** [comment]
Can you try the latest preview as well as attach a sample project repo?

**Comment by RajeevRameshHNR** [comment]
> [@mattleibow](https://github.com/mattleibow) I’m working on a .NET MAUI app with `<MauiVersion>9.0.50</MauiVersion>`. The app targets both Android and iOS. When using the following SkiaSharp packages, everything works fine on both platforms:
> 
> ```
> <PackageReference Include="SkiaSharp" Version="2.88.9" />
> <PackageReference Include="SkiaSharp.Views" Version="2.88.9" />
> <PackageReference Include="SkiaSharp.Views.Maui.Controls" Version="2.88.9" />
> ```
> 
> However, when I update these packages to the latest versions:
> 
> ```
> <PackageReference Include="SkiaSharp" Version="3.116.1" />
> <PackageReference Include="SkiaSharp.Views" Version="3.116.1" />
> <PackageReference Include="SkiaSharp.Views.Maui.Controls" Version="3.116.1" />
> ```
> 
> The app continues to work on Android but fails on iOS with the following exception:
> 
> ```
> System.TypeInitializationException: The type initializer for 'SkiaSharp.SKObject' threw an exception.
>  ---> System.InvalidOperationException: The version of the native libSkiaSharp library (88.1) is incompatible with this version of SkiaSharp. Supported versions of the native libSkiaSharp library are in the range [116.0, 117.0).
>    at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Version minSupported, Version current, Boolean throwIfIncompatible)
>    at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Boolean throwIfIncompatible)
>    at SkiaSharp.SKObject..cctor()
>    --- End of inner exception stack trace ---
>    at SkiaSharp.SKSurface..ctor(IntPtr h, Boolean owns)
>    at SkiaSharp.SKSurface.GetObject(IntPtr handle)
>    at SkiaSharp.SKSurface.Create(SKImageInfo info, IntPtr pixels, Int32 rowBytes, SKSurfaceReleaseDelegate releaseProc, Object context, SKSurfaceProperties props)
>    at SkiaSharp.SKSurface.Create(SKImageInfo info, IntPtr pixels, Int32 rowBytes)
>    at SkiaSharp.Views.iOS.SKCGSurfaceFactory.CreateSurface(CGRect contentsBounds, NFloat scale, SKImageInfo& info)
>    at SkiaSharp.Views.iOS.SKCanvasView.Draw(CGRect rect)
>    at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
>    at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
>    at Mobile.Program.Main(String[] args) in /Users/victorsanchez/Mobile-Maui/Mobile/Platforms/iOS/Program.cs:line 12
> ```
> 
> It seems the native `libSkiaSharp` library on iOS remains at version 88.1, which is incompatible with SkiaSharp 3.116.1 (expecting 116.0–117.0). This issue doesn’t occur on Android. Has anyone encountered this with .NET MAUI 9.0.50 on iOS, or is there a known fix to ensure the correct native library version is used?

I have the similar issue with upgrading the version.
The version of the native libSkiaSharp library (88.1) is incompatible with this version of SkiaSharp. Supported versions of the native libSkiaSharp library are in the range [118.0, 119.0).

**Comment by mattleibow** [comment]
Can you attach a binlog of the build? Did you try removing the app from the device?

Are you building on mac or using pair to Mac or the iPhone plugged into the windows machine?

**Comment by FreakyAli** [comment]
@vikher  I can still see this with versions you mentioned, did you ever find a fix for it?

**Comment by spudnut2000** [comment]
> For people ending up here googling: I encountered this issue when I installed `Avalonia.Svg.Skia 11.3.0` package into desktop app on linux, the workaround is installing `SkiaSharp.NativeAssets.Linux 3.116.1` to force the compatible version of `libSkiaSharp`.
> 
> ```
> System.TypeInitializationException: The type initializer for 'SkiaSharp.SKFontManager' threw an exception.
>  ---> System.TypeInitializationException: The type initializer for 'SkiaSharp.SKObject' threw an exception.
>  ---> System.InvalidOperationException: The version of the native libSkiaSharp library (88.1) is incompatible with this version of SkiaSharp. Supported versions of the native libSkiaSharp library are in the range [116.0, 117.0).
>    at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Version minSupported, Version current, Boolean throwIfIncompatible)
>    at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Boolean throwIfIncompatible)
>    at SkiaSharp.SKObject..cctor()
>    --- End of inner exception stack trace ---
>    at SkiaSharp.SKObject..ctor(IntPtr handle, Boolean owns)
>    at SkiaSharp.SKFontManager..ctor(IntPtr handle, Boolean owns)
>    at SkiaSharp.SKFontManager.SKFontManagerStatic..ctor(IntPtr x)
>    at SkiaSharp.SKFontManager..cctor()
>    --- End of inner exception stack trace ---
>    at SkiaSharp.SKFontManager.get_Default()
>    at Avalonia.Skia.FontManagerImpl..ctor()
>    at Avalonia.Skia.SkiaPlatform.Initialize(SkiaOptions options)
>    at Avalonia.SkiaApplicationExtensions.<>c.<UseSkia>b__0_0()
>    at Avalonia.AppBuilder.SetupUnsafe()
>    at Avalonia.AppBuilder.Setup()
>    at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime)
>    at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, Action`1 lifetimeBuilder)
>    at DiPi.Speaker.Program.Main(String[] args) in /home/dipi/Documents/dotnet/DiPi.StreamApps/DiPi.Speaker/Program.cs:line 14
> ```

This was the solution for me as well. Thank you.

**Comment by PhasonMatrix** [comment]
> For people ending up here googling: I encountered this issue when I installed `Avalonia.Svg.Skia 11.3.0` package into desktop app on linux, the workaround is installing `SkiaSharp.NativeAssets.Linux 3.116.1` to force the compatible version of `libSkiaSharp`.
> 
> ```
> System.TypeInitializationException: The type initializer for 'SkiaSharp.SKFontManager' threw an exception.
>  ---> System.TypeInitializationException: The type initializer for 'SkiaSharp.SKObject' threw an exception.
>  ---> System.InvalidOperationException: The version of the native libSkiaSharp library (88.1) is incompatible with this version of SkiaSharp. Supported versions of the native libSkiaSharp library are in the range [116.0, 117.0).
>    at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Version minSupported, Version current, Boolean throwIfIncompatible)
>    at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Boolean throwIfIncompatible)
>    at SkiaSharp.SKObject..cctor()
>    --- End of inner exception stack trace ---
>    at SkiaSharp.SKObject..ctor(IntPtr handle, Boolean owns)
>    at SkiaSharp.SKFontManager..ctor(IntPtr handle, Boolean owns)
>    at SkiaSharp.SKFontManager.SKFontManagerStatic..ctor(IntPtr x)
>    at SkiaSharp.SKFontManager..cctor()
>    --- End of inner exception stack trace ---
>    at SkiaSharp.SKFontManager.get_Default()
>    at Avalonia.Skia.FontManagerImpl..ctor()
>    at Avalonia.Skia.SkiaPlatform.Initialize(SkiaOptions options)
>    at Avalonia.SkiaApplicationExtensions.<>c.<UseSkia>b__0_0()
>    at Avalonia.AppBuilder.SetupUnsafe()
>    at Avalonia.AppBuilder.Setup()
>    at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime)
>    at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, Action`1 lifetimeBuilder)
>    at DiPi.Speaker.Program.Main(String[] args) in /home/dipi/Documents/dotnet/DiPi.StreamApps/DiPi.Speaker/Program.cs:line 14
> ```

This fixed the problem for me too. Thank you.
