### ISSUE TITLE
[BUG] Unable to find an entry point named 'sk_region_op2' in shared library 'libSkiaSharp'

### ISSUE THREAD

**Issue by WouterDevExperts** [mono/SkiaSharp#3119]
### Description

I use the FreeSpire.XLS library version 14.2.0 in a Docker Linux environment.
When I create a new workbook ( var workbook = new Workbook(); ) I get this error:

System.TypeInitializationException: The type initializer for 'Spire.Xls.Core.Spreadsheet.XlsPageSetupBase' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'spr娮' threw an exception.
 ---> System.EntryPointNotFoundException: Unable to find an entry point named 'sk_region_op2' in shared library 'libSkiaSharp'.
   at SkiaSharp.SkiaApi.sk_region_op2(IntPtr r, IntPtr src, SKRegionOperation op)
   at SkiaSharp.SKRegion.Op(SKRegion region, SKRegionOperation op)
   at spr揼.幥()
   at spr揼.庚(spr憀 A_0)
   at spr揼.帰(spr눾 A_0)
   at spr憀.惡()
   at spr憀.幥(spr눾 A_0)
   at spr꺹.帰(spr憀 A_0)
   at spr憀.態()
   at spr娮..cctor()
   --- End of inner exception stack trace ---
   at Spire.Xls.Core.Spreadsheet.XlsPageSetupBase.PaperSizeEntry..ctor(Double width, Double height, MeasureUnits units)
   at Spire.Xls.Core.Spreadsheet.XlsPageSetupBase..cctor()
   --- End of inner exception stack trace ---
   at Spire.Xls.Core.Spreadsheet.XlsPageSetupBase..ctor(Object A_0)
   at Spire.Xls.Core.Spreadsheet.XlsPageSetup..ctor(Object A_0)
   at Spire.Xls.PageSetup..ctor(Object A_0)
   at Spire.Xls.Core.Spreadsheet.XlsWorksheet.InitializeCollections()
   at Spire.Xls.Core.Spreadsheet.XlsWorksheetBase..ctor(Object A_0)
   at Spire.Xls.Core.Spreadsheet.XlsWorksheet..ctor(Object A_0)
   at Spire.Xls.Worksheet..ctor(Object A_0)
   at Spire.Xls.Core.Spreadsheet.Collections.XlsWorksheetsCollection.Add(String sheetName)
   at Spire.Xls.Core.Spreadsheet.XlsWorkbook.帰(Int32 A_0)
   at Spire.Xls.Core.Spreadsheet.XlsWorkbook..ctor(Object A_0)
   at Spire.Xls.Workbook..ctor()

It works fine in the previous version: SkiaSharp.NativeAssets.Linux.NoDependencies version 2.88.9

### Code

using Spire.Xls;

using var workbook = new Workbook();

### Expected Behavior

The Excel work being created without an error like in version 2.88.9

### Actual Behavior

Since version 3.116.1 the error occurs.

### Version of SkiaSharp

3.116.0 (Current)

### Last Known Good Version of SkiaSharp

2.88.9 (Previous)

### IDE / Editor

Visual Studio (Windows)

### Platform / Operating System

Linux

### Platform / Operating System Version

Docker image:
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base

### Devices

All browsers (project is a Web API)

### Relevant Log Output

```shell
System.TypeInitializationException: The type initializer for 'Spire.Xls.Core.Spreadsheet.XlsPageSetupBase' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'spr娮' threw an exception.
 ---> System.EntryPointNotFoundException: Unable to find an entry point named 'sk_region_op2' in shared library 'libSkiaSharp'.
   at SkiaSharp.SkiaApi.sk_region_op2(IntPtr r, IntPtr src, SKRegionOperation op)
   at SkiaSharp.SKRegion.Op(SKRegion region, SKRegionOperation op)
   at spr揼.幥()
   at spr揼.庚(spr憀 A_0)
   at spr揼.帰(spr눾 A_0)
   at spr憀.惡()
   at spr憀.幥(spr눾 A_0)
   at spr꺹.帰(spr憀 A_0)
   at spr憀.態()
   at spr娮..cctor()
   --- End of inner exception stack trace ---
   at Spire.Xls.Core.Spreadsheet.XlsPageSetupBase.PaperSizeEntry..ctor(Double width, Double height, MeasureUnits units)
   at Spire.Xls.Core.Spreadsheet.XlsPageSetupBase..cctor()
   --- End of inner exception stack trace ---
   at Spire.Xls.Core.Spreadsheet.XlsPageSetupBase..ctor(Object A_0)
   at Spire.Xls.Core.Spreadsheet.XlsPageSetup..ctor(Object A_0)
   at Spire.Xls.PageSetup..ctor(Object A_0)
   at Spire.Xls.Core.Spreadsheet.XlsWorksheet.InitializeCollections()
   at Spire.Xls.Core.Spreadsheet.XlsWorksheetBase..ctor(Object A_0)
   at Spire.Xls.Core.Spreadsheet.XlsWorksheet..ctor(Object A_0)
   at Spire.Xls.Worksheet..ctor(Object A_0)
   at Spire.Xls.Core.Spreadsheet.Collections.XlsWorksheetsCollection.Add(String sheetName)
   at Spire.Xls.Core.Spreadsheet.XlsWorkbook.帰(Int32 A_0)
   at Spire.Xls.Core.Spreadsheet.XlsWorkbook..ctor(Object A_0)
   at Spire.Xls.Workbook..ctor()
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mattleibow** [comment]
Are you able to attach a repro project so we can investigate?

Also, make sure both your skia and native assets are the same version.

**Comment by WouterDevExperts** [comment]
Sure, here you go: https://github.com/WouterDevExperts/SkiaSharpBug

**Comment by francorobles** [comment]
Same thing is happening to my project. Below are my references
<PackageReference Include="FreeSpire.XLS" Version="14.2.0" />
<PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="3.116.1" />

**Comment by molesmoke** [comment]
Spire.Xls looks like it uses a much older version of Skia - I'd probably not expect the sample to work.
https://www.nuget.org/packages/freeSpire.xls/#dependencies-body-tab
