### ISSUE TITLE
Failed to create EGL surface

### ISSUE THREAD

**Issue by bugadani** [mono/SkiaSharp#338]
Hi!

So I'm not sure if this is a bug somewhere in Skia/Skiasharp or in windows 10 mobile, but today I was hit with a "Failed to create EGL surface" exception, out of nowhere. Unfortunately the phone wasn't attached to the debugger so only my custom logging caught the exception, with the following trace:

   at SkiaSharp.Views.UWP.GlesContext.CreateSurface(SwapChainPanel panel, Int32 rbWidth, Int32 rbHeight, GlesBackingOption backingOption, GlesMultisampling multisampling, GlesRenderTarget renderTarget)
   at SkiaSharp.Views.UWP.GlesContext.SetSurface(SwapChainPanel swapChainPanel, Int32 rbWidth, Int32 rbHeight, GlesBackingOption backingOption, GlesMultisampling multisampling, GlesRenderTarget renderTarget)
   at SkiaSharp.Views.UWP.AngleSwapChainPanel.UpdateBuffers()
   at SkiaSharp.Views.UWP.AngleSwapChainPanel.RenderFrame()
   at SkiaSharp.Views.UWP.AngleSwapChainPanel.Invalidate()
   at SkiaSharp.Views.UWP.AngleSwapChainPanel.CalculateBufferSize()
   at SkiaSharp.Views.UWP.AngleSwapChainPanel.OnCompositionChanged(SwapChainPanel sender, Object args)

I'm not sure how this can happen and what can be done to avoid it happening again in the future.
The phone is a Lumia 950XL running W10M build 10.0.15228.0 (feature2) and the issue can't be reproduced by any consistent way I'm aware of.

**Comment by mattleibow** [comment]
Do you know what version of SkiaSharp was this on?

**Comment by bugadani** [comment]
Yes, 1.58.0
