### ISSUE TITLE
NullReferenceException when creating SkCanvas backed by a WriteableBitmap

### ISSUE THREAD

**Issue by mgnslndh** [mono/SkiaSharp#39]
The [following code](https://github.com/impsnldavid/skiasharpwpfextensions/blob/master/src/Imp.SkiaSharpWpfExtensions/SkiaControl.cs#L72-L92) from https://github.com/impsnldavid/skiasharpwpfextensions fails randomly with a `NullReferenceException` when the `SkCanvas` is constructed.

The member variable `_bitmap` is a [WriteableBitmap](https://msdn.microsoft.com/en-us/library/system.windows.media.imaging.writeablebitmap(v=vs.110).aspx)

```
		protected override void OnRender(DrawingContext dc)
		{
			if (_bitmap == null)
				return;

			_bitmap.Lock();

			using (var surface = SKSurface.Create((int)_bitmap.Width, (int)_bitmap.Height, 
				SKColorType.N_32, SKAlphaType.Premul, _bitmap.BackBuffer, _bitmap.BackBufferStride))
			{
				if (IsClearCanvas)
					surface.Canvas.Clear(_canvasClearColor);

				Draw(surface.Canvas, (int)_bitmap.Width, (int)_bitmap.Height);
			}

			_bitmap.AddDirtyRect(new Int32Rect(0, 0, (int)_bitmap.Width, (int)_bitmap.Height));
			_bitmap.Unlock();

			dc.DrawImage(_bitmap, new Rect(0, 0, ActualWidth, ActualHeight));
                }
```

The exception randomly occurs on calls to [surface.Canvas.Clear(_canvasClearColor);](https://github.com/impsnldavid/skiasharpwpfextensions/blob/master/src/Imp.SkiaSharpWpfExtensions/SkiaControl.cs#L83)

The `NullReferenceException` is wrapped in a `TargetInvocationException`. Here are the call stacks:

## Inner NullReferenceException Stack Trace

```
   at SkiaSharp.SKObject.RegisterHandle(IntPtr handle, SKObject instance)
   at SkiaSharp.SKCanvas..ctor(IntPtr handle)
```

## TargetInvocationException Stack Trace
```
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at SkiaSharp.SKObject.GetObject[TSkiaObject](IntPtr handle)
   at SkiaSharp.WpfExtensions.SkiaControl.OnRender(DrawingContext dc) in C:\Users\_\Documents\GitHub\skiasharpwpfextensions\src\Imp.SkiaSharpWpfExtensions\SkiaControl.cs:line 83
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Imp.SkiaSharpWpfExtensions.Example.App.Main() in C:\Users\magnu_000\Documents\GitHub\skiasharpwpfextensions\src\Imp.SkiaSharpWpfExtensions.Example\obj\x64\Debug\App.g.cs:line 0
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

My guess is that the reason this is happening is the following [lines of code](https://github.com/mono/SkiaSharp/blob/master/binding/Binding/SKObject.cs#L116-L117) in `SKObject`:

    var shouldReplace =
                  reference == null ||
                  reference.Target != null ||
                  ((SKObject)reference.Target).Handle == IntPtr.Zero;

Lets assume that `reference` is not `null` but the `Target` property is. 

- `reference == null` would be `false`.
- `reference.Target != null` would be `false`

Since both the above expressions evaluate to `false` it is necessary to evaluate the last expression as well. But in this case `Target` is `null` and this is what is causing the exception.

**Comment by migueldeicaza** [comment]
Would you mind confirming is the bug is fixed with the pull request that you so kindly sent us?

**Comment by mgnslndh** [comment]
@migueldeicaza the bug was kind of random but always occurred after a short while. I have not been able to reproduce it but will leave the test application running over night just to be sure. Looks good.

**Comment by mgnslndh** [comment]
No crash during the night. I consider this bug fixed.

**Comment by migueldeicaza** [comment]
Thanks!
