### ISSUE TITLE
Error building SkiaSharp

### ISSUE THREAD

**Issue by GeorgyRezchikov** [mono/SkiaSharp#485]
Hello,

I trying to compile SkiaSharp. When running the ".\bootstrapper.ps1 -Target everything" I get an error:

========================================
externals-uwp
========================================
Executing task: externals-uwp
Done. Made 33 targets from 21 files in 347ms
ninja: Entering directory `out/winrt/x64'
ninja: no work to do.
Copying file libSkiaSharp.dll to C:/../SkiaSharp/output/native/uwp/x64/libSkiaSharp.dll
Copying file libSkiaSharp.pdb to C:/../SkiaSharp/output/native/uwp/x64/libSkiaSharp.pdb
Done. Made 33 targets from 21 files in 197ms
ninja: Entering directory `out/winrt/Win32'
ninja: no work to do.
Copying file libSkiaSharp.dll to C:/../SkiaSharp/output/native/uwp/x86/libSkiaSharp.dll
Copying file libSkiaSharp.pdb to C:/../SkiaSharp/output/native/uwp/x86/libSkiaSharp.pdb
Done. Made 33 targets from 21 files in 198ms
ninja: Entering directory `out/winrt/ARM'
[1/958] compile ../../../src/xamarin/SkManagedStream.cpp
FAILED: obj/src/xamarin/libSkiaSharp.SkManagedStream.obj 
cmd /c "set __VSCMD_ARG_NO_LOGO=1 && set VSCMD_START_DIR=%CD% && "C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.13.26128/../../../Auxiliary/Build/vcvarsall.bat" amd64_arm && "C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.13.26128/bin/HostX64/arm/cl.exe" /nologo /showIncludes /FC @obj/src/xamarin/libSkiaSharp.SkManagedStream.obj.rsp /c ../../../src/xamarin/SkManagedStream.cpp /Foobj/src/xamarin/libSkiaSharp.SkManagedStream.obj /Fd"obj/SkiaSharp_c.pdb""
[vcvarsall.bat] Environment initialized for: 'x64_arm'
System cannot find the path specified.
[2/958] compile ../../../src/xamarin/sk_managedstream.cpp
FAILED: obj/src/xamarin/libSkiaSharp.sk_managedstream.obj 
cmd /c "set __VSCMD_ARG_NO_LOGO=1 && set VSCMD_START_DIR=%CD% && "C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.13.26128/../../../Auxiliary/Build/vcvarsall.bat" amd64_arm && "C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.13.26128/bin/HostX64/arm/cl.exe" /nologo /showIncludes /FC @obj/src/xamarin/libSkiaSharp.sk_managedstream.obj.rsp /c ../../../src/xamarin/sk_managedstream.cpp /Foobj/src/xamarin/libSkiaSharp.sk_managedstream.obj /Fd"obj/SkiaSharp_c.pdb""
[vcvarsall.bat] Environment initialized for: 'x64_arm'
System cannot find the path specified.
[3/958] compile ../../../src/xamarin/sk_xamarin.cpp
FAILED: obj/src/xamarin/libSkiaSharp.sk_xamarin.obj 
cmd /c "set __VSCMD_ARG_NO_LOGO=1 && set VSCMD_START_DIR=%CD% && "C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.13.26128/../../../Auxiliary/Build/vcvarsall.bat" amd64_arm && "C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.13.26128/bin/HostX64/arm/cl.exe" /nologo /showIncludes /FC @obj/src/xamarin/libSkiaSharp.sk_xamarin.obj.rsp /c ../../../src/xamarin/sk_xamarin.cpp /Foobj/src/xamarin/libSkiaSharp.sk_xamarin.obj /Fd"obj/SkiaSharp_c.pdb""
[vcvarsall.bat] Environment initialized for: 'x64_arm'
System cannot find the path specified.
[4/958] compile ../../../src/xamarin/sk_managedpixelserializer.cpp
FAILED: obj/src/xamarin/libSkiaSharp.sk_managedpixelserializer.obj 
cmd /c "set __VSCMD_ARG_NO_LOGO=1 && set VSCMD_START_DIR=%CD% && "C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.13.26128/../../../Auxiliary/Build/vcvarsall.bat" amd64_arm && "C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.13.26128/bin/HostX64/arm/cl.exe" /nologo /showIncludes /FC @obj/src/xamarin/libSkiaSharp.sk_managedpixelserializer.obj.rsp /c ../../../src/xamarin/sk_managedpixelserializer.cpp /Foobj/src/xamarin/libSkiaSharp.sk_managedpixelserializer.obj /Fd"obj/SkiaSharp_c.pdb""
[vcvarsall.bat] Environment initialized for: 'x64_arm'
System cannot find the path specified.
[5/958] compile ../../../src/xamarin/SkManagedPixelSerializer.cpp
FAILED: obj/src/xamarin/libSkiaSharp.SkManagedPixelSerializer.obj 
cmd /c "set __VSCMD_ARG_NO_LOGO=1 && set VSCMD_START_DIR=%CD% && "C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.13.26128/../../../Auxiliary/Build/vcvarsall.bat" amd64_arm && "C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.13.26128/bin/HostX64/arm/cl.exe" /nologo /showIncludes /FC @obj/src/xamarin/libSkiaSharp.SkManagedPixelSerializer.obj.rsp /c ../../../src/xamarin/SkManagedPixelSerializer.cpp /Foobj/src/xamarin/libSkiaSharp.SkManagedPixelSerializer.obj /Fd"obj/SkiaSharp_c.pdb""
[vcvarsall.bat] Environment initialized for: 'x64_arm'
System cannot find the path specified.
[6/958] compile ../../../src/xamarin/SkiaKeeper.c
FAILED: obj/src/xamarin/libSkiaSharp.SkiaKeeper.obj 
cmd /c "set __VSCMD_ARG_NO_LOGO=1 && set VSCMD_START_DIR=%CD% && "C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.13.26128/../../../Auxiliary/Build/vcvarsall.bat" amd64_arm && "C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.13.26128/bin/HostX64/arm/cl.exe" /nologo /showIncludes /FC @obj/src/xamarin/libSkiaSharp.SkiaKeeper.obj.rsp /c ../../../src/xamarin/SkiaKeeper.c /Foobj/src/xamarin/libSkiaSharp.SkiaKeeper.obj /Fd"obj/SkiaSharp_c.pdb""
[vcvarsall.bat] Environment initialized for: 'x64_arm'
System cannot find the path specified.
ninja: build stopped: subcommand failed.

I did not find the arm folder on the specified path
![image](https://user-images.githubusercontent.com/28917934/38602242-d9d88e84-3d72-11e8-88a3-c7f0d2554186.png)

What should i setup to get the result?

**Comment by mattleibow** [comment]
You may have to check the ARM and ARM64 boxes in the "Individual components":

![image](https://user-images.githubusercontent.com/1096616/38611872-2f4af066-3d85-11e8-96cb-4161fdff1da5.png)

**Comment by GeorgyRezchikov** [comment]
Thanks very much!

But I have 1 more question.
I'm trying to build a project for Andriod (SkiaSharpSample.sln Andriod) on Windows
![image](https://user-images.githubusercontent.com/28917934/38626596-9948141e-3db5-11e8-8ec0-aa9a0ad44c91.png)

I get an error:
`Severity	Code	Description	Project	File	Line	Suppression State
Error		The "CreateNativeLibraryArchive" task failed unexpectedly.
System.IO.DirectoryNotFoundException: Could not find a part of the path '..\..\output\native\android\arm64-v8a\libHarfBuzzSharp.so'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Xamarin.Android.Tools.Files.CopyIfChanged(String source, String destination)
   at Xamarin.Android.Tasks.CreateNativeLibraryArchive.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	HarfBuzzSharp.Android			

   
Severity	Code	Description	Project	File	Line	Suppression State
Error		The "CreateNativeLibraryArchive" task failed unexpectedly.
System.IO.DirectoryNotFoundException: Could not find a part of the path '..\..\output\native\android\arm64-v8a\libSkiaSharp.so'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Xamarin.Android.Tools.Files.CopyIfChanged(String source, String destination)
   at Xamarin.Android.Tasks.CreateNativeLibraryArchive.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	SkiaSharp.Android			
  `
I looked at the build log SkiaSharp:

`========================================
Everything
========================================
Executing task: Everything
Finished executing task: Everything

Task                          Duration            
--------------------------------------------------
externals-angle-uwp           Skipped             
externals-harfbuzz            Skipped             
externals-init                00:00:01.4430322    
externals-uwp                 00:00:05.2655756    
externals-windows             00:00:03.0337583    
externals-osx                 Skipped             
externals-ios                 Skipped             
externals-tvos                Skipped             
externals-watchos             Skipped             
externals-android             Skipped             
externals-linux               Skipped             
externals-native              00:00:00.0004828    
externals                     00:00:00.0004161    
libs                          00:00:16.2721508    
nuget                         00:00:11.8867662    
tests                         00:00:43.8222085    
samples                       00:08:29.0243833    
Everything                    00:00:00.0004422    
`
In the BuildExternals file, the condition is IsRunningOnMac ()
`
// this builds the native C and C++ externals for Android
Task ("externals-android")
    .IsDependentOn ("externals-init")
    .WithCriteria (IsRunningOnMac ())
    .Does (() => 
`
How can I run an Android project on Windows?

**Comment by mattleibow** [comment]
@GeorgyRezchikov At this point, I have not done any Android development on Windows. When we started this project, skia was not able to build on Windows. I opened an issue so we can check this out again and see if we can get more platforms building Android: https://github.com/mono/SkiaSharp/issues/488

In the mean time, you can just download the binaries for you version you are testing with: https://github.com/mono/SkiaSharp/releases

For example, if you want to use the pre-built binaries for Android v1.60.0:

1. You can go to that release: https://github.com/mono/SkiaSharp/releases/tag/v1.60.0
2. Go to the Mac CI for SkiaSharp: https://jenkins.mono-project.com/view/Components/job/Components-SkiaSharp/328
3. In the "Azure Artifacts" link on the left, just look for the binaries:
    - https://jenkins.mono-project.com/view/Components/job/Components-SkiaSharp/328/Azure/processDownloadRequest/ArtifactsFor-328/abf9de57d9176e73a97e82a6402cfbd0e00127c5/output/native/android/armeabi-v7a/libSkiaSharp.so
    - https://jenkins.mono-project.com/view/Components/job/Components-SkiaSharp/328/Azure/processDownloadRequest/ArtifactsFor-328/abf9de57d9176e73a97e82a6402cfbd0e00127c5/output/native/android/arm64-v8a/libSkiaSharp.so
    - https://jenkins.mono-project.com/view/Components/job/Components-SkiaSharp/328/Azure/processDownloadRequest/ArtifactsFor-328/abf9de57d9176e73a97e82a6402cfbd0e00127c5/output/native/android/x86/libSkiaSharp.so
    - https://jenkins.mono-project.com/view/Components/job/Components-SkiaSharp/328/Azure/processDownloadRequest/ArtifactsFor-328/abf9de57d9176e73a97e82a6402cfbd0e00127c5/output/native/android/x86_64/libSkiaSharp.so
4. Download the various files and place them in the `output/native/android/` directory

This is not perfect yet, but we are slowly getting there.

**Comment by mattleibow** [comment]
Let me know if this helps.
