### ISSUE TITLE
Add a GTK# renderer for Xamarin.Forms

### ISSUE THREAD

**Issue by mattleibow** [mono/SkiaSharp#487]

**Comment by mattleibow** [comment]
Duplicate of https://github.com/mono/SkiaSharp/issues/379

**Comment by hflexgrig** [comment]
Is there any news from this. I'm currently using SkiaSharp.Views.Forms for my application, and it won't work for my application. Error i'm getting is

"System.InvalidCastException: Unable to cast object of type 'SkiaSharp.Views.Forms.SKCanvasViewRenderer' to type 'Xamarin.Forms.IRegisterable'.
   at Xamarin.Forms.Internals.Registrar`1.GetHandler(Type type, Type visualType) in D:\a\1\s\Xamarin.Forms.Core\Registrar.cs:line 71
   at Xamarin.Forms.Internals.Registrar`1.GetHandlerForObject[TOut](Object obj) in D:\a\1\s\Xamarin.Forms.Core\Registrar.cs:line 111
   at Xamarin.Forms.Platform.GTK.Platform.CreateRenderer(VisualElement element) in D:\a\1\s\Xamarin.Forms.Platform.GTK\Platform.cs:line 94
   at Xamarin.Forms.Platform.GTK.Packagers.PageElementPackager.OnChildAdded(VisualElement view) in D:\a\1\s\Xamarin.Forms.Platform.GTK\Packagers\PageElementPackager.cs:line 14
   at Xamarin.Forms.Platform.GTK.Packagers.VisualElementPackager`1.Load() in D:\a\1\s\Xamarin.Forms.Platform.GTK\Packagers\VisualElementPackager.cs:line 40
   at Xamarin.Forms.Platform.GTK.Renderers.PageRenderer.OnShown() in D:\a\1\s\Xamarin.Forms.Platform.GTK\Renderers\PageRenderer.cs:line 29
   at Gtk.Widget.shown_cb(IntPtr widget)
   at GLib.ExceptionManager.RaiseUnhandledException(Exception e, Boolean is_terminal)
   at Gtk.Widget.shown_cb(IntPtr widget)
   at Gtk.Widget.gtk_widget_show_all(IntPtr raw)
   at Xamarin.Forms.Platform.GTK.Renderers.TabbedPageRenderer.InsertPage(Page page, Int32 index) in D:\a\1\s\Xamarin.Forms.Platform.GTK\Renderers\TabbedPageRenderer.cs:line 150
   at Xamarin.Forms.Platform.GTK.Renderers.TabbedPageRenderer.ResetPages() in D:\a\1\s\Xamarin.Forms.Platform.GTK\Renderers\TabbedPageRenderer.cs:line 175
   at Xamarin.Forms.Platform.GTK.Renderers.TabbedPageRenderer.OnPagesChanged(Object sender, NotifyCollectionChangedEventArgs e) in D:\a\1\s\Xamarin.Forms.Platform.GTK\Renderers\TabbedPageRenderer.cs:line 116
   at Xamarin.Forms.Platform.GTK.Renderers.TabbedPageRenderer.Init() in D:\a\1\s\Xamarin.Forms.Platform.GTK\Renderers\TabbedPageRenderer.cs:line 48
   at Xamarin.Forms.Platform.GTK.Renderers.TabbedPageRenderer.OnElementChanged(VisualElementChangedEventArgs e) in D:\a\1\s\Xamarin.Forms.Platform.GTK\Renderers\TabbedPageRenderer.cs:line 44
   at Xamarin.Forms.Platform.GTK.Renderers.AbstractPageRenderer`2.SetElement(VisualElement element) in D:\a\1\s\Xamarin.Forms.Platform.GTK\Renderers\AbstractPageRenderer.cs:line 59
   at Xamarin.Forms.Platform.GTK.Platform.CreateRenderer(VisualElement element) in D:\a\1\s\Xamarin.Forms.Platform.GTK\Platform.cs:line 97
   at Xamarin.Forms.Platform.GTK.Platform.AddChild(Page mainPage) in D:\a\1\s\Xamarin.Forms.Platform.GTK\Platform.cs:line 143
   at Xamarin.Forms.Platform.GTK.Platform.SetPage(Page newRoot) in D:\a\1\s\Xamarin.Forms.Platform.GTK\Platform.cs:line 126
   at Xamarin.Forms.Platform.GTK.FormsWindow.UpdateMainPage() in D:\a\1\s\Xamarin.Forms.Platform.GTK\FormsWindow.cs:line 113
   at Xamarin.Forms.Platform.GTK.FormsWindow.LoadApplication(Application application) in D:\a\1\s\Xamarin.Forms.Platform.GTK\FormsWindow.cs:line 42
   at CSharpMath.Forms.Example.GTK.MainClass.Main(String[] args) in D:\Projects\csharpmath\CSharpMath.Forms.Example.GTK\Program.cs:line 19"

**Comment by mattleibow** [comment]
@hflexgrig this looks like you are missing the GTK renderers. Unfortunately, I just haven't gotten around to that yet. See this issue: https://github.com/mono/SkiaSharp/issues/379 If you really need to use GTK, you can have a go at creating your own renderers or giving https://github.com/mono/SkiaSharp/issues/379 a thumbs up to show support. As the votes come in, it moves up the list.
