### ISSUE TITLE
Large images shows blank after resizing

### ISSUE THREAD

**Issue by mattleibow** [mono/SkiaSharp#648]
_From @amerella on September 7, 2018 9:34_

When resizing a large image (> 6MB, 14034px by 9921px), the process goes through with no errors, but the image itself doesn't show upon save, only the white background canvas. The pixels cannot be read in the SKCodec, and similarly if I try and create an SKBitmap instead of an image, I get error 'Unable to allocate pixels for the bitmap'.

The code works fine with smaller images.

Is there a limit on how large a file size can be processed?
`using (SKMemoryStream sourceStream = new SKMemoryStream(imageData))
    {
        using (SKCodec codec = SKCodec.Create(sourceStream))
        {
            sourceStream.Seek(0);

            using (SKImage image = SKImage.FromEncodedData(SKData.Create(sourceStream)))
            {
                int newHeight = image.Height;
                int newWidth = image.Width;

                if (maxHeight > 0 && newHeight > maxHeight)
                {
                    double scale = (double)maxHeight / newHeight;
                    newHeight = maxHeight;
                    newWidth = (int)Math.Floor(newWidth * scale);
                }

                if (maxWidth > 0 && newWidth > maxWidth)
                {
                    double scale = (double)maxWidth / newWidth;
                    newWidth = maxWidth;
                    newHeight = (int)Math.Floor(newHeight * scale);
                }

                var info = codec.Info.ColorSpace.IsSrgb ? new SKImageInfo(newWidth, newHeight) : new SKImageInfo(newWidth, newHeight, SKImageInfo.PlatformColorType, SKAlphaType.Premul, SKColorSpace.CreateSrgb());
                using (SKSurface surface = SKSurface.Create(info))
                {
                    using (SKPaint paint = new SKPaint())
                    {
                        // High quality without antialiasing
                        paint.IsAntialias = true;
                        paint.FilterQuality = SKFilterQuality.High;

                        // Draw the bitmap to fill the surface
                        surface.Canvas.Clear(SKColors.White);
                        var rect = new SKRect(0, 0, newWidth, newHeight);
                        surface.Canvas.DrawImage(image, rect, paint);
                        surface.Canvas.Flush();

                        using (SKImage newImage = surface.Snapshot())
                        {
                            using (SKData newImageData = newImage.Encode(convertToJpeg ? SKEncodedImageFormat.Jpeg : (codec.EncodedFormat == SKEncodedImageFormat.Gif ? SKEncodedImageFormat.Png : codec.EncodedFormat), 
                                codec.EncodedFormat == SKEncodedImageFormat.Gif || codec.EncodedFormat == SKEncodedImageFormat.Png || !downsampleJpeg ? 100 : 85))
                            {
                                return newImageData.ToArray();
                            }
                        }
                    }
                }
            }
        }
    }
}`

_Copied from original issue: mono/SkiaSharp.Extended#49_

**Comment by mattleibow** [comment]
I belive this issue is actually a skia one: https://groups.google.com/forum/#!topic/skia-discuss/886WuVcQUGo

Unfortunately, there is nothing SkiaSharp can do until the actual library supports this.

**Comment by mattleibow** [comment]
Now that I think about it, I remember this question from somewhere else... Do you have a link so we can connect the dots?

**Comment by nor0x** [comment]
Hi @mattleibow 👋

are there any updates or workarounds for this issue, what's the best approach to render large images with Skia(Sharp) without downsampling?

**Comment by mattleibow** [comment]
Most probably the same issue: https://github.com/mono/SkiaSharp/issues/1249

**Comment by perumaal** [comment]
Hi,
The referenced issue seems different: Skia(Sharp?) drops images that are larger than 32K - hard-coded in the library.
However, this issue (which I am hitting as well) seems to surface on much smaller sized images.
Case in point:
 * Windows 10 Pro (1909 18363.778)
 * WPF + SkiaSharp (1.68.2.1\lib\net45\SkiaSharp.dll)
 * JPG with DSLR size 5286x3555 (roughly 11MB)
 * Decode results in:
    // Error reading file: <redacted>.JPG ; System.Exception: Unable to allocate pixels for the bitmap.
    // at SkiaSharp.SKBitmap..ctor(SKImageInfo info, Int32 rowBytes)
    // at SkiaSharp.SKBitmap.Decode(SKCodec codec, SKImageInfo bitmapInfo)
    // at SkiaSharp.SKBitmap.Decode(SKCodec codec)
    // at SkiaSharp.SKBitmap.Decode(SKStream stream)

Note that opening the same image in a Chromium-browser on the same machine works well (i.e. not a Skia issue?).

I am not sure if there is some contiguous memory allocation issue of sorts in the C# layer.

**Comment by mattleibow** [comment]
@perumaal do you have an example image?

**Comment by perumaal** [comment]
I realize I am stressing the system quite a bit here:
 * Manage 10 SKBitmap instances in memory.
 * Each SKBitmap is 4Kx4K (~64MB).
 * The Nth one (depending on the system) fails.

I don't expect Skia(Sharp) or any platform to withstand this pressure without some level of disk-based caching strategy.

Perhaps the only remaining issue is that the error is non-intuitive. (i.e. the error that arises results in folks coming to this page perhaps).

**Comment by Ziriax** [comment]
Yes that really should throw an OutOfMemory exception.

Also, I am not sure if SkiaSharp adds native memory pressure, so the GC knows about it.

https://docs.microsoft.com/en-us/dotnet/api/system.gc.addmemorypressure?redirectedfrom=MSDN&view=netcore-3.1#System_GC_AddMemoryPressure_System_Int64_
