### ISSUE TITLE
SKGLView exception when ViewExtensions.RotateYTo called on parent view [Xamarin Forms UWP]

### ISSUE THREAD

**Issue by comfr3ak** [mono/SkiaSharp#730]
### Description

When ViewExtensions.RotateYTo is called on the parent view (like a Grid) of an SKGLView, an unhandled exception occurs:

System.Exception: Failed to create EGL surface
   at SkiaSharp.Views.GlesInterop.GlesContext.CreateSurface(SwapChainPanel panel, Nullable`1 renderSurfaceSize, Nullable`1 resolutionScale)
   at SkiaSharp.Views.UWP.AngleSwapChainPanel.EnsureRenderSurface()
   at SkiaSharp.Views.UWP.AngleSwapChainPanel.OnCompositionChanged(SwapChainPanel sender, Object args)

### Code

Create a window with a Grid. Add a SKGLView object to the grid. Then perform the following call on the grid object several times from 180 to 0, leaving plenty of time in between. It will crash, usually on the first try:

	Xamarin.Forms.ViewExtensions.RotateYTo(<Your Grid Object>, 180, 300);

### Expected Behavior

The parent view should flip horizontally without crashing. 

### Actual Behavior

The parent view flips partially, then the application closes with the exception. Sometimes it succeeds but always crashes within a few tries. 

### Basic Information

- Version with issue:  1.68.0-preview28
- Last known good version:  None
- IDE:  VS2017
- Platform Target Frameworks: 
  - Android:  
  - iOS:  
  - Linux:  
  - macOS:  
  - Tizen:   
  - tvOS:  
  - UWP:   
  - watchOS:  
  - Windows Classic:  
- Target Devices:
  -

**Comment by gmurray81** [comment]
Hi,
Has anyone looked into this bug @mattleibow? I think I'm hitting the same issue with a simple Navigation action between pages containing the gl view.

**Comment by gmurray81** [comment]
I opened #1573 in case it was a distinct root cause.
