### ISSUE TITLE
New build issues

### ISSUE THREAD

**Issue by tdenniston** [mono/SkiaSharp#88]
Hello,

I'm running in to three separate build problems. I can refile them separately, but they seem like probably small or related issues so I opted to report all three in one.

1) I can't seem to build the 'tests' target right now:

```
========================================
tests
========================================
Executing task: tests
GET https://api.nuget.org/v3/index.json/Packages(Id='NUnit',Version='2.6.4')
GET https://api.nuget.org/v3/index.json/Packages(Id='NUnit',Version='2.6.4.0')
GET https://www.myget.org/F/xamprojectci/api/v2/Packages(Id='NUnit',Version='2.6.4')
GET https://www.myget.org/F/xamprojectci/api/v2/Packages(Id='NUnit',Version='2.6.4.0')
System.InvalidOperationException: Unable to find version '2.6.4' of package 'NUnit'.
   at NuGet.PackageHelper.ResolvePackage(IPackageRepository repository, String packageId, SemanticVersion version)
   at NuGet.Commands.RestoreCommand.RestorePackage(IFileSystem packagesFolderFileSystem, String packageId, SemanticVersi
on version, Boolean packageRestoreConsent, ConcurrentQueue`1 satellitePackages)
   at NuGet.Commands.RestoreCommand.<>c__DisplayClass5.<>c__DisplayClass7.<ExecuteInParallel>b__2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
An error occured when executing task.
Error: NuGet: Process returned an error.
```

2) The UWP targets are enabled because I'm running on Windows 7, but the managed libs do not build successfully. The native targets seem to build correctly, but when executing the "libs-windows" target I see tons of these errors:

```
========================================
libs-windows
========================================
Executing task: libs-windows
Microsoft (R) Build Engine version 14.0.25123.0
Copyright (C) Microsoft Corporation. All rights reserved.
...
     2>Done Building Project "C:\Users\Tyler\Documents\otherdev\SkiaSharp\binding\SkiaSharp.Desktop\SkiaSharp.Desktop.csproj" (default targets).
     1>Project "C:\Users\Tyler\Documents\otherdev\SkiaSharp\binding\SkiaSharp.Windows.sln" (1) is building "C:\Users\Tyler\Documents\otherdev\SkiaSharp\binding\SkiaSharp.Portable\SkiaSharp.Portable.csproj" (4) on node 1 (default targets).
     3>C:\Users\Tyler\Documents\otherdev\SkiaSharp\binding\SkiaSharp\Properties\SkiaSharpAssemblyInfo.cs(6,12): error CS0246: The type or namespace name 'AssemblyTitleAttribute' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\Tyler\Documents\otherdev\SkiaSharp\binding\SkiaSharp.UWP\SkiaSharp.UWP.csproj]
     3>C:\Users\Tyler\Documents\otherdev\SkiaSharp\binding\SkiaSharp\Properties\SkiaSharpAssemblyInfo.cs(6,12): error CS0246: The type or namespace name 'AssemblyTitle' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\Tyler\Documents\otherdev\SkiaSharp\binding\SkiaSharp.UWP\SkiaSharp.UWP.csproj]
...
     3>C:\Users\Tyler\AppData\Local\Temp\.NETCore,Version=v5.0.AssemblyAttributes.cs(4,20): error CS0400: The type or namespace name 'System' could not be found in the global namespace (are you missing an assembly reference?) [C:\Users\Tyler\Documents\otherdev\SkiaSharp\binding\SkiaSharp.UWP\SkiaSharp.UWP.csproj]
     3>C:\Users\Tyler\Documents\otherdev\SkiaSharp\binding\SkiaSharp\Properties\SkiaSharpAssemblyInfo.cs(6,27): error CS0518: Predefined type 'System.String' is not defined or imported 
...
     3>C:\Users\Tyler\Documents\otherdev\SkiaSharp\binding\Binding\SkiaApi.cs(37,26): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) 
...
    6 Warning(s)
    5974 Error(s)
```

3) When I comment out the UWP targets, remove the UWP project from `SkiaSharp.Windows.sln` and remove the `Skia.UWP.Demo.sln` solution from the `build.cake` "samples" target, everything else builds, but then I can't build the samples:

```
========================================
samples
========================================
Executing task: samples
GET https://api.nuget.org/v3/index.json/Packages(Id='Xamarin.Android.Support.Design',Version='23.3.0')
GET https://api.nuget.org/v3/index.json/Packages(Id='Xamarin.Forms',Version='2.3.0.38-pre2')
GET https://api.nuget.org/v3/index.json/Packages(Id='Xamarin.Android.Support.Animated.Vector.Drawable',Version='23.3.0')

GET https://api.nuget.org/v3/index.json/Packages(Id='SkiaSharp',Version='1.49.4-beta3')
GET https://api.nuget.org/v3/index.json/Packages(Id='Xamarin.Android.Support.Design',Version='23.3')
GET https://api.nuget.org/v3/index.json/Packages(Id='SkiaSharp',Version='1.49.4.0-beta3')
GET https://api.nuget.org/v3/index.json/Packages(Id='Xamarin.Android.Support.Animated.Vector.Drawable',Version='23.3')
GET https://api.nuget.org/v3/index.json/Packages(Id='Xamarin.Android.Support.Design',Version='23.3.0.0')
GET https://api.nuget.org/v3/index.json/Packages(Id='Xamarin.Android.Support.Animated.Vector.Drawable',Version='23.3.0.0
')
GET https://api.nuget.org/v3/index.json/Packages(Id='Xamarin.Android.Support.v4',Version='23.3.0')
GET https://api.nuget.org/v3/index.json/Packages(Id='Xamarin.Android.Support.v4',Version='23.3')
GET https://www.myget.org/F/xamprojectci/api/v2/Packages(Id='Xamarin.Forms',Version='2.3.0.38-pre2')
GET https://www.myget.org/F/xamprojectci/api/v2/Packages(Id='SkiaSharp',Version='1.49.4-beta3')
GET https://www.myget.org/F/xamprojectci/api/v2/Packages(Id='Xamarin.Android.Support.Design',Version='23.3.0')
GET https://www.myget.org/F/xamprojectci/api/v2/Packages(Id='Xamarin.Android.Support.Animated.Vector.Drawable',Version='
23.3.0')
GET https://api.nuget.org/v3/index.json/Packages(Id='Xamarin.Android.Support.v4',Version='23.3.0.0')
GET https://www.myget.org/F/xamprojectci/api/v2/Packages(Id='Xamarin.Android.Support.v4',Version='23.3.0')
GET https://api.nuget.org/v3/index.json/Packages(Id='Xamarin.Android.Support.v7.AppCompat',Version='23.3.0')
Installing 'SkiaSharp 1.49.4-beta3'.
Installing 'Xamarin.Android.Support.Animated.Vector.Drawable 23.3.0'.
Installing 'Xamarin.Android.Support.Design 23.3.0'.
GET https://www.myget.org/F/xamprojectci/api/v2/package/SkiaSharp/1.49.4-beta3
Successfully installed 'Xamarin.Android.Support.Animated.Vector.Drawable 23.3.0'.
GET https://api.nuget.org/v3/index.json/Packages(Id='Xamarin.Android.Support.v7.CardView',Version='23.3.0')
Installing 'Xamarin.Android.Support.v4 23.3.0'.
GET https://api.nuget.org/v3/index.json/Packages(Id='Xamarin.Android.Support.v7.AppCompat',Version='23.3')
Successfully installed 'Xamarin.Android.Support.Design 23.3.0'.
GET https://api.nuget.org/v3/index.json/Packages(Id='Xamarin.Android.Support.v7.MediaRouter',Version='23.3.0')
GET https://api.nuget.org/v3/index.json/Packages(Id='Xamarin.Android.Support.v7.MediaRouter',Version='23.3')
GET https://api.nuget.org/v3/index.json/Packages(Id='Xamarin.Android.Support.v7.CardView',Version='23.3')
GET https://api.nuget.org/v3/index.json/Packages(Id='Xamarin.Android.Support.v7.CardView',Version='23.3.0.0')
GET https://api.nuget.org/v3/index.json/Packages(Id='Xamarin.Android.Support.v7.AppCompat',Version='23.3.0.0')
GET https://www.myget.org/F/xamprojectci/api/v2/Packages(Id='Xamarin.Android.Support.v7.CardView',Version='23.3.0')
Successfully installed 'Xamarin.Android.Support.v4 23.3.0'.
GET https://api.nuget.org/v3/index.json/Packages(Id='Xamarin.Android.Support.v7.RecyclerView',Version='23.3.0')
GET https://api.nuget.org/v3/index.json/Packages(Id='Xamarin.Android.Support.v7.MediaRouter',Version='23.3.0.0')
GET https://www.myget.org/F/xamprojectci/api/v2/Packages(Id='Xamarin.Android.Support.v7.MediaRouter',Version='23.3.0')
GET https://www.myget.org/F/xamprojectci/api/v2/Packages(Id='Xamarin.Android.Support.v7.AppCompat',Version='23.3.0')
Installing 'Xamarin.Android.Support.v7.CardView 23.3.0'.
GET https://api.nuget.org/v3/index.json/Packages(Id='Xamarin.Android.Support.v7.RecyclerView',Version='23.3')
Successfully installed 'Xamarin.Android.Support.v7.CardView 23.3.0'.
GET https://api.nuget.org/v3/index.json/Packages(Id='Xamarin.Android.Support.Vector.Drawable',Version='23.3.0')
Installing 'Xamarin.Android.Support.v7.MediaRouter 23.3.0'.
GET https://api.nuget.org/v3/index.json/Packages(Id='Xamarin.Android.Support.Vector.Drawable',Version='23.3')
Installing 'Xamarin.Android.Support.v7.AppCompat 23.3.0'.
Successfully installed 'Xamarin.Android.Support.v7.MediaRouter 23.3.0'.
GET https://api.nuget.org/v3/index.json/Packages(Id='Xamarin.Android.Support.v7.RecyclerView',Version='23.3.0.0')
GET https://api.nuget.org/v3/index.json/Packages(Id='Xamarin.Android.Support.Vector.Drawable',Version='23.3.0.0')
Successfully installed 'Xamarin.Android.Support.v7.AppCompat 23.3.0'.
GET https://www.myget.org/F/xamprojectci/api/v2/Packages(Id='Xamarin.Android.Support.v7.RecyclerView',Version='23.3.0')
GET https://www.myget.org/F/xamprojectci/api/v2/Packages(Id='Xamarin.Android.Support.Vector.Drawable',Version='23.3.0')
Installing 'Xamarin.Android.Support.v7.RecyclerView 23.3.0'.
Installing 'Xamarin.Android.Support.Vector.Drawable 23.3.0'.
Successfully installed 'Xamarin.Android.Support.v7.RecyclerView 23.3.0'.
Successfully installed 'Xamarin.Android.Support.Vector.Drawable 23.3.0'.
System.NotSupportedException: ZIP archive contains unsupported data structures.
   at MS.Internal.IO.Zip.ZipArchive.VerifyVersionNeededToExtract(UInt16 version)
   at MS.Internal.IO.Zip.ZipIOLocalFileHeader.Validate()
   at MS.Internal.IO.Zip.ZipIOLocalFileHeader.ParseRecord(BinaryReader reader, Encoding encoding)
   at MS.Internal.IO.Zip.ZipIOLocalFileBlock.ParseRecord(BinaryReader reader, String fileName, Int64 position, ZipIOCent
ralDirectoryBlock centralDir, ZipIOCentralDirectoryFileHeader centralDirFileHeader)
   at MS.Internal.IO.Zip.ZipIOLocalFileBlock.SeekableLoad(ZipIOBlockManager blockManager, String fileName)
   at MS.Internal.IO.Zip.ZipIOBlockManager.LoadLocalFileBlock(String zipFileName)
   at MS.Internal.IO.Zip.ZipArchive.GetFile(String zipFileName)
   at MS.Internal.IO.Zip.ZipArchive.GetFiles()
   at System.IO.Packaging.ZipPackage.ContentTypeHelper..ctor(ZipArchive zipArchive, IgnoredItemHelper ignoredItemHelper)

   at System.IO.Packaging.ZipPackage..ctor(Stream s, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream, FileMode packageMode, FileAccess packageAccess, Boolean streaming)

   at System.IO.Packaging.Package.Open(Stream stream)
   at NuGet.PackageHelper.GetManifestStream(Stream packageStream)
   at NuGet.OptimizedZipPackage.EnsureManifest()
   at NuGet.OptimizedZipPackage..ctor(IFileSystem fileSystem, String packagePath)
   at NuGet.LocalPackageRepository.OpenPackage(String path)
   at NuGet.LocalPackageRepository.GetPackage(Func`2 openPackage, String path)
   at NuGet.LocalPackageRepository.<>c__DisplayClass13.<FindPackage>b__f(String path)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at NuGet.LocalPackageRepository.FindPackage(Func`2 openPackage, String packageId, SemanticVersion version)
   at NuGet.LocalPackageRepository.FindPackage(String packageId, SemanticVersion version)
   at NuGet.PackageRepositoryExtensions.FindPackage(IPackageRepository repository, String packageId, SemanticVersion ver
sion, IPackageConstraintProvider constraintProvider, Boolean allowPrereleaseVersions, Boolean allowUnlisted)
   at NuGet.DataServicePackage.EnsurePackage(IPackageCacheRepository cacheRepository)
   at NuGet.DataServicePackage.ExtractContents(IFileSystem fileSystem, String extractPath)
   at NuGet.Commands.DownloadCommandBase.CommandLineInstallPackageManager.OnExpandFiles(PackageOperationEventArgs e)
   at NuGet.PackageManager.ExecuteInstall(IPackage package)
   at NuGet.PackageManager.Execute(PackageOperation operation)
   at NuGet.PackageManager.Execute(IPackage package, IPackageOperationResolver resolver)
   at NuGet.PackageManager.InstallPackage(IPackage package, FrameworkName targetFramework, Boolean ignoreDependencies, B
oolean allowPrereleaseVersions, Boolean ignoreWalkInfo)
   at NuGet.PackageManager.InstallPackage(IPackage package, Boolean ignoreDependencies, Boolean allowPrereleaseVersions,
 Boolean ignoreWalkInfo)
   at NuGet.Common.PackageExtractor.<>c__DisplayClass1.<InstallPackage>b__0()
   at NuGet.Common.PackageExtractor.ExecuteLocked(String name, Action action)
   at NuGet.Common.PackageExtractor.InstallPackage(IPackageManager packageManager, IPackage package)
   at NuGet.Commands.RestoreCommand.RestorePackage(IFileSystem packagesFolderFileSystem, String packageId, SemanticVersi
on version, Boolean packageRestoreConsent, ConcurrentQueue`1 satellitePackages)
   at NuGet.Commands.RestoreCommand.<>c__DisplayClass5.<>c__DisplayClass7.<ExecuteInParallel>b__2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
System.InvalidOperationException: Unable to find version '2.3.0.38-pre2' of package 'Xamarin.Forms'.
   at NuGet.PackageHelper.ResolvePackage(IPackageRepository repository, String packageId, SemanticVersion version)
   at NuGet.Commands.RestoreCommand.RestorePackage(IFileSystem packagesFolderFileSystem, String packageId, SemanticVersi
on version, Boolean packageRestoreConsent, ConcurrentQueue`1 satellitePackages)
   at NuGet.Commands.RestoreCommand.<>c__DisplayClass5.<>c__DisplayClass7.<ExecuteInParallel>b__2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
An error occured when executing task.
Error: NuGet: Process returned an error.
```

**Comment by mattleibow** [comment]
Hi @tdenniston,
Thanks for reporting this, I believe it was my fault... and that of the machines. The current state was just so that our CI could pop out the NuGet for uploading, but then CI just had a few hiccups. Should be all nice now.

Issue 1, NuGet was having issues, so :(
Issue 2, You were building `SkiaSharp.UWP.csproj`, that also has to be removed from the binding solution `SkiaSharp.Windows.sln`
Issue 3, My bad, I used our internal feed for CI, but as NuGet was down, all the packages came from there - including the dodgy ones that we have

I fixed it to use the SkiaSharp from the output folder, and if NuGet has issues, it will just fail to restore the other packages.

Just a note: all is now well, and I have pushed out a new version: https://github.com/mono/SkiaSharp/releases/tag/v1.49.4-beta which has tvOS and PDF support
