### ISSUE TITLE
[BUG] Calling MeasureText with an empty string generates an exception

### ISSUE THREAD

**Issue by alexstrickland** [mono/SkiaSharp#957]
**Description**

Calling MeasureText with an empty string generates an exception.

**Code**

                    var textRectangle = new SKRect();
                    _textPaint.MeasureText("", ref textRectangle);

**Actual Behavior**

System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null.
Parameter name: buffer
  Source=SkiaSharp
  StackTrace:
   at SkiaSharp.SKPaint.MeasureText(IntPtr buffer, IntPtr length, SKRect& bounds)
   at SkiaSharp.SKPaint.MeasureText(Byte[] text, SKRect& bounds)
   at SkiaSharp.SKPaint.MeasureText(String text, SKRect& bounds)
   at AtillaX.UI.MainPage.canvasView_PaintSurface(Object sender, SKPaintSurfaceEventArgs skPaintSurfaceEventArgs) in C:\Users\alsasus\source\repos\AtillaX\AtillaX.UI\AtillaX.UI\MainPage.xaml.cs:line 81
   at SkiaSharp.Views.Forms.SKCanvasView.OnPaintSurface(SKPaintSurfaceEventArgs e)
   at SkiaSharp.Views.Forms.SKCanvasView.SkiaSharp.Views.Forms.ISKCanvasViewController.OnPaintSurface(SKPaintSurfaceEventArgs e)
   at SkiaSharp.Views.Forms.SKCanvasViewRendererBase`2.OnPaintSurface(Object sender, SKPaintSurfaceEventArgs e)
   at SkiaSharp.Views.UWP.SKXamlCanvas.OnPaintSurface(SKPaintSurfaceEventArgs e)
   at SkiaSharp.Views.UWP.SKXamlCanvas.DoInvalidate()
   at SkiaSharp.Views.UWP.SKXamlCanvas.Invalidate()
   at SkiaSharp.Views.UWP.SKXamlCanvas.OnSizeChanged(Object sender, SizeChangedEventArgs e)

**Basic Information**

- Version with issue:  SkiaSharp.View.Forms 1.68
- IDE:  Visual Studio
- Platform Target Frameworks: 
  - Android:  
  - UWP:

**Comment by michaldobrodenka** [comment]
Similar bug, already fixed (but in not yet released 1.68.1) https://github.com/mono/SkiaSharp/issues/734
